// useBeehiveBuyerTracking.ts
// Generated by CodeCreator
import { useEntityList, useEntityById, useCreateEntity, useUpdateEntity, useDeleteEntity } from './useEntityCRUD';
import { BeehiveBuyerTrackingApi } from '../api/BeehiveBuyerTrackingApi';
import type { BeehiveBuyerTracking, CreateBeehiveBuyerTrackingRequest, UpdateBeehiveBuyerTrackingRequest } from '../types/BeehiveBuyerTracking';

export const useBeehiveBuyerTrackings = (page = 0, pageSize = 25, search = '', sortField = '', sortDir = 'asc') =>
  useEntityList<BeehiveBuyerTracking>('beehiveBuyerTrackings', BeehiveBuyerTrackingApi.getAll, page, pageSize, search, sortField, sortDir);

export const useBeehiveBuyerTracking = (id: number) =>
  useEntityById<BeehiveBuyerTracking>('beehiveBuyerTrackings', BeehiveBuyerTrackingApi.getById, id);

export const useCreateBeehiveBuyerTracking = () =>
  useCreateEntity<BeehiveBuyerTracking, CreateBeehiveBuyerTrackingRequest>('beehiveBuyerTrackings', BeehiveBuyerTrackingApi.create, 'Beehive Buyer Tracking');

export function useUpdateBeehiveBuyerTracking() {
  const mutation = useUpdateEntity<BeehiveBuyerTracking, UpdateBeehiveBuyerTrackingRequest>('beehiveBuyerTrackings', BeehiveBuyerTrackingApi.update, 'Beehive Buyer Tracking');
  return {
    ...mutation,
    mutate: (params: { id: number; data: UpdateBeehiveBuyerTrackingRequest }) =>
      mutation.mutate({ id: params.id, data: params.data }),
    mutateAsync: (params: { id: number; data: UpdateBeehiveBuyerTrackingRequest }) =>
      mutation.mutateAsync({ id: params.id, data: params.data }),
  };
}

export const useDeleteBeehiveBuyerTracking = () =>
  useDeleteEntity('beehiveBuyerTrackings', BeehiveBuyerTrackingApi.delete, 'Beehive Buyer Tracking');


