// useCustomerDebt.ts
// Generated by CodeCreator
import { useEntityList, useEntityById, useCreateEntity, useUpdateEntity, useDeleteEntity } from './useEntityCRUD';
import { CustomerDebtApi } from '../api/CustomerDebtApi';
import type { CustomerDebt, CreateCustomerDebtRequest, UpdateCustomerDebtRequest } from '../types/CustomerDebt';

export const useCustomerDebts = (page = 0, pageSize = 25, search = '', sortField = '', sortDir = 'asc') =>
  useEntityList<CustomerDebt>('customerDebts', CustomerDebtApi.getAll, page, pageSize, search, sortField, sortDir);

export const useCustomerDebt = (id: number) =>
  useEntityById<CustomerDebt>('customerDebts', CustomerDebtApi.getById, id);

export const useCreateCustomerDebt = () =>
  useCreateEntity<CustomerDebt, CreateCustomerDebtRequest>('customerDebts', CustomerDebtApi.create, 'Customer Debt');

export function useUpdateCustomerDebt() {
  const mutation = useUpdateEntity<CustomerDebt, UpdateCustomerDebtRequest>('customerDebts', CustomerDebtApi.update, 'Customer Debt');
  return {
    ...mutation,
    mutate: (params: { id: number; data: UpdateCustomerDebtRequest }) =>
      mutation.mutate({ id: params.id, data: params.data }),
    mutateAsync: (params: { id: number; data: UpdateCustomerDebtRequest }) =>
      mutation.mutateAsync({ id: params.id, data: params.data }),
  };
}

export const useDeleteCustomerDebt = () =>
  useDeleteEntity('customerDebts', CustomerDebtApi.delete, 'Customer Debt');


