// useCustomer.ts
// Generated by CodeCreator
import { useEntityList, useEntityById, useCreateEntity, useUpdateEntity, useDeleteEntity } from './useEntityCRUD';
import { CustomerApi } from '../api/CustomerApi';
import type { Customer, CreateCustomerRequest, UpdateCustomerRequest } from '../types/Customer';

export const useCustomers = (page = 0, pageSize = 25, search = '', sortField = '', sortDir = 'asc') =>
  useEntityList<Customer>('customers', CustomerApi.getAll, page, pageSize, search, sortField, sortDir);

export const useCustomer = (id: number) =>
  useEntityById<Customer>('customers', CustomerApi.getById, id);

export const useCreateCustomer = () =>
  useCreateEntity<Customer, CreateCustomerRequest>('customers', CustomerApi.create, 'Customer');

export function useUpdateCustomer() {
  const mutation = useUpdateEntity<Customer, UpdateCustomerRequest>('customers', CustomerApi.update, 'Customer');
  return {
    ...mutation,
    mutate: (params: { id: number; data: UpdateCustomerRequest }) =>
      mutation.mutate({ id: params.id, data: params.data }),
    mutateAsync: (params: { id: number; data: UpdateCustomerRequest }) =>
      mutation.mutateAsync({ id: params.id, data: params.data }),
  };
}

export const useDeleteCustomer = () =>
  useDeleteEntity('customers', CustomerApi.delete, 'Customer');


