// useDelivery.ts
// Generated by CodeCreator
import { useEntityList, useEntityById, useCreateEntity, useUpdateEntity, useDeleteEntity } from './useEntityCRUD';
import { DeliveryApi } from '../api/DeliveryApi';
import type { Delivery, CreateDeliveryRequest, UpdateDeliveryRequest } from '../types/Delivery';

export const useDeliveries = (page = 0, pageSize = 25, search = '', sortField = '', sortDir = 'asc') =>
  useEntityList<Delivery>('deliveries', DeliveryApi.getAll, page, pageSize, search, sortField, sortDir);

export const useDelivery = (id: number) =>
  useEntityById<Delivery>('deliveries', DeliveryApi.getById, id);

export const useCreateDelivery = () =>
  useCreateEntity<Delivery, CreateDeliveryRequest>('deliveries', DeliveryApi.create, 'Delivery');

export function useUpdateDelivery() {
  const mutation = useUpdateEntity<Delivery, UpdateDeliveryRequest>('deliveries', DeliveryApi.update, 'Delivery');
  return {
    ...mutation,
    mutate: (params: { id: number; data: UpdateDeliveryRequest }) =>
      mutation.mutate({ id: params.id, data: params.data }),
    mutateAsync: (params: { id: number; data: UpdateDeliveryRequest }) =>
      mutation.mutateAsync({ id: params.id, data: params.data }),
  };
}

export const useDeleteDelivery = () =>
  useDeleteEntity('deliveries', DeliveryApi.delete, 'Delivery');


