// useEntityCRUD.ts
// Generated by CodeCreator - Generic CRUD hook factory
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useNotification } from '../contexts/NotificationContext';

// Generic API interface that all entity APIs conform to
export interface EntityApi<T, TCreate = unknown, TUpdate = unknown> {
  getAll(page: number, pageSize: number, search: string): Promise<{ items: T[]; total: number }>;
  getById(id: number | string): Promise<T>;
  create?(data: TCreate): Promise<T>;
  update?(id: number | string, data: TUpdate): Promise<T>;
  delete?(id: number | string): Promise<void>;
}

export function useEntityList<T>(
  entityKey: string,
  apiFn: (page: number, pageSize: number, search: string, sortField: string, sortDir: string) => Promise<{ items: T[]; total: number }>,
  page: number = 0,
  pageSize: number = 25,
  search: string = '',
  sortField: string = '',
  sortDir: string = 'asc'
) {
  return useQuery({
    queryKey: [entityKey, page, pageSize, search, sortField, sortDir],
    queryFn: () => apiFn(page, pageSize, search, sortField, sortDir),
    placeholderData: (prev) => prev,
  });
}

export function useEntityById<T>(
  entityKey: string,
  apiFn: (id: number | string) => Promise<T>,
  id: number | string
) {
  return useQuery({
    queryKey: [entityKey, id],
    queryFn: () => apiFn(id),
    enabled: Boolean(id),
  });
}

export function useCreateEntity<T, TCreate>(
  entityKey: string,
  apiFn: (data: TCreate) => Promise<T>,
  label: string
) {
  const queryClient = useQueryClient();
  const { showSuccess, showError } = useNotification();
  return useMutation({
    mutationFn: (data: TCreate) => apiFn(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [entityKey] });
      showSuccess(`${label} created successfully`);
    },
    onError: (error: Error) => {
      showError(error.message || `Failed to create ${label.toLowerCase()}`);
    },
  });
}

/** Custom error for 409 Conflict (optimistic concurrency) */
export class ConflictError extends Error {
  currentData: unknown;
  constructor(message: string, currentData?: unknown) {
    super(message);
    this.name = 'ConflictError';
    this.currentData = currentData;
  }
}

export function useUpdateEntity<T, TUpdate>(
  entityKey: string,
  apiFn: (id: number | string, data: TUpdate) => Promise<T>,
  label: string
) {
  const queryClient = useQueryClient();
  const { showSuccess, showError } = useNotification();
  return useMutation({
    mutationFn: async (params: { id: number | string; data: TUpdate }) => {
      try {
        return await apiFn(params.id, params.data);
      } catch (err: unknown) {
        if (err && typeof err === 'object' && 'response' in err) {
          const axiosErr = err as { response?: { status?: number; data?: { message?: string; currentData?: unknown } } };
          if (axiosErr.response?.status === 409) {
            throw new ConflictError(
              axiosErr.response.data?.message || 'Record was modified by another user.',
              axiosErr.response.data?.currentData
            );
          }
        }
        throw err;
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [entityKey] });
      showSuccess(`${label} updated successfully`);
    },
    onError: (error: Error) => {
      if (error instanceof ConflictError) return; // Form handles conflict UI
      showError(error.message || `Failed to update ${label.toLowerCase()}`);
    },
  });
}

export function useDeleteEntity(
  entityKey: string,
  apiFn: (id: number | string) => Promise<void>,
  label: string
) {
  const queryClient = useQueryClient();
  const { showSuccess, showError } = useNotification();
  return useMutation({
    mutationFn: (id: number | string) => apiFn(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: [entityKey] });
      showSuccess(`${label} deleted successfully`);
    },
    onError: (error: Error) => {
      showError(error.message || `Failed to delete ${label.toLowerCase()}`);
    },
  });
}

