// useEnumValues.ts
// Generated by CodeCreator - Hook for fetching enum dropdown values
import { useQuery } from '@tanstack/react-query';
import { EnumApi, type EnumOption } from '../api/EnumApi';

export function useEnumValues(enumType: string): EnumOption[] {
  const { data } = useQuery({
    queryKey: ['enums'],
    queryFn: () => EnumApi.getAll(),
    staleTime: Infinity,
  });

  if (!data) return [];
  const match = data.find((e) => e.enumType.toLowerCase() === enumType.toLowerCase());
  return match?.values || [];
}

export function useEnumLabel(enumType: string, value: number): string {
  const options = useEnumValues(enumType);
  const match = options.find((o) => o.value === value);
  return match?.label || String(value);
}

