// useOrderLine.ts
// Generated by CodeCreator
import { useEntityList, useEntityById, useCreateEntity, useUpdateEntity, useDeleteEntity } from './useEntityCRUD';
import { OrderLineApi } from '../api/OrderLineApi';
import type { OrderLine, CreateOrderLineRequest, UpdateOrderLineRequest } from '../types/OrderLine';

export const useOrderLines = (page = 0, pageSize = 25, search = '', sortField = '', sortDir = 'asc') =>
  useEntityList<OrderLine>('orderLines', OrderLineApi.getAll, page, pageSize, search, sortField, sortDir);

export const useOrderLine = (id: number) =>
  useEntityById<OrderLine>('orderLines', OrderLineApi.getById, id);

export const useCreateOrderLine = () =>
  useCreateEntity<OrderLine, CreateOrderLineRequest>('orderLines', OrderLineApi.create, 'Order Line');

export function useUpdateOrderLine() {
  const mutation = useUpdateEntity<OrderLine, UpdateOrderLineRequest>('orderLines', OrderLineApi.update, 'Order Line');
  return {
    ...mutation,
    mutate: (params: { id: number; data: UpdateOrderLineRequest }) =>
      mutation.mutate({ id: params.id, data: params.data }),
    mutateAsync: (params: { id: number; data: UpdateOrderLineRequest }) =>
      mutation.mutateAsync({ id: params.id, data: params.data }),
  };
}

export const useDeleteOrderLine = () =>
  useDeleteEntity('orderLines', OrderLineApi.delete, 'Order Line');


