// useOrderHeader.ts
// Generated by CodeCreator
import { useEntityList, useEntityById, useCreateEntity, useUpdateEntity, useDeleteEntity } from './useEntityCRUD';
import { OrderHeaderApi } from '../api/OrderHeaderApi';
import type { OrderHeader, CreateOrderHeaderRequest, UpdateOrderHeaderRequest } from '../types/OrderHeader';

export const useOrderHeaders = (page = 0, pageSize = 25, search = '', sortField = '', sortDir = 'asc') =>
  useEntityList<OrderHeader>('orderHeaders', OrderHeaderApi.getAll, page, pageSize, search, sortField, sortDir);

export const useOrderHeader = (id: number) =>
  useEntityById<OrderHeader>('orderHeaders', OrderHeaderApi.getById, id);

export const useCreateOrderHeader = () =>
  useCreateEntity<OrderHeader, CreateOrderHeaderRequest>('orderHeaders', OrderHeaderApi.create, 'Order Header');

export function useUpdateOrderHeader() {
  const mutation = useUpdateEntity<OrderHeader, UpdateOrderHeaderRequest>('orderHeaders', OrderHeaderApi.update, 'Order Header');
  return {
    ...mutation,
    mutate: (params: { id: number; data: UpdateOrderHeaderRequest }) =>
      mutation.mutate({ id: params.id, data: params.data }),
    mutateAsync: (params: { id: number; data: UpdateOrderHeaderRequest }) =>
      mutation.mutateAsync({ id: params.id, data: params.data }),
  };
}

export const useDeleteOrderHeader = () =>
  useDeleteEntity('orderHeaders', OrderHeaderApi.delete, 'Order Header');


