// useProductPrice.ts
// Generated by CodeCreator
import { useEntityList, useEntityById, useCreateEntity, useUpdateEntity, useDeleteEntity } from './useEntityCRUD';
import { ProductPriceApi } from '../api/ProductPriceApi';
import type { ProductPrice, CreateProductPriceRequest, UpdateProductPriceRequest } from '../types/ProductPrice';

export const useProductPrices = (page = 0, pageSize = 25, search = '', sortField = '', sortDir = 'asc') =>
  useEntityList<ProductPrice>('productPrices', ProductPriceApi.getAll, page, pageSize, search, sortField, sortDir);

export const useProductPrice = (id: number) =>
  useEntityById<ProductPrice>('productPrices', ProductPriceApi.getById, id);

export const useCreateProductPrice = () =>
  useCreateEntity<ProductPrice, CreateProductPriceRequest>('productPrices', ProductPriceApi.create, 'Product Price');

export function useUpdateProductPrice() {
  const mutation = useUpdateEntity<ProductPrice, UpdateProductPriceRequest>('productPrices', ProductPriceApi.update, 'Product Price');
  return {
    ...mutation,
    mutate: (params: { id: number; data: UpdateProductPriceRequest }) =>
      mutation.mutate({ id: params.id, data: params.data }),
    mutateAsync: (params: { id: number; data: UpdateProductPriceRequest }) =>
      mutation.mutateAsync({ id: params.id, data: params.data }),
  };
}

export const useDeleteProductPrice = () =>
  useDeleteEntity('productPrices', ProductPriceApi.delete, 'Product Price');


