// useProductPriceHist.ts
// Generated by CodeCreator
import { useEntityList, useEntityById, useCreateEntity, useUpdateEntity, useDeleteEntity } from './useEntityCRUD';
import { ProductPriceHistApi } from '../api/ProductPriceHistApi';
import type { ProductPriceHist, CreateProductPriceHistRequest, UpdateProductPriceHistRequest } from '../types/ProductPriceHist';

export const useProductPriceHists = (page = 0, pageSize = 25, search = '', sortField = '', sortDir = 'asc') =>
  useEntityList<ProductPriceHist>('productPriceHists', ProductPriceHistApi.getAll, page, pageSize, search, sortField, sortDir);

export const useProductPriceHist = (id: number) =>
  useEntityById<ProductPriceHist>('productPriceHists', ProductPriceHistApi.getById, id);

export const useCreateProductPriceHist = () =>
  useCreateEntity<ProductPriceHist, CreateProductPriceHistRequest>('productPriceHists', ProductPriceHistApi.create, 'Product Price Hist');

export function useUpdateProductPriceHist() {
  const mutation = useUpdateEntity<ProductPriceHist, UpdateProductPriceHistRequest>('productPriceHists', ProductPriceHistApi.update, 'Product Price Hist');
  return {
    ...mutation,
    mutate: (params: { id: number; data: UpdateProductPriceHistRequest }) =>
      mutation.mutate({ id: params.id, data: params.data }),
    mutateAsync: (params: { id: number; data: UpdateProductPriceHistRequest }) =>
      mutation.mutateAsync({ id: params.id, data: params.data }),
  };
}

export const useDeleteProductPriceHist = () =>
  useDeleteEntity('productPriceHists', ProductPriceHistApi.delete, 'Product Price Hist');


