// useProduct.ts
// Generated by CodeCreator
import { useEntityList, useEntityById, useCreateEntity, useUpdateEntity, useDeleteEntity } from './useEntityCRUD';
import { ProductApi } from '../api/ProductApi';
import type { Product, CreateProductRequest, UpdateProductRequest } from '../types/Product';

export const useProducts = (page = 0, pageSize = 25, search = '', sortField = '', sortDir = 'asc') =>
  useEntityList<Product>('products', ProductApi.getAll, page, pageSize, search, sortField, sortDir);

export const useProduct = (id: number) =>
  useEntityById<Product>('products', ProductApi.getById, id);

export const useCreateProduct = () =>
  useCreateEntity<Product, CreateProductRequest>('products', ProductApi.create, 'Product');

export function useUpdateProduct() {
  const mutation = useUpdateEntity<Product, UpdateProductRequest>('products', ProductApi.update, 'Product');
  return {
    ...mutation,
    mutate: (params: { id: number; data: UpdateProductRequest }) =>
      mutation.mutate({ id: params.id, data: params.data }),
    mutateAsync: (params: { id: number; data: UpdateProductRequest }) =>
      mutation.mutateAsync({ id: params.id, data: params.data }),
  };
}

export const useDeleteProduct = () =>
  useDeleteEntity('products', ProductApi.delete, 'Product');


