// useSupplierOrder.ts
// Generated by CodeCreator
import { useEntityList, useEntityById, useCreateEntity, useUpdateEntity, useDeleteEntity } from './useEntityCRUD';
import { SupplierOrderApi } from '../api/SupplierOrderApi';
import type { SupplierOrder, CreateSupplierOrderRequest, UpdateSupplierOrderRequest } from '../types/SupplierOrder';

export const useSupplierOrders = (page = 0, pageSize = 25, search = '', sortField = '', sortDir = 'asc') =>
  useEntityList<SupplierOrder>('supplierOrders', SupplierOrderApi.getAll, page, pageSize, search, sortField, sortDir);

export const useSupplierOrder = (id: number) =>
  useEntityById<SupplierOrder>('supplierOrders', SupplierOrderApi.getById, id);

export const useCreateSupplierOrder = () =>
  useCreateEntity<SupplierOrder, CreateSupplierOrderRequest>('supplierOrders', SupplierOrderApi.create, 'Supplier Order');

export function useUpdateSupplierOrder() {
  const mutation = useUpdateEntity<SupplierOrder, UpdateSupplierOrderRequest>('supplierOrders', SupplierOrderApi.update, 'Supplier Order');
  return {
    ...mutation,
    mutate: (params: { id: number; data: UpdateSupplierOrderRequest }) =>
      mutation.mutate({ id: params.id, data: params.data }),
    mutateAsync: (params: { id: number; data: UpdateSupplierOrderRequest }) =>
      mutation.mutateAsync({ id: params.id, data: params.data }),
  };
}

export const useDeleteSupplierOrder = () =>
  useDeleteEntity('supplierOrders', SupplierOrderApi.delete, 'Supplier Order');


