// AuthContext.tsx
// Generated by CodeCreator - Authentication context with JWT token
import { createContext, useContext, useState, useCallback, useEffect, useRef, type ReactNode } from 'react';
import { api } from '../api/client';

const SESSION_TIMEOUT_MS = 30 * 60 * 1000; // 30 minutes
const SESSION_WARNING_MS = 60 * 1000; // Show warning 60 seconds before timeout

interface AuthUser {
  username: string;
  token: string;
  permissions: string[];
}

interface AuthContextType {
  user: AuthUser | null;
  isAuthenticated: boolean;
  permissions: string[];
  login: (username: string, password: string) => Promise<void>;
  logout: () => void;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AuthUser | null>(() => {
    const stored = localStorage.getItem('auth_user');
    if (stored) {
      try { return JSON.parse(stored); } catch { return null; }
    }
    return null;
  });

  const login = useCallback(async (username: string, password: string) => {
    // POST /api/auth/login - generated AuthController verifies against c_User table
    const { data } = await api.post<{ token: string; permissions?: string[] }>('/auth/login', { username, password });
    const authUser: AuthUser = { username, token: data.token, permissions: data.permissions ?? [] };
    setUser(authUser);
    localStorage.setItem('auth_user', JSON.stringify(authUser));
    localStorage.setItem('auth_token', data.token);
    api.defaults.headers.common['Authorization'] = `Bearer ${data.token}`;
  }, []);

  const logout = useCallback(() => {
    setUser(null);
    localStorage.removeItem('auth_user');
    localStorage.removeItem('auth_token');
    delete api.defaults.headers.common['Authorization'];
  }, []);

  // Restore token on mount
  if (user?.token) {
    api.defaults.headers.common['Authorization'] = `Bearer ${user.token}`;
  }

  // Session timeout / idle detection
  const [showTimeoutWarning, setShowTimeoutWarning] = useState(false);
  const lastActivityRef = useRef(Date.now());
  useEffect(() => {
    if (!user) return;
    const resetActivity = () => { lastActivityRef.current = Date.now(); setShowTimeoutWarning(false); };
    const events = ['mousedown', 'keydown', 'scroll', 'touchstart'] as const;
    events.forEach((e) => window.addEventListener(e, resetActivity));
    const interval = setInterval(() => {
      const idle = Date.now() - lastActivityRef.current;
      if (idle >= SESSION_TIMEOUT_MS) { logout(); }
      else if (idle >= SESSION_TIMEOUT_MS - SESSION_WARNING_MS) { setShowTimeoutWarning(true); }
    }, 10000);
    return () => { events.forEach((e) => window.removeEventListener(e, resetActivity)); clearInterval(interval); };
  }, [user, logout]);

  return (
    <AuthContext.Provider value={{ user, isAuthenticated: Boolean(user), permissions: user?.permissions ?? [], login, logout }}>
      {showTimeoutWarning && (
        <div style={{ position: 'fixed', top: 0, left: 0, right: 0, zIndex: 9999, background: '#ff9800', color: '#000', textAlign: 'center', padding: '8px', fontSize: '14px' }}>
          Session expiring due to inactivity. Move your mouse to stay logged in.
        </div>
      )}
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (!context) throw new Error('useAuth must be used within AuthProvider');
  return context;
}

export function usePermission(entity: string, action: 'read' | 'write' | 'delete'): boolean {
  const { permissions } = useAuth();
  // If no permissions array (empty), assume all allowed for backward compatibility
  if (permissions.length === 0) return true;
  return permissions.includes(`${entity}:${action}`);
}

export function PermissionGate({
  entity,
  action,
  children,
}: {
  entity: string;
  action: 'read' | 'write' | 'delete';
  children: ReactNode;
}) {
  const allowed = usePermission(entity, action);
  if (!allowed) return null;
  return <>{children}</>;
}

