// NotificationContext.tsx
// Generated by CodeCreator - Toast notification system
import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';
import { Snackbar, Alert, type AlertColor } from '@mui/material';

interface Notification {
  message: string;
  severity: AlertColor;
  key: number;
}

interface NotificationHistoryItem {
  message: string;
  severity: AlertColor;
  timestamp: Date;
  read: boolean;
}

interface NotificationContextType {
  showSuccess: (message: string) => void;
  showError: (message: string) => void;
  showWarning: (message: string) => void;
  showInfo: (message: string) => void;
  history: NotificationHistoryItem[];
  unreadCount: number;
  markAllRead: () => void;
  clearHistory: () => void;
}

const NotificationContext = createContext<NotificationContextType | null>(null);

export function useNotification() {
  const ctx = useContext(NotificationContext);
  if (!ctx) throw new Error('useNotification must be used within NotificationProvider');
  return ctx;
}

export function NotificationProvider({ children }: { children: ReactNode }) {
  const [notification, setNotification] = useState<Notification | null>(null);
  const [history, setHistory] = useState<NotificationHistoryItem[]>([]);

  const show = useCallback((message: string, severity: AlertColor) => {
    setNotification({ message, severity, key: Date.now() });
    setHistory((prev) => [{ message, severity, timestamp: new Date(), read: false }, ...prev].slice(0, 50));
  }, []);

  const markAllRead = useCallback(() => setHistory((prev) => prev.map((n) => ({ ...n, read: true }))), []);
  const clearHistory = useCallback(() => setHistory([]), []);
  const unreadCount = history.filter((n) => !n.read).length;

  const value: NotificationContextType = {
    showSuccess: useCallback((msg: string) => show(msg, 'success'), [show]),
    showError: useCallback((msg: string) => show(msg, 'error'), [show]),
    showWarning: useCallback((msg: string) => show(msg, 'warning'), [show]),
    showInfo: useCallback((msg: string) => show(msg, 'info'), [show]),
    history, unreadCount, markAllRead, clearHistory,
  };

  return (
    <NotificationContext.Provider value={value}>
      {children}
      <Snackbar
        key={notification?.key}
        open={Boolean(notification)}
        autoHideDuration={4000}
        onClose={() => setNotification(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
      >
        {notification ? (
          <Alert
            onClose={() => setNotification(null)}
            severity={notification.severity}
            variant="filled"
            sx={{ width: '100%' }}
          >
            {notification.message}
          </Alert>
        ) : undefined}
      </Snackbar>
    </NotificationContext.Provider>
  );
}

