// CustomerList.tsx
// Generated by CodeCreator
import { useState, useCallback } from 'react';
import type { GridSortModel } from '@mui/x-data-grid';
import { type GridColDef, GridActionsCellItem } from '@mui/x-data-grid';
import { Box, Alert, Button, Dialog, DialogTitle, DialogContent } from '@mui/material';
import { Visibility as ViewIcon } from '@mui/icons-material';
import { ContentCopy as ContentCopyIcon } from '@mui/icons-material';
import { OpenInNew as OpenInNewIcon } from '@mui/icons-material';
import { Edit as EditIcon } from '@mui/icons-material';
import { Delete as DeleteIcon } from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import { useCustomers, useUpdateCustomer, useDeleteCustomer } from '../hooks/useCustomer';
import AppDataGrid from '../components/shared/AppDataGrid';
import ConfirmDialog from '../components/shared/ConfirmDialog';
import { useEnumValues } from '../hooks/useEnumValues';
import { useNotification } from '../contexts/NotificationContext';
import { PermissionGate } from '../contexts/AuthContext';
import CustomerForm from './CustomerForm';
import type { UpdateCustomerRequest } from '../types/Customer';
import FilterBuilder from '../components/shared/FilterBuilder';
import FilterListIcon from '@mui/icons-material/FilterList';
import he from '../i18n/he';
import { Collapse } from '@mui/material';

export default function CustomerList() {
  const [paginationModel, setPaginationModel] = useState({ page: 0, pageSize: 25 });
  const [search, setSearch] = useState('');
  const [sortModel, setSortModel] = useState<GridSortModel>([]);
  const [showFilters, setShowFilters] = useState(false);
  const [activeFilters, setActiveFilters] = useState<Record<string, unknown>>({});
  const sortField = sortModel[0]?.field ?? '';
  const sortDir = sortModel[0]?.sort ?? 'asc';
  const handleSortModelChange = useCallback((model: GridSortModel) => {
    setSortModel(model);
    setPaginationModel((prev) => ({ ...prev, page: 0 }));
  }, []);
  const { data, isLoading, isError, error } = useCustomers(paginationModel.page, paginationModel.pageSize, search, sortField, sortDir);
  const deleteMutation = useDeleteCustomer();
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const [selectedIds, setSelectedIds] = useState<(string | number)[]>([]);
  const [bulkDeleteConfirm, setBulkDeleteConfirm] = useState(false);
  const navigate = useNavigate();
  const { showSuccess } = useNotification();
  const updateMutation = useUpdateCustomer();
  const [quickCreateOpen, setQuickCreateOpen] = useState(false);
  const enmCustomerTypeOptions = useEnumValues('CustomerType');
  const enmAccountantMethodOptions = useEnumValues('AccountantMethod');

  const columns: GridColDef[] = [
    { field: 'id', headerName: 'ID', width: 80, type: 'number' },
    { field: 'customerCode', headerName: 'Customer Code', flex: 1, minWidth: 150 },
    { field: 'customerName', headerName: 'Customer Name', flex: 1, minWidth: 150 },
    { field: 'phone', headerName: 'Phone', flex: 1, minWidth: 150 },
    { field: 'email', headerName: 'Email', flex: 1, minWidth: 150 },
    { field: 'address', headerName: 'Address', flex: 1, minWidth: 150 },
    { field: 'city', headerName: 'City', flex: 1, minWidth: 150 },
    { field: 'taxId', headerName: 'Tax ID', flex: 1, minWidth: 150 },
    {
      field: 'enmCustomerType',
      headerName: 'Customer Type',
      width: 150,
      valueFormatter: (value) => {
        const opt = enmCustomerTypeOptions.find((o) => o.value === value);
        return opt ? opt.label : String(value ?? '');
      },
    },
    { field: 'paymentTermsDays', headerName: 'Payment Terms Days', width: 120 },
    { field: 'notes', headerName: 'Notes', flex: 1, minWidth: 150 },
    { field: 'isActive', headerName: 'Is Active', width: 100, type: 'boolean' },
    { field: 'location', headerName: 'Location', flex: 1, minWidth: 150 },
    { field: 'accountantEmail', headerName: 'Accountant Email', flex: 1, minWidth: 150 },
    {
      field: 'enmAccountantMethod',
      headerName: 'Accountant Method',
      width: 150,
      valueFormatter: (value) => {
        const opt = enmAccountantMethodOptions.find((o) => o.value === value);
        return opt ? opt.label : String(value ?? '');
      },
    },
    { field: 'invoiceName', headerName: 'Invoice Name', flex: 1, minWidth: 150 },
    { field: 'profitabilityCode', headerName: 'Profitability Code', flex: 1, minWidth: 150 },
    { field: 'customerIdentifier', headerName: 'Customer Identifier', flex: 1, minWidth: 150 },
    {
      field: 'actions',
      type: 'actions',
      headerName: 'Actions',
      width: 140,
      getActions: (params) => [
        <GridActionsCellItem
          key="view"
          icon={<ViewIcon />}
          label="View"
          onClick={() => navigate(`/customers/${params.id}`)}
        />,
        <GridActionsCellItem
          key="edit"
          icon={<EditIcon />}
          label="Edit"
          onClick={() => navigate(`/customers/${params.id}/edit`)}
        />,
        <GridActionsCellItem
          key="delete"
          icon={<DeleteIcon />}
          label="Delete"
          onClick={() => setDeleteId(params.id as number)}
        />,
      ],
    },
  ];

  if (isError) {
    return (
      <Box sx={{ p: 3 }}>
        <Alert severity="error" sx={{ mb: 2 }}>
          Failed to load customers: {(error as Error)?.message || 'Unknown error'}
        </Alert>
      </Box>
    );
  }

  const filterFields = [
    { field: 'customerCode', label: 'Customer Code', type: 'string' as const },
    { field: 'customerName', label: 'Customer Name', type: 'string' as const },
    { field: 'phone', label: 'Phone', type: 'string' as const },
    { field: 'email', label: 'Email', type: 'string' as const },
    { field: 'address', label: 'Address', type: 'string' as const },
    { field: 'city', label: 'City', type: 'string' as const },
    { field: 'taxId', label: 'Tax ID', type: 'string' as const },
    { field: 'enmCustomerType', label: 'Customer Type', type: 'string' as const },
    { field: 'paymentTermsDays', label: 'Payment Terms Days', type: 'number' as const },
    { field: 'notes', label: 'Notes', type: 'string' as const },
    { field: 'isActive', label: 'Is Active', type: 'boolean' as const },
    { field: 'location', label: 'Location', type: 'string' as const },
    { field: 'accountantEmail', label: 'Accountant Email', type: 'string' as const },
    { field: 'enmAccountantMethod', label: 'Accountant Method', type: 'string' as const },
    { field: 'invoiceName', label: 'Invoice Name', type: 'string' as const },
    { field: 'profitabilityCode', label: 'Profitability Code', type: 'string' as const },
    { field: 'customerIdentifier', label: 'Customer Identifier', type: 'string' as const },
  ];

  return (
    <Box sx={{ p: 3 }}>
      <Box display="flex" justifyContent="flex-end" mb={1}>
        <Button size="small" startIcon={<FilterListIcon />} onClick={() => setShowFilters((p) => !p)} color={Object.keys(activeFilters).length > 0 ? 'primary' : 'inherit'}>
          {showFilters ? he.actions.hideFilters : `${he.actions.filter}${Object.keys(activeFilters).length > 0 ? ` (${Object.keys(activeFilters).length})` : ''}`}
        </Button>
      </Box>
      <Collapse in={showFilters}>
        <FilterBuilder fields={filterFields} onApply={(f) => { setActiveFilters(f as Record<string, unknown>); setPaginationModel((p) => ({ ...p, page: 0 })); }} onClear={() => setActiveFilters({})} />
      </Collapse>
      <AppDataGrid
        entityName="customer"
        title="Customer List"
        rows={data?.items || []}
        columns={columns}
        loading={isLoading}
        getRowId={(row) => (row as any).id as string | number}
        rowCount={data?.total || 0}
        paginationModel={paginationModel}
        onPaginationModelChange={setPaginationModel}
        serverSearch={search}
        onServerSearchChange={setSearch}
        sortModel={sortModel}
        onSortModelChange={handleSortModelChange}
        onRowClick={(id) => navigate(`/customers/${id}`)}
        checkboxSelection
        onSelectionChange={(ids) => setSelectedIds(ids)}
        onContextMenuActions={(id, row) => [
          { label: he.actions.view, icon: <OpenInNewIcon fontSize="small" />, onClick: () => navigate(`/customers/${id}`) },
          { label: he.actions.copyId, icon: <ContentCopyIcon fontSize="small" />, onClick: () => { navigator.clipboard.writeText(String(id)); showSuccess(he.messages.idCopied); } },
          { label: he.actions.copyRow, icon: <ContentCopyIcon fontSize="small" />, onClick: () => { navigator.clipboard.writeText(JSON.stringify(row, null, 2)); showSuccess(he.messages.rowCopied); } },
          { label: he.actions.duplicate, icon: <ContentCopyIcon fontSize="small" />, onClick: () => navigate(`/customers/new?cloneFrom=${id}`), divider: true },
          { label: he.actions.edit, icon: <EditIcon fontSize="small" />, onClick: () => navigate(`/customers/${id}/edit`) },
          { label: he.actions.delete, icon: <DeleteIcon fontSize="small" />, onClick: () => setDeleteId(id as number), divider: true },
        ]}
        onCreateNew={() => navigate('/customers/new')}
        editable
        processRowUpdate={async (newRow, oldRow) => { await updateMutation.mutateAsync({ id: (newRow as any).id as number, data: newRow as unknown as UpdateCustomerRequest }); return newRow; }}
        onBulkEdit={async (ids, field, value) => {
          await Promise.all(ids.map((id) => updateMutation.mutateAsync({ id: id as number, data: { [field]: value } as unknown as UpdateCustomerRequest })));
        }}
        bulkEditableFields={[
          { field: 'customerCode', label: 'Customer Code', type: 'string' },
          { field: 'customerName', label: 'Customer Name', type: 'string' },
          { field: 'phone', label: 'Phone', type: 'string' },
          { field: 'email', label: 'Email', type: 'string' },
          { field: 'address', label: 'Address', type: 'string' },
          { field: 'city', label: 'City', type: 'string' },
          { field: 'taxId', label: 'Tax ID', type: 'string' },
          { field: 'enmCustomerType', label: 'Customer Type', type: 'select' },
          { field: 'paymentTermsDays', label: 'Payment Terms Days', type: 'number' },
          { field: 'notes', label: 'Notes', type: 'string' },
          { field: 'location', label: 'Location', type: 'string' },
          { field: 'accountantEmail', label: 'Accountant Email', type: 'string' },
          { field: 'enmAccountantMethod', label: 'Accountant Method', type: 'select' },
          { field: 'invoiceName', label: 'Invoice Name', type: 'string' },
          { field: 'profitabilityCode', label: 'Profitability Code', type: 'string' },
        ]}
        headerActions={
          <>
            <PermissionGate entity="customer" action="delete">
              {selectedIds.length > 0 && (
                <Button variant="outlined" color="error" onClick={() => setBulkDeleteConfirm(true)}>
                  {he.actions.bulkDelete} ({selectedIds.length})
                </Button>
              )}
            </PermissionGate>
            <PermissionGate entity="customer" action="write">
              <Button variant="contained" onClick={() => navigate('/customers/new')}>
                {he.actions.create}
              </Button>
              <Button variant="outlined" onClick={() => setQuickCreateOpen(true)}>
                {he.actions.quickCreate}
              </Button>
            </PermissionGate>
          </>
        }
      />
      <Dialog open={quickCreateOpen} onClose={() => setQuickCreateOpen(false)} maxWidth="md" fullWidth>
        <DialogTitle>Quick Create Customer</DialogTitle>
        <DialogContent>
          <CustomerForm embedded onSuccess={() => setQuickCreateOpen(false)} />
        </DialogContent>
      </Dialog>
      <ConfirmDialog
        open={deleteId !== null}
        title="Delete Customer"
        message="Are you sure you want to delete this customer? This action cannot be undone."
        confirmDisabled={deleteMutation.isPending}
        onConfirm={() => {
          if (deleteId !== null) {
            deleteMutation.mutate(deleteId);
          }
          setDeleteId(null);
        }}
        onCancel={() => setDeleteId(null)}
      />
      <ConfirmDialog
        open={bulkDeleteConfirm}
        title="Delete Multiple Customers"
        message={`Are you sure you want to delete ${selectedIds.length} customer(s)? This action cannot be undone.`}
        severity="error"
        onConfirm={async () => {
          try {
            await Promise.all(selectedIds.map((id) => deleteMutation.mutateAsync(id as number)));
          } catch { /* individual errors handled by mutation onError */ }
          setSelectedIds([]);
          setBulkDeleteConfirm(false);
        }}
        onCancel={() => setBulkDeleteConfirm(false)}
      />
    </Box>
  );
}

