// CustomerDebtView.tsx
// Generated by CodeCreator
import { useState, useCallback } from 'react';
import {
  Box,
  Paper,
  Typography,
  Button,
  Skeleton,
  Chip,
  IconButton,
  Tooltip,
  Snackbar,
} from '@mui/material';
import Grid from '@mui/material/Grid2';
import PrintIcon from '@mui/icons-material/Print';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import { PermissionGate } from '../contexts/AuthContext';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { useCustomerDebt } from '../hooks/useCustomerDebt';
import { useEnumValues } from '../hooks/useEnumValues';
import { Tabs, Tab } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { api } from '../api/client';

export default function CustomerDebtView() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const parsedId = id ? Number(id) : 0;
  const { data: entity, isLoading, isError } = useCustomerDebt(parsedId);
  const enmDebtStatusOptions = useEnumValues('DebtStatus');

  const [copiedField, setCopiedField] = useState('');
  const copyToClipboard = useCallback((value: unknown, fieldName: string) => {
    navigator.clipboard.writeText(String(value ?? '')).then(() => setCopiedField(fieldName));
  }, []);

  const [activeTab, setActiveTab] = useState(0);
  const { data: auditData } = useQuery({
    queryKey: ['audit', 'CustomerDebt', parsedId],
    queryFn: () => api.get(`/audit/CustomerDebt/${parsedId}`).then((r) => r.data as { items: unknown[]; total: number }),
    enabled: Boolean(parsedId) && activeTab === 1,
  });

  if (isLoading) {
    return (
      <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
        <Skeleton variant="text" width={250} height={40} sx={{ mb: 3 }} />
        <Paper sx={{ p: 3 }}>
          <Grid container spacing={2}>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
          </Grid>
        </Paper>
      </Box>
    );
  }

  if (isError || !entity) {
    return (
      <Box p={4}>
        <Typography color="error">Customer Debt not found.</Typography>
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
      <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h5">Customer Debt Details</Typography>
        <Box display="flex" gap={1}>
          <PermissionGate entity="customerDebt" action="write">
            <Button variant="contained" onClick={() => navigate(`/customerDebts/${entity.id}/edit`)}>
              Edit
            </Button>
          </PermissionGate>
          <PermissionGate entity="customerDebt" action="write">
            <Button variant="outlined" startIcon={<ContentCopyIcon />} onClick={() => navigate(`/customerDebts/new?cloneFrom=${entity.id}`)}>
              Clone
            </Button>
          </PermissionGate>
          <Button variant="outlined" onClick={() => navigate('/customerDebts')}>
            Back to List
          </Button>
          <Button variant="outlined" startIcon={<PrintIcon />} onClick={() => window.print()} className="no-print">
            Print
          </Button>
        </Box>
      </Box>
      <Paper sx={{ p: 3 }}>
        <Grid container spacing={2}>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                ID
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy ID" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.id, 'ID')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.id}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary" title="Customer">
                Customer ID
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Customer ID" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.fkCustomerId, 'Customer ID')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              <Link to={`/customers/${entity.fkCustomerId}`} style={{ color: 'inherit', textDecoration: 'underline' }}>
                {entity.fkCustomerId}
              </Link>
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary" title="Order Header">
                Order Header ID
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Order Header ID" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.fkOrderHeaderId, 'Order Header ID')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.fkOrderHeaderId ? (
                <Link to={`/orderHeaders/${entity.fkOrderHeaderId}`} style={{ color: 'inherit', textDecoration: 'underline' }}>
                  {entity.fkOrderHeaderId}
                </Link>
              ) : '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Debt Amount
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Debt Amount" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.debtAmount, 'Debt Amount')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.debtAmount}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Paid Amount
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Paid Amount" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.paidAmount, 'Paid Amount')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.paidAmount ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Remaining Amount
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Remaining Amount" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.remainingAmount, 'Remaining Amount')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.remainingAmount ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Debt Date
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Debt Date" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.debtDate, 'Debt Date')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {(() => { const v = entity.debtDate; if (!v || String(v) < '1900') return '-'; return new Date(v).toLocaleDateString(); })()}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Due Date
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Due Date" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.dueDate, 'Due Date')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {(() => { const v = entity.dueDate; if (!v || String(v) < '1900') return '-'; return new Date(v).toLocaleDateString(); })()}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Debt Status
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Debt Status" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.enmDebtStatus, 'Debt Status')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {enmDebtStatusOptions.find((o) => o.value === entity.enmDebtStatus)?.label || String(entity.enmDebtStatus)}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Notes
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Notes" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.notes, 'Notes')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.notes ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Needs Attention
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Needs Attention" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.needsAttention, 'Needs Attention')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Box>
              <Chip
                label={entity.needsAttention ? 'Yes' : 'No'}
                color={entity.needsAttention ? 'success' : 'default'}
                size="small"
              />
            </Box>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Product Types
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Product Types" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.productTypes, 'Product Types')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.productTypes ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Delivery Date
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Delivery Date" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.deliveryDate, 'Delivery Date')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {(() => { const v = entity.deliveryDate; if (!v || String(v) < '1900') return '-'; return new Date(v).toLocaleDateString(); })()}
            </Typography>
          </Grid>
        </Grid>
      </Paper>

      <Box sx={{ mt: 3 }}>
        <Tabs value={activeTab} onChange={(_, v) => setActiveTab(v)} sx={{ borderBottom: 1, borderColor: 'divider' }}>
          <Tab label="Details" />
          <Tab label="History" />
        </Tabs>

        {/* History tab — fetches from c_AuditIndexed */}
        {activeTab === 1 && (
          <Box sx={{ pt: 2 }}>
            {auditData?.items ? (
              <Box>
                {(auditData.items as { id: number; fieldName: string; oldValue: string; newValue: string; changedByUser: string; occurredAt: string; operation: string }[]).map((a) => (
                  <Paper key={a.id} variant="outlined" sx={{ p: 1.5, mb: 1, display: 'flex', gap: 2, alignItems: 'center' }}>
                    <Typography variant="caption" color="text.secondary" sx={{ minWidth: 140 }}>
                      {new Date(a.occurredAt).toLocaleString()}
                    </Typography>
                    <Typography variant="body2" sx={{ fontWeight: 600 }}>{a.changedByUser}</Typography>
                    <Typography variant="body2">
                      {a.operation === 'Added' ? 'Created record' : `Changed ${a.fieldName}`}
                      {a.oldValue && a.newValue ? ` from "${a.oldValue}" to "${a.newValue}"` : a.newValue ? `: "${a.newValue}"` : ''}
                    </Typography>
                  </Paper>
                ))}
                {auditData.items.length === 0 && <Typography color="text.secondary">No history available</Typography>}
              </Box>
            ) : <Typography>Loading history...</Typography>}
          </Box>
        )}
      </Box>
      <Snackbar
        open={Boolean(copiedField)}
        autoHideDuration={2000}
        onClose={() => setCopiedField('')}
        message={`${copiedField} copied to clipboard`}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      />
    </Box>
  );
}

