// CustomerForm.tsx
// Generated by CodeCreator
import { useEffect, useState, useCallback } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  TextField,
  Button,
  Box,
  Paper,
  Typography,
  FormControlLabel,
  Checkbox,
  CircularProgress,
  MenuItem,
  Divider,
  Autocomplete,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Alert,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Snackbar,
} from '@mui/material';
import { ExpandMore as ExpandMoreIcon } from '@mui/icons-material';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useCustomer, useCreateCustomer, useUpdateCustomer } from '../hooks/useCustomer';
import { fieldLabel } from '../i18n/fieldLabels';
import he from '../i18n/he';
import { customerSchema, type CustomerFormData } from '../types/Customer';
import { PermissionGate } from '../contexts/AuthContext';
import { useEnumValues } from '../hooks/useEnumValues';

interface CustomerFormProps {
  embedded?: boolean;
  onSuccess?: () => void;
}

export default function CustomerForm({ embedded, onSuccess }: CustomerFormProps = {}) {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const isEditMode = !embedded && Boolean(id);
  const [searchParams] = useSearchParams();
  const cloneFromId = searchParams.get('cloneFrom');

  const enmCustomerTypeOptions = useEnumValues('CustomerType');
  const enmAccountantMethodOptions = useEnumValues('AccountantMethod');

  const parsedId = id ? Number(id) : 0;
  const { data: existingData, isLoading: isLoadingData } = useCustomer(parsedId);
  const cloneParsedId = cloneFromId ? Number(cloneFromId) : 0;
  const { data: cloneSourceData } = useCustomer(cloneParsedId);
  const createMutation = useCreateCustomer();
  const updateMutation = useUpdateCustomer();

  const {
    control,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting, isDirty },
  } = useForm<CustomerFormData>({
    resolver: zodResolver(customerSchema),
  });

  useEffect(() => {
    if (isEditMode && existingData) {
      reset({
        customerCode: existingData.customerCode,
        customerName: existingData.customerName,
        phone: existingData.phone ?? '',
        email: existingData.email ?? '',
        address: existingData.address ?? '',
        city: existingData.city ?? '',
        taxId: existingData.taxId ?? '',
        enmCustomerType: existingData.enmCustomerType ?? 0,
        paymentTermsDays: existingData.paymentTermsDays ?? 0,
        notes: existingData.notes ?? '',
        location: existingData.location ?? '',
        accountantEmail: existingData.accountantEmail ?? '',
        enmAccountantMethod: existingData.enmAccountantMethod ?? 0,
        invoiceName: existingData.invoiceName ?? '',
        profitabilityCode: existingData.profitabilityCode ?? '',
      });
    }
  }, [isEditMode, existingData, reset]);

  useEffect(() => {
    if (!isEditMode && cloneFromId && cloneSourceData) {
      reset({
        customerCode: '',  // Unique - must change before saving
        customerName: cloneSourceData.customerName,
        phone: cloneSourceData.phone ?? '',
        email: cloneSourceData.email ?? '',
        address: cloneSourceData.address ?? '',
        city: cloneSourceData.city ?? '',
        taxId: cloneSourceData.taxId ?? '',
        enmCustomerType: cloneSourceData.enmCustomerType ?? 0,
        paymentTermsDays: cloneSourceData.paymentTermsDays ?? 0,
        notes: cloneSourceData.notes ?? '',
        location: cloneSourceData.location ?? '',
        accountantEmail: cloneSourceData.accountantEmail ?? '',
        enmAccountantMethod: cloneSourceData.enmAccountantMethod ?? 0,
        invoiceName: cloneSourceData.invoiceName ?? '',
        profitabilityCode: cloneSourceData.profitabilityCode ?? '',
      });
    }
  }, [cloneFromId, cloneSourceData, isEditMode, reset]);

  const [conflictData, setConflictData] = useState<Record<string,unknown> | null>(null);

  const onSubmit = async (formData: CustomerFormData) => {
    try {
      if (isEditMode) {
        const payload = { ...formData, _etag: (existingData as unknown as Record<string,unknown>)?._etag } as Record<string,unknown>;
        await updateMutation.mutateAsync({ id: parsedId, data: payload as unknown as CustomerFormData });
      } else {
        await createMutation.mutateAsync(formData);
      }
      localStorage.removeItem(draftKey); // Clear draft on successful save
      if (embedded && onSuccess) {
        onSuccess();
      } else {
        navigate('/customers');
      }
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'name' in error && (error as Error).name === 'ConflictError') {
        setConflictData({ message: (error as Error).message });
        return;
      }
      const axiosErr = error as { response?: { status?: number; data?: Record<string,unknown> } };
      if (axiosErr.response?.status === 409) {
        setConflictData(axiosErr.response.data as Record<string,unknown>);
      } else {
        console.error('Failed to save customer:', error);
      }
    }
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && (e.key === 'Enter' || e.key === 's')) {
        e.preventDefault();
        handleSubmit(onSubmit)();
      }
      if (e.key === 'Escape') {
        navigate('/customers');
      }
    };
  
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }); // re-registers on every render to capture latest form state

  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isDirty && !isSubmitting) {
        e.preventDefault();
      }
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [isDirty, isSubmitting]);

  // Auto-save draft to localStorage every 30 seconds
  const draftKey = `draft_customer_${isEditMode ? id : 'new'}`;
  const [hasDraft, setHasDraft] = useState(false);
  const [draftRestored, setDraftRestored] = useState(false);
  useEffect(() => {
    if (draftRestored) return;
    const saved = localStorage.getItem(draftKey);
    if (saved) setHasDraft(true);
  }, [draftKey, draftRestored]);
  useEffect(() => {
    if (!isDirty) return;
    const timer = setInterval(() => {
      const formValues = control._formValues;
      if (formValues) localStorage.setItem(draftKey, JSON.stringify(formValues));
    }, 30000);
    return () => clearInterval(timer);
  }, [isDirty, draftKey, control]);
  const restoreDraft = useCallback(() => {
    const saved = localStorage.getItem(draftKey);
    if (saved) { try { reset(JSON.parse(saved)); } catch {} }
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey, reset]);
  const discardDraft = useCallback(() => {
    localStorage.removeItem(draftKey);
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey]);

  // Warn on browser close/refresh when form is dirty
  useEffect(() => {
    const handler = (e: BeforeUnloadEvent) => { if (isDirty && !isSubmitting) { e.preventDefault(); } };
    window.addEventListener('beforeunload', handler);
    return () => window.removeEventListener('beforeunload', handler);
  }, [isDirty, isSubmitting]);

  if ((isEditMode && isLoadingData) || (cloneFromId && !cloneSourceData)) {
    return (
      <Box display="flex" justifyContent="center" p={4}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <PermissionGate entity="customer" action="write">
    <Box sx={{ p: embedded ? 1 : 3, maxWidth: embedded ? '100%' : 800, mx: 'auto' }}>
      {/* Auto-save draft banner */}
      {hasDraft && !draftRestored && (
        <Alert severity="info" sx={{ mb: 2 }} action={
          <Box>
            <Button size="small" onClick={restoreDraft}>Restore</Button>
            <Button size="small" color="inherit" onClick={discardDraft}>Discard</Button>
          </Box>
        }>Unsaved draft found. Restore or discard?</Alert>
      )}
      {/* Navigation guard handled by beforeunload event */}
      {/* Concurrency conflict dialog */}
      <Dialog open={Boolean(conflictData)} onClose={() => setConflictData(null)} maxWidth="sm" fullWidth>
        <DialogTitle color="error">Conflict — Record Modified</DialogTitle>
        <DialogContent>
          <DialogContentText>
            <>{(conflictData as Record<string,unknown>)?.message ?? 'This record was modified by another user since you loaded it.'}{' '}Your changes were not saved. Please refresh and try again.</>
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setConflictData(null); window.location.reload(); }} variant="contained">Refresh &amp; Retry</Button>
        </DialogActions>
      </Dialog>
      {!embedded && (
        <Typography variant="h5" mb={3}>
          {isEditMode ? `${he.grid.editOf} ${he.entities.customer.s}` : cloneFromId ? `${he.grid.cloneOf} ${he.entities.customer.s}` : `${he.grid.addOf} ${he.entities.customer.s}`}
        </Typography>
      )}
      {cloneFromId && (
        <Alert severity="warning" sx={{ mb: 2 }}>
          Cloning record — the following unique fields were cleared and <strong>must be filled with new values</strong> before saving:
          <br />• Customer Code
        </Alert>
      )}
      <Paper sx={{ p: 3, elevation: embedded ? 0 : undefined }}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Box display="flex" flexDirection="column" gap={2}>
            <Controller
              name="customerCode"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('customerCode') ?? "Customer Code"}
                  type="text"
                  fullWidth
                  autoFocus
                  required
                  error={Boolean(errors.customerCode)}
                  helperText={errors.customerCode?.message}
                />
              )}
            />
            <Controller
              name="customerName"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('customerName') ?? "Customer Name"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  required
                  error={Boolean(errors.customerName)}
                  helperText={errors.customerName?.message}
                />
              )}
            />
            <Controller
              name="phone"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('phone') ?? "Phone"}
                  type="text"
                  fullWidth
                  error={Boolean(errors.phone)}
                  helperText={errors.phone?.message}
                />
              )}
            />
            <Controller
              name="email"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('email') ?? "Email"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.email)}
                  helperText={errors.email?.message}
                />
              )}
            />
            <Controller
              name="address"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('address') ?? "Address"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.address)}
                  helperText={errors.address?.message}
                />
              )}
            />
            <Controller
              name="city"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('city') ?? "City"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.city)}
                  helperText={errors.city?.message}
                />
              )}
            />
            <Controller
              name="taxId"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('taxId') ?? "Tax ID"}
                  type="text"
                  fullWidth
                  error={Boolean(errors.taxId)}
                  helperText={errors.taxId?.message}
                />
              )}
            />
            <Controller
              name="enmCustomerType"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('enmCustomerType') ?? "Customer Type"}
                  select
                  fullWidth
                  error={Boolean(errors.enmCustomerType)}
                  helperText={errors.enmCustomerType?.message}
                >
                  {enmCustomerTypeOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="paymentTermsDays"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('paymentTermsDays') ?? "Payment Terms Days"}
                  type="number"
                  fullWidth
                  error={Boolean(errors.paymentTermsDays)}
                  helperText={errors.paymentTermsDays?.message}
                />
              )}
            />
            <Controller
              name="notes"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('notes') ?? "Notes"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.notes)}
                  helperText={errors.notes?.message}
                />
              )}
            />
            <Controller
              name="location"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('location') ?? "Location"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.location)}
                  helperText={errors.location?.message}
                />
              )}
            />
            <Controller
              name="accountantEmail"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('accountantEmail') ?? "Accountant Email"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.accountantEmail)}
                  helperText={errors.accountantEmail?.message}
                />
              )}
            />
            <Controller
              name="enmAccountantMethod"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('enmAccountantMethod') ?? "Accountant Method"}
                  select
                  fullWidth
                  error={Boolean(errors.enmAccountantMethod)}
                  helperText={errors.enmAccountantMethod?.message}
                >
                  {enmAccountantMethodOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="invoiceName"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('invoiceName') ?? "Invoice Name"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.invoiceName)}
                  helperText={errors.invoiceName?.message}
                />
              )}
            />
            <Controller
              name="profitabilityCode"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('profitabilityCode') ?? "Profitability Code"}
                  type="text"
                  fullWidth
                  error={Boolean(errors.profitabilityCode)}
                  helperText={errors.profitabilityCode?.message}
                />
              )}
            />
            {isEditMode && existingData && (
              <>
                <Divider sx={{ my: 1 }} />
                <Typography variant="subtitle2" color="text.secondary">
                  {he.grid.computedFields}
                </Typography>
                <TextField
                  label={fieldLabel('profitabilityCode') ?? "Is Active"}
                  value={existingData.isActive ? 'Yes' : 'No'}
                  disabled
                  fullWidth
                />
                <TextField
                  label={fieldLabel('profitabilityCode') ?? "Customer Identifier"}
                  value={existingData.customerIdentifier ?? ''}
                  disabled
                  fullWidth
                />
              </>
            )}
            <Box display="flex" gap={2} mt={2}>
              <Button type="submit" variant="contained" disabled={isSubmitting}>
                {isSubmitting ? he.actions.saving : (isEditMode ? he.actions.save : he.actions.create)}
              </Button>
              {!embedded && (
                <Button variant="outlined" onClick={() => navigate('/customers')}>
                  {he.actions.cancel}
                </Button>
              )}
            </Box>
          </Box>
        </form>
      </Paper>
    </Box>
    </PermissionGate>
  );
}

