// CustomerView.tsx
// Generated by CodeCreator
import { useState, useCallback } from 'react';
import {
  Box,
  Paper,
  Typography,
  Button,
  Skeleton,
  Chip,
  IconButton,
  Tooltip,
  Snackbar,
} from '@mui/material';
import Grid from '@mui/material/Grid2';
import PrintIcon from '@mui/icons-material/Print';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import { PermissionGate } from '../contexts/AuthContext';
import { useNavigate, useParams } from 'react-router-dom';
import { useCustomer } from '../hooks/useCustomer';
import { useEnumValues } from '../hooks/useEnumValues';
import { Tabs, Tab } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import AppDataGrid from '../components/shared/AppDataGrid';
import { type GridColDef } from '@mui/x-data-grid';
import { BeehiveBuyerTrackingApi } from '../api/BeehiveBuyerTrackingApi';
import { CustomerDebtApi } from '../api/CustomerDebtApi';
import { OrderHeaderApi } from '../api/OrderHeaderApi';
import { api } from '../api/client';

export default function CustomerView() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const parsedId = id ? Number(id) : 0;
  const { data: entity, isLoading, isError } = useCustomer(parsedId);
  const enmCustomerTypeOptions = useEnumValues('CustomerType');
  const enmAccountantMethodOptions = useEnumValues('AccountantMethod');

  const [copiedField, setCopiedField] = useState('');
  const copyToClipboard = useCallback((value: unknown, fieldName: string) => {
    navigator.clipboard.writeText(String(value ?? '')).then(() => setCopiedField(fieldName));
  }, []);

  const [activeTab, setActiveTab] = useState(0);
  const { data: beehiveBuyerTrackingData } = useQuery({
    queryKey: ['beehiveBuyerTrackings', 'by-parent', parsedId],
    queryFn: () => BeehiveBuyerTrackingApi.getAll(0, 100, '', '', 'asc', { customerId: parsedId }),
    enabled: Boolean(parsedId) && activeTab > 0,
  });
  const { data: customerDebtData } = useQuery({
    queryKey: ['customerDebts', 'by-parent', parsedId],
    queryFn: () => CustomerDebtApi.getAll(0, 100, '', '', 'asc', { customerId: parsedId }),
    enabled: Boolean(parsedId) && activeTab > 0,
  });
  const { data: orderHeaderData } = useQuery({
    queryKey: ['orderHeaders', 'by-parent', parsedId],
    queryFn: () => OrderHeaderApi.getAll(0, 100, '', '', 'asc', { customerId: parsedId }),
    enabled: Boolean(parsedId) && activeTab > 0,
  });
  const { data: auditData } = useQuery({
    queryKey: ['audit', 'Customer', parsedId],
    queryFn: () => api.get(`/audit/Customer/${parsedId}`).then((r) => r.data as { items: unknown[]; total: number }),
    enabled: Boolean(parsedId) && activeTab === 4,
  });

  if (isLoading) {
    return (
      <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
        <Skeleton variant="text" width={250} height={40} sx={{ mb: 3 }} />
        <Paper sx={{ p: 3 }}>
          <Grid container spacing={2}>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
          </Grid>
        </Paper>
      </Box>
    );
  }

  if (isError || !entity) {
    return (
      <Box p={4}>
        <Typography color="error">Customer not found.</Typography>
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
      <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h5">Customer Details</Typography>
        <Box display="flex" gap={1}>
          <PermissionGate entity="customer" action="write">
            <Button variant="contained" onClick={() => navigate(`/customers/${entity.id}/edit`)}>
              Edit
            </Button>
          </PermissionGate>
          <PermissionGate entity="customer" action="write">
            <Button variant="outlined" startIcon={<ContentCopyIcon />} onClick={() => navigate(`/customers/new?cloneFrom=${entity.id}`)}>
              Clone
            </Button>
          </PermissionGate>
          <Button variant="outlined" onClick={() => navigate('/customers')}>
            Back to List
          </Button>
          <Button variant="outlined" startIcon={<PrintIcon />} onClick={() => window.print()} className="no-print">
            Print
          </Button>
        </Box>
      </Box>
      <Paper sx={{ p: 3 }}>
        <Grid container spacing={2}>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                ID
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy ID" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.id, 'ID')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.id}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Customer Code
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Customer Code" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.customerCode, 'Customer Code')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.customerCode}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Customer Name
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Customer Name" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.customerName, 'Customer Name')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.customerName}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Phone
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Phone" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.phone, 'Phone')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.phone ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Email
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Email" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.email, 'Email')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.email ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Address
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Address" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.address, 'Address')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.address ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                City
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy City" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.city, 'City')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.city ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Tax ID
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Tax ID" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.taxId, 'Tax ID')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.taxId ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Customer Type
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Customer Type" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.enmCustomerType, 'Customer Type')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {enmCustomerTypeOptions.find((o) => o.value === entity.enmCustomerType)?.label || String(entity.enmCustomerType)}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Payment Terms Days
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Payment Terms Days" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.paymentTermsDays, 'Payment Terms Days')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.paymentTermsDays ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Notes
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Notes" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.notes, 'Notes')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.notes ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Is Active
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Is Active" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.isActive, 'Is Active')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Box>
              <Chip
                label={entity.isActive ? 'Yes' : 'No'}
                color={entity.isActive ? 'success' : 'default'}
                size="small"
              />
            </Box>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Location
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Location" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.location, 'Location')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.location ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Accountant Email
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Accountant Email" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.accountantEmail, 'Accountant Email')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.accountantEmail ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Accountant Method
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Accountant Method" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.enmAccountantMethod, 'Accountant Method')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {enmAccountantMethodOptions.find((o) => o.value === entity.enmAccountantMethod)?.label || String(entity.enmAccountantMethod)}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Invoice Name
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Invoice Name" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.invoiceName, 'Invoice Name')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.invoiceName ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Profitability Code
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Profitability Code" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.profitabilityCode, 'Profitability Code')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.profitabilityCode ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Customer Identifier
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Customer Identifier" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.customerIdentifier, 'Customer Identifier')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.customerIdentifier ?? '-'}
            </Typography>
          </Grid>
        </Grid>
      </Paper>

      <Box sx={{ mt: 3 }}>
        <Tabs value={activeTab} onChange={(_, v) => setActiveTab(v)} sx={{ borderBottom: 1, borderColor: 'divider' }}>
          <Tab label="Details" />
          <Tab label="Beehive Buyer Trackings" />
          <Tab label="Customer Debts" />
          <Tab label="Order Headers" />
          <Tab label="History" />
        </Tabs>
        {activeTab === 1 && (
          <Box sx={{ pt: 2 }}>
            <AppDataGrid
              title="Beehive Buyer Trackings"
              rows={beehiveBuyerTrackingData?.items || []}
              columns={[
                { field: 'id', headerName: 'ID', width: 80 },
                { field: 'fkCustomerId', headerName: 'Customer ID', flex: 1, minWidth: 120 },
                { field: 'lastOrderDate', headerName: 'Last Order Date', flex: 1, minWidth: 120 },
                { field: 'beehiveQuantity', headerName: 'Beehive Quantity', flex: 1, minWidth: 120 },
                { field: 'reminderMonth', headerName: 'Reminder Month', flex: 1, minWidth: 120 },
                { field: 'isRelevant', headerName: 'Is Relevant', width: 100, type: 'boolean' },
              ] as GridColDef[]}
              loading={false}
              getRowId={(row) => (row as any).id as string | number}
              onRowClick={(childId) => navigate(`/beehiveBuyerTrackings/${childId}`)}
            />
          </Box>
        )}
        {activeTab === 2 && (
          <Box sx={{ pt: 2 }}>
            <AppDataGrid
              title="Customer Debts"
              rows={customerDebtData?.items || []}
              columns={[
                { field: 'id', headerName: 'ID', width: 80 },
                { field: 'fkCustomerId', headerName: 'Customer ID', flex: 1, minWidth: 120 },
                { field: 'fkOrderHeaderId', headerName: 'Order Header ID', flex: 1, minWidth: 120 },
                { field: 'debtAmount', headerName: 'Debt Amount', flex: 1, minWidth: 120 },
                { field: 'paidAmount', headerName: 'Paid Amount', flex: 1, minWidth: 120 },
                { field: 'remainingAmount', headerName: 'Remaining Amount', flex: 1, minWidth: 120 },
              ] as GridColDef[]}
              loading={false}
              getRowId={(row) => (row as any).id as string | number}
              onRowClick={(childId) => navigate(`/customerDebts/${childId}`)}
            />
          </Box>
        )}
        {activeTab === 3 && (
          <Box sx={{ pt: 2 }}>
            <AppDataGrid
              title="Order Headers"
              rows={orderHeaderData?.items || []}
              columns={[
                { field: 'id', headerName: 'ID', width: 80 },
                { field: 'orderNumber', headerName: 'Order Number', flex: 1, minWidth: 120 },
                { field: 'fkCustomerId', headerName: 'Customer ID', flex: 1, minWidth: 120 },
                { field: 'orderDate', headerName: 'Order Date', flex: 1, minWidth: 120 },
                { field: 'totalAmount', headerName: 'Total Amount', flex: 1, minWidth: 120 },
                { field: 'vatAmount', headerName: 'VATAmount', flex: 1, minWidth: 120 },
              ] as GridColDef[]}
              loading={false}
              getRowId={(row) => (row as any).id as string | number}
              onRowClick={(childId) => navigate(`/orderHeaders/${childId}`)}
            />
          </Box>
        )}

        {/* History tab — fetches from c_AuditIndexed */}
        {activeTab === 4 && (
          <Box sx={{ pt: 2 }}>
            {auditData?.items ? (
              <Box>
                {(auditData.items as { id: number; fieldName: string; oldValue: string; newValue: string; changedByUser: string; occurredAt: string; operation: string }[]).map((a) => (
                  <Paper key={a.id} variant="outlined" sx={{ p: 1.5, mb: 1, display: 'flex', gap: 2, alignItems: 'center' }}>
                    <Typography variant="caption" color="text.secondary" sx={{ minWidth: 140 }}>
                      {new Date(a.occurredAt).toLocaleString()}
                    </Typography>
                    <Typography variant="body2" sx={{ fontWeight: 600 }}>{a.changedByUser}</Typography>
                    <Typography variant="body2">
                      {a.operation === 'Added' ? 'Created record' : `Changed ${a.fieldName}`}
                      {a.oldValue && a.newValue ? ` from "${a.oldValue}" to "${a.newValue}"` : a.newValue ? `: "${a.newValue}"` : ''}
                    </Typography>
                  </Paper>
                ))}
                {auditData.items.length === 0 && <Typography color="text.secondary">No history available</Typography>}
              </Box>
            ) : <Typography>Loading history...</Typography>}
          </Box>
        )}
      </Box>
      <Snackbar
        open={Boolean(copiedField)}
        autoHideDuration={2000}
        onClose={() => setCopiedField('')}
        message={`${copiedField} copied to clipboard`}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      />
    </Box>
  );
}

