// DeliveryForm.tsx
// Generated by CodeCreator
import { useEffect, useState, useCallback } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  TextField,
  Button,
  Box,
  Paper,
  Typography,
  FormControlLabel,
  Checkbox,
  CircularProgress,
  MenuItem,
  Divider,
  Autocomplete,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Alert,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Snackbar,
} from '@mui/material';
import { ExpandMore as ExpandMoreIcon } from '@mui/icons-material';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useDelivery, useCreateDelivery, useUpdateDelivery } from '../hooks/useDelivery';
import { fieldLabel } from '../i18n/fieldLabels';
import he from '../i18n/he';
import { deliverySchema, type DeliveryFormData } from '../types/Delivery';
import { PermissionGate } from '../contexts/AuthContext';
import { useEnumValues } from '../hooks/useEnumValues';
import { useQuery } from '@tanstack/react-query';
import { OrderHeaderApi } from '../api/OrderHeaderApi';

interface DeliveryFormProps {
  embedded?: boolean;
  onSuccess?: () => void;
}

export default function DeliveryForm({ embedded, onSuccess }: DeliveryFormProps = {}) {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const isEditMode = !embedded && Boolean(id);
  const [searchParams] = useSearchParams();
  const cloneFromId = searchParams.get('cloneFrom');

  const enmDeliveryMethodOptions = useEnumValues('DeliveryMethod');
  const enmDeliveryStatusOptions = useEnumValues('DeliveryStatus');

  const { data: orderHeaderData } = useQuery({
    queryKey: ['orderHeaders', 'all'],
    queryFn: () => OrderHeaderApi.getAll(0, 9999, ''),
    staleTime: 5 * 60 * 1000,
  });

  const parsedId = id ? Number(id) : 0;
  const { data: existingData, isLoading: isLoadingData } = useDelivery(parsedId);
  const cloneParsedId = cloneFromId ? Number(cloneFromId) : 0;
  const { data: cloneSourceData } = useDelivery(cloneParsedId);
  const createMutation = useCreateDelivery();
  const updateMutation = useUpdateDelivery();

  const {
    control,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting, isDirty },
  } = useForm<DeliveryFormData>({
    resolver: zodResolver(deliverySchema),
  });

  useEffect(() => {
    if (isEditMode && existingData) {
      reset({
        fkOrderHeaderId: existingData.fkOrderHeaderId,
        deliveryAddress: existingData.deliveryAddress ?? '',
        contactPhone: existingData.contactPhone ?? '',
        contactName: existingData.contactName ?? '',
        enmDeliveryMethod: existingData.enmDeliveryMethod ?? 0,
        orderedDate: existingData.orderedDate ?? '',
        receivedDate: existingData.receivedDate ?? '',
        arrivalToHubDate: existingData.arrivalToHubDate ?? '',
        arrivalToCustomerDate: existingData.arrivalToCustomerDate ?? '',
        enmDeliveryStatus: existingData.enmDeliveryStatus,
        location: existingData.location ?? '',
        notes: existingData.notes ?? '',
      });
    }
  }, [isEditMode, existingData, reset]);

  useEffect(() => {
    if (!isEditMode && cloneFromId && cloneSourceData) {
      reset({
        fkOrderHeaderId: cloneSourceData.fkOrderHeaderId,
        deliveryAddress: cloneSourceData.deliveryAddress ?? '',
        contactPhone: cloneSourceData.contactPhone ?? '',
        contactName: cloneSourceData.contactName ?? '',
        enmDeliveryMethod: cloneSourceData.enmDeliveryMethod ?? 0,
        orderedDate: cloneSourceData.orderedDate ?? '',
        receivedDate: cloneSourceData.receivedDate ?? '',
        arrivalToHubDate: cloneSourceData.arrivalToHubDate ?? '',
        arrivalToCustomerDate: cloneSourceData.arrivalToCustomerDate ?? '',
        enmDeliveryStatus: cloneSourceData.enmDeliveryStatus,
        location: cloneSourceData.location ?? '',
        notes: cloneSourceData.notes ?? '',
      });
    }
  }, [cloneFromId, cloneSourceData, isEditMode, reset]);

  const [conflictData, setConflictData] = useState<Record<string,unknown> | null>(null);

  const onSubmit = async (formData: DeliveryFormData) => {
    try {
      if (isEditMode) {
        const payload = { ...formData, _etag: (existingData as unknown as Record<string,unknown>)?._etag } as Record<string,unknown>;
        await updateMutation.mutateAsync({ id: parsedId, data: payload as unknown as DeliveryFormData });
      } else {
        await createMutation.mutateAsync(formData);
      }
      localStorage.removeItem(draftKey); // Clear draft on successful save
      if (embedded && onSuccess) {
        onSuccess();
      } else {
        navigate('/deliveries');
      }
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'name' in error && (error as Error).name === 'ConflictError') {
        setConflictData({ message: (error as Error).message });
        return;
      }
      const axiosErr = error as { response?: { status?: number; data?: Record<string,unknown> } };
      if (axiosErr.response?.status === 409) {
        setConflictData(axiosErr.response.data as Record<string,unknown>);
      } else {
        console.error('Failed to save delivery:', error);
      }
    }
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && (e.key === 'Enter' || e.key === 's')) {
        e.preventDefault();
        handleSubmit(onSubmit)();
      }
      if (e.key === 'Escape') {
        navigate('/deliveries');
      }
    };
  
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }); // re-registers on every render to capture latest form state

  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isDirty && !isSubmitting) {
        e.preventDefault();
      }
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [isDirty, isSubmitting]);

  // Auto-save draft to localStorage every 30 seconds
  const draftKey = `draft_delivery_${isEditMode ? id : 'new'}`;
  const [hasDraft, setHasDraft] = useState(false);
  const [draftRestored, setDraftRestored] = useState(false);
  useEffect(() => {
    if (draftRestored) return;
    const saved = localStorage.getItem(draftKey);
    if (saved) setHasDraft(true);
  }, [draftKey, draftRestored]);
  useEffect(() => {
    if (!isDirty) return;
    const timer = setInterval(() => {
      const formValues = control._formValues;
      if (formValues) localStorage.setItem(draftKey, JSON.stringify(formValues));
    }, 30000);
    return () => clearInterval(timer);
  }, [isDirty, draftKey, control]);
  const restoreDraft = useCallback(() => {
    const saved = localStorage.getItem(draftKey);
    if (saved) { try { reset(JSON.parse(saved)); } catch {} }
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey, reset]);
  const discardDraft = useCallback(() => {
    localStorage.removeItem(draftKey);
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey]);

  // Warn on browser close/refresh when form is dirty
  useEffect(() => {
    const handler = (e: BeforeUnloadEvent) => { if (isDirty && !isSubmitting) { e.preventDefault(); } };
    window.addEventListener('beforeunload', handler);
    return () => window.removeEventListener('beforeunload', handler);
  }, [isDirty, isSubmitting]);

  if ((isEditMode && isLoadingData) || (cloneFromId && !cloneSourceData)) {
    return (
      <Box display="flex" justifyContent="center" p={4}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <PermissionGate entity="delivery" action="write">
    <Box sx={{ p: embedded ? 1 : 3, maxWidth: embedded ? '100%' : 800, mx: 'auto' }}>
      {/* Auto-save draft banner */}
      {hasDraft && !draftRestored && (
        <Alert severity="info" sx={{ mb: 2 }} action={
          <Box>
            <Button size="small" onClick={restoreDraft}>Restore</Button>
            <Button size="small" color="inherit" onClick={discardDraft}>Discard</Button>
          </Box>
        }>Unsaved draft found. Restore or discard?</Alert>
      )}
      {/* Navigation guard handled by beforeunload event */}
      {/* Concurrency conflict dialog */}
      <Dialog open={Boolean(conflictData)} onClose={() => setConflictData(null)} maxWidth="sm" fullWidth>
        <DialogTitle color="error">Conflict — Record Modified</DialogTitle>
        <DialogContent>
          <DialogContentText>
            <>{(conflictData as Record<string,unknown>)?.message ?? 'This record was modified by another user since you loaded it.'}{' '}Your changes were not saved. Please refresh and try again.</>
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setConflictData(null); window.location.reload(); }} variant="contained">Refresh &amp; Retry</Button>
        </DialogActions>
      </Dialog>
      {!embedded && (
        <Typography variant="h5" mb={3}>
          {isEditMode ? `${he.grid.editOf} ${he.entities.delivery.s}` : cloneFromId ? `${he.grid.cloneOf} ${he.entities.delivery.s}` : `${he.grid.addOf} ${he.entities.delivery.s}`}
        </Typography>
      )}
      <Paper sx={{ p: 3, elevation: embedded ? 0 : undefined }}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Box display="flex" flexDirection="column" gap={2}>
            <Controller
              name="fkOrderHeaderId"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <Autocomplete
                  options={orderHeaderData?.items || []}
                  getOptionLabel={(option) => `${(option as any).id} - ${(option as any).invoiceNumber || ''}`}
                  value={(orderHeaderData?.items || []).find((i: any) => i.id === field.value) || null}
                  onChange={(_, newValue) => field.onChange(newValue ? (newValue as any).id : 0)}
                  isOptionEqualToValue={(option, value) => (option as any).id === (value as any)?.id}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label={fieldLabel('fkOrderHeaderId') ?? "Order Header ID"}
                      title="Order Header"
                      autoFocus
                      required
                      error={Boolean(errors.fkOrderHeaderId)}
                      helperText={errors.fkOrderHeaderId?.message}
                    />
                  )}
                />
              )}
            />
            <Controller
              name="deliveryAddress"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('deliveryAddress') ?? "Delivery Address"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.deliveryAddress)}
                  helperText={errors.deliveryAddress?.message}
                />
              )}
            />
            <Controller
              name="contactPhone"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('contactPhone') ?? "Contact Phone"}
                  type="text"
                  fullWidth
                  error={Boolean(errors.contactPhone)}
                  helperText={errors.contactPhone?.message}
                />
              )}
            />
            <Controller
              name="contactName"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('contactName') ?? "Contact Name"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.contactName)}
                  helperText={errors.contactName?.message}
                />
              )}
            />
            <Controller
              name="enmDeliveryMethod"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('enmDeliveryMethod') ?? "Delivery Method"}
                  select
                  fullWidth
                  error={Boolean(errors.enmDeliveryMethod)}
                  helperText={errors.enmDeliveryMethod?.message}
                >
                  {enmDeliveryMethodOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="orderedDate"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 10); })()}
                  label={fieldLabel('orderedDate') ?? "Ordered Date"}
                  type="date"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  error={Boolean(errors.orderedDate)}
                  helperText={errors.orderedDate?.message}
                />
              )}
            />
            <Controller
              name="receivedDate"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 10); })()}
                  label={fieldLabel('receivedDate') ?? "Received Date"}
                  type="date"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  error={Boolean(errors.receivedDate)}
                  helperText={errors.receivedDate?.message}
                />
              )}
            />
            <Controller
              name="arrivalToHubDate"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 10); })()}
                  label={fieldLabel('arrivalToHubDate') ?? "Arrival To Hub Date"}
                  type="date"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  error={Boolean(errors.arrivalToHubDate)}
                  helperText={errors.arrivalToHubDate?.message}
                />
              )}
            />
            <Controller
              name="arrivalToCustomerDate"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 10); })()}
                  label={fieldLabel('arrivalToCustomerDate') ?? "Arrival To Customer Date"}
                  type="date"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  error={Boolean(errors.arrivalToCustomerDate)}
                  helperText={errors.arrivalToCustomerDate?.message}
                />
              )}
            />
            <Controller
              name="enmDeliveryStatus"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('enmDeliveryStatus') ?? "Delivery Status"}
                  select
                  fullWidth
                  required
                  error={Boolean(errors.enmDeliveryStatus)}
                  helperText={errors.enmDeliveryStatus?.message}
                >
                  {enmDeliveryStatusOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="location"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('location') ?? "Location"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.location)}
                  helperText={errors.location?.message}
                />
              )}
            />
            <Controller
              name="notes"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label={fieldLabel('notes') ?? "Notes"}
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.notes)}
                  helperText={errors.notes?.message}
                />
              )}
            />
            {isEditMode && existingData && (
              <>
                <Divider sx={{ my: 1 }} />
                <Typography variant="subtitle2" color="text.secondary">
                  {he.grid.computedFields}
                </Typography>
                <TextField
                  label={fieldLabel('notes') ?? "Products Summary"}
                  value={existingData.productsSummary ?? ''}
                  disabled
                  fullWidth
                />
              </>
            )}
            <Box display="flex" gap={2} mt={2}>
              <Button type="submit" variant="contained" disabled={isSubmitting}>
                {isSubmitting ? he.actions.saving : (isEditMode ? he.actions.save : he.actions.create)}
              </Button>
              {!embedded && (
                <Button variant="outlined" onClick={() => navigate('/deliveries')}>
                  {he.actions.cancel}
                </Button>
              )}
            </Box>
          </Box>
        </form>
      </Paper>
    </Box>
    </PermissionGate>
  );
}

