// DeliveryView.tsx
// Generated by CodeCreator
import { useState, useCallback } from 'react';
import {
  Box,
  Paper,
  Typography,
  Button,
  Skeleton,
  Chip,
  IconButton,
  Tooltip,
  Snackbar,
} from '@mui/material';
import Grid from '@mui/material/Grid2';
import PrintIcon from '@mui/icons-material/Print';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import { PermissionGate } from '../contexts/AuthContext';
import { fieldLabel } from '../i18n/fieldLabels';
import he from '../i18n/he';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { useDelivery } from '../hooks/useDelivery';
import { useEnumValues } from '../hooks/useEnumValues';
import { Tabs, Tab } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { api } from '../api/client';

export default function DeliveryView() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const parsedId = id ? Number(id) : 0;
  const { data: entity, isLoading, isError } = useDelivery(parsedId);
  const enmDeliveryMethodOptions = useEnumValues('DeliveryMethod');
  const enmDeliveryStatusOptions = useEnumValues('DeliveryStatus');

  const [copiedField, setCopiedField] = useState('');
  const copyToClipboard = useCallback((value: unknown, fieldName: string) => {
    navigator.clipboard.writeText(String(value ?? '')).then(() => setCopiedField(fieldName));
  }, []);

  const [activeTab, setActiveTab] = useState(0);
  const { data: auditData } = useQuery({
    queryKey: ['audit', 'Delivery', parsedId],
    queryFn: () => api.get(`/audit/Delivery/${parsedId}`).then((r) => r.data as { items: unknown[]; total: number }),
    enabled: Boolean(parsedId) && activeTab === 1,
  });

  if (isLoading) {
    return (
      <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
        <Skeleton variant="text" width={250} height={40} sx={{ mb: 3 }} />
        <Paper sx={{ p: 3 }}>
          <Grid container spacing={2}>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
          </Grid>
        </Paper>
      </Box>
    );
  }

  if (isError || !entity) {
    return (
      <Box p={4}>
        <Typography color="error">{he.messages.notFound}</Typography>
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
      <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h5">{he.actions.details}</Typography>
        <Box display="flex" gap={1}>
          <PermissionGate entity="delivery" action="write">
            <Button variant="contained" onClick={() => navigate(`/deliveries/${entity.id}/edit`)}>
              {he.actions.edit}
            </Button>
          </PermissionGate>
          <PermissionGate entity="delivery" action="write">
            <Button variant="outlined" startIcon={<ContentCopyIcon />} onClick={() => navigate(`/deliveries/new?cloneFrom=${entity.id}`)}>
              {he.actions.duplicate}
            </Button>
          </PermissionGate>
          <Button variant="outlined" onClick={() => navigate('/deliveries')}>
            {he.actions.backToList}
          </Button>
          <Button variant="outlined" startIcon={<PrintIcon />} onClick={() => window.print()} className="no-print">
            {he.actions.print}
          </Button>
        </Box>
      </Box>
      <Paper sx={{ p: 3 }}>
        <Grid container spacing={2}>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('id') ?? 'ID'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy ID" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.id, 'ID')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.id}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary" title="Order Header">
                Order Header ID
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Order Header ID" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.fkOrderHeaderId, 'Order Header ID')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              <Link to={`/orderHeaders/${entity.fkOrderHeaderId}`} style={{ color: 'inherit', textDecoration: 'underline' }}>
                {entity.fkOrderHeaderId}
              </Link>
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('deliveryAddress') ?? 'Delivery Address'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Delivery Address" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.deliveryAddress, 'Delivery Address')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.deliveryAddress ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('contactPhone') ?? 'Contact Phone'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Contact Phone" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.contactPhone, 'Contact Phone')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.contactPhone ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('contactName') ?? 'Contact Name'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Contact Name" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.contactName, 'Contact Name')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.contactName ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('enmDeliveryMethod') ?? 'Delivery Method'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Delivery Method" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.enmDeliveryMethod, 'Delivery Method')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {enmDeliveryMethodOptions.find((o) => o.value === entity.enmDeliveryMethod)?.label || String(entity.enmDeliveryMethod)}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('orderedDate') ?? 'Ordered Date'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Ordered Date" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.orderedDate, 'Ordered Date')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {(() => { const v = entity.orderedDate; if (!v || String(v) < '1900') return '-'; return new Date(v).toLocaleDateString(); })()}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('receivedDate') ?? 'Received Date'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Received Date" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.receivedDate, 'Received Date')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {(() => { const v = entity.receivedDate; if (!v || String(v) < '1900') return '-'; return new Date(v).toLocaleDateString(); })()}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('arrivalToHubDate') ?? 'Arrival To Hub Date'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Arrival To Hub Date" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.arrivalToHubDate, 'Arrival To Hub Date')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {(() => { const v = entity.arrivalToHubDate; if (!v || String(v) < '1900') return '-'; return new Date(v).toLocaleDateString(); })()}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('arrivalToCustomerDate') ?? 'Arrival To Customer Date'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Arrival To Customer Date" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.arrivalToCustomerDate, 'Arrival To Customer Date')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {(() => { const v = entity.arrivalToCustomerDate; if (!v || String(v) < '1900') return '-'; return new Date(v).toLocaleDateString(); })()}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('enmDeliveryStatus') ?? 'Delivery Status'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Delivery Status" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.enmDeliveryStatus, 'Delivery Status')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {enmDeliveryStatusOptions.find((o) => o.value === entity.enmDeliveryStatus)?.label || String(entity.enmDeliveryStatus)}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('location') ?? 'Location'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Location" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.location, 'Location')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.location ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('productsSummary') ?? 'Products Summary'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Products Summary" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.productsSummary, 'Products Summary')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.productsSummary ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('notes') ?? 'Notes'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Notes" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.notes, 'Notes')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.notes ?? '-'}
            </Typography>
          </Grid>
        </Grid>
      </Paper>

      <Box sx={{ mt: 3 }}>
        <Tabs value={activeTab} onChange={(_, v) => setActiveTab(v)} sx={{ borderBottom: 1, borderColor: 'divider' }}>
          <Tab label={he.actions.details} />
          <Tab label={he.grid.history} />
        </Tabs>

        {/* History tab — fetches from c_AuditIndexed */}
        {activeTab === 1 && (
          <Box sx={{ pt: 2 }}>
            {auditData?.items ? (
              <Box>
                {(auditData.items as { id: number; fieldName: string; oldValue: string; newValue: string; changedByUser: string; occurredAt: string; operation: string }[]).map((a) => (
                  <Paper key={a.id} variant="outlined" sx={{ p: 1.5, mb: 1, display: 'flex', gap: 2, alignItems: 'center' }}>
                    <Typography variant="caption" color="text.secondary" sx={{ minWidth: 140 }}>
                      {new Date(a.occurredAt).toLocaleString()}
                    </Typography>
                    <Typography variant="body2" sx={{ fontWeight: 600 }}>{a.changedByUser}</Typography>
                    <Typography variant="body2">
                      {a.operation === 'Added' ? 'Created record' : `Changed ${a.fieldName}`}
                      {a.oldValue && a.newValue ? ` from "${a.oldValue}" to "${a.newValue}"` : a.newValue ? `: "${a.newValue}"` : ''}
                    </Typography>
                  </Paper>
                ))}
                {auditData.items.length === 0 && <Typography color="text.secondary">No history available</Typography>}
              </Box>
            ) : <Typography>Loading history...</Typography>}
          </Box>
        )}
      </Box>
      <Snackbar
        open={Boolean(copiedField)}
        autoHideDuration={2000}
        onClose={() => setCopiedField('')}
        message={`${copiedField} copied to clipboard`}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      />
    </Box>
  );
}

