// OrderLineForm.tsx
// Generated by CodeCreator
import { useEffect, useState, useCallback } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  TextField,
  Button,
  Box,
  Paper,
  Typography,
  FormControlLabel,
  Checkbox,
  CircularProgress,
  MenuItem,
  Divider,
  Autocomplete,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Alert,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Snackbar,
} from '@mui/material';
import { ExpandMore as ExpandMoreIcon } from '@mui/icons-material';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useOrderLine, useCreateOrderLine, useUpdateOrderLine } from '../hooks/useOrderLine';
import { orderLineSchema, type OrderLineFormData } from '../types/OrderLine';
import { PermissionGate } from '../contexts/AuthContext';
import { useQuery } from '@tanstack/react-query';
import { OrderHeaderApi } from '../api/OrderHeaderApi';
import { ProductApi } from '../api/ProductApi';

interface OrderLineFormProps {
  embedded?: boolean;
  onSuccess?: () => void;
}

export default function OrderLineForm({ embedded, onSuccess }: OrderLineFormProps = {}) {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const isEditMode = !embedded && Boolean(id);
  const [searchParams] = useSearchParams();
  const cloneFromId = searchParams.get('cloneFrom');

  const { data: orderHeaderData } = useQuery({
    queryKey: ['orderHeaders', 'all'],
    queryFn: () => OrderHeaderApi.getAll(0, 9999, ''),
    staleTime: 5 * 60 * 1000,
  });
  const { data: productData } = useQuery({
    queryKey: ['products', 'all'],
    queryFn: () => ProductApi.getAll(0, 9999, ''),
    staleTime: 5 * 60 * 1000,
  });

  const parsedId = id ? Number(id) : 0;
  const { data: existingData, isLoading: isLoadingData } = useOrderLine(parsedId);
  const cloneParsedId = cloneFromId ? Number(cloneFromId) : 0;
  const { data: cloneSourceData } = useOrderLine(cloneParsedId);
  const createMutation = useCreateOrderLine();
  const updateMutation = useUpdateOrderLine();

  const {
    control,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting, isDirty },
  } = useForm<OrderLineFormData>({
    resolver: zodResolver(orderLineSchema),
  });

  useEffect(() => {
    if (isEditMode && existingData) {
      reset({
        fkOrderHeaderId: existingData.fkOrderHeaderId,
        fkProductId: existingData.fkProductId,
        quantity: existingData.quantity,
        unitPrice: existingData.unitPrice,
        discountPercent: existingData.discountPercent ?? 0,
        lineNumber: existingData.lineNumber,
      });
    }
  }, [isEditMode, existingData, reset]);

  useEffect(() => {
    if (!isEditMode && cloneFromId && cloneSourceData) {
      reset({
        fkOrderHeaderId: cloneSourceData.fkOrderHeaderId,
        fkProductId: cloneSourceData.fkProductId,
        quantity: cloneSourceData.quantity,
        unitPrice: cloneSourceData.unitPrice,
        discountPercent: cloneSourceData.discountPercent ?? 0,
        lineNumber: cloneSourceData.lineNumber,
      });
    }
  }, [cloneFromId, cloneSourceData, isEditMode, reset]);

  const [conflictData, setConflictData] = useState<Record<string,unknown> | null>(null);

  const onSubmit = async (formData: OrderLineFormData) => {
    try {
      if (isEditMode) {
        const payload = { ...formData, _etag: (existingData as unknown as Record<string,unknown>)?._etag } as Record<string,unknown>;
        await updateMutation.mutateAsync({ id: parsedId, data: payload as unknown as OrderLineFormData });
      } else {
        await createMutation.mutateAsync(formData);
      }
      localStorage.removeItem(draftKey); // Clear draft on successful save
      if (embedded && onSuccess) {
        onSuccess();
      } else {
        navigate('/orderLines');
      }
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'name' in error && (error as Error).name === 'ConflictError') {
        setConflictData({ message: (error as Error).message });
        return;
      }
      const axiosErr = error as { response?: { status?: number; data?: Record<string,unknown> } };
      if (axiosErr.response?.status === 409) {
        setConflictData(axiosErr.response.data as Record<string,unknown>);
      } else {
        console.error('Failed to save orderLine:', error);
      }
    }
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && (e.key === 'Enter' || e.key === 's')) {
        e.preventDefault();
        handleSubmit(onSubmit)();
      }
      if (e.key === 'Escape') {
        navigate('/orderLines');
      }
    };
  
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }); // re-registers on every render to capture latest form state

  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isDirty && !isSubmitting) {
        e.preventDefault();
      }
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [isDirty, isSubmitting]);

  // Auto-save draft to localStorage every 30 seconds
  const draftKey = `draft_orderLine_${isEditMode ? id : 'new'}`;
  const [hasDraft, setHasDraft] = useState(false);
  const [draftRestored, setDraftRestored] = useState(false);
  useEffect(() => {
    if (draftRestored) return;
    const saved = localStorage.getItem(draftKey);
    if (saved) setHasDraft(true);
  }, [draftKey, draftRestored]);
  useEffect(() => {
    if (!isDirty) return;
    const timer = setInterval(() => {
      const formValues = control._formValues;
      if (formValues) localStorage.setItem(draftKey, JSON.stringify(formValues));
    }, 30000);
    return () => clearInterval(timer);
  }, [isDirty, draftKey, control]);
  const restoreDraft = useCallback(() => {
    const saved = localStorage.getItem(draftKey);
    if (saved) { try { reset(JSON.parse(saved)); } catch {} }
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey, reset]);
  const discardDraft = useCallback(() => {
    localStorage.removeItem(draftKey);
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey]);

  // Warn on browser close/refresh when form is dirty
  useEffect(() => {
    const handler = (e: BeforeUnloadEvent) => { if (isDirty && !isSubmitting) { e.preventDefault(); } };
    window.addEventListener('beforeunload', handler);
    return () => window.removeEventListener('beforeunload', handler);
  }, [isDirty, isSubmitting]);

  if ((isEditMode && isLoadingData) || (cloneFromId && !cloneSourceData)) {
    return (
      <Box display="flex" justifyContent="center" p={4}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <PermissionGate entity="orderLine" action="write">
    <Box sx={{ p: embedded ? 1 : 3, maxWidth: embedded ? '100%' : 800, mx: 'auto' }}>
      {/* Auto-save draft banner */}
      {hasDraft && !draftRestored && (
        <Alert severity="info" sx={{ mb: 2 }} action={
          <Box>
            <Button size="small" onClick={restoreDraft}>Restore</Button>
            <Button size="small" color="inherit" onClick={discardDraft}>Discard</Button>
          </Box>
        }>Unsaved draft found. Restore or discard?</Alert>
      )}
      {/* Navigation guard handled by beforeunload event */}
      {/* Concurrency conflict dialog */}
      <Dialog open={Boolean(conflictData)} onClose={() => setConflictData(null)} maxWidth="sm" fullWidth>
        <DialogTitle color="error">Conflict — Record Modified</DialogTitle>
        <DialogContent>
          <DialogContentText>
            <>{(conflictData as Record<string,unknown>)?.message ?? 'This record was modified by another user since you loaded it.'}{' '}Your changes were not saved. Please refresh and try again.</>
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setConflictData(null); window.location.reload(); }} variant="contained">Refresh &amp; Retry</Button>
        </DialogActions>
      </Dialog>
      {!embedded && (
        <Typography variant="h5" mb={3}>
          {isEditMode ? 'Edit Order Line' : cloneFromId ? 'Clone Order Line' : 'Add Order Line'}
        </Typography>
      )}
      <Paper sx={{ p: 3, elevation: embedded ? 0 : undefined }}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Box display="flex" flexDirection="column" gap={2}>
            <Controller
              name="fkOrderHeaderId"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <Autocomplete
                  options={orderHeaderData?.items || []}
                  getOptionLabel={(option) => `${(option as any).id} - ${(option as any).invoiceNumber || ''}`}
                  value={(orderHeaderData?.items || []).find((i: any) => i.id === field.value) || null}
                  onChange={(_, newValue) => field.onChange(newValue ? (newValue as any).id : 0)}
                  isOptionEqualToValue={(option, value) => (option as any).id === (value as any)?.id}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label="Order Header ID"
                      title="Order Header"
                      autoFocus
                      required
                      error={Boolean(errors.fkOrderHeaderId)}
                      helperText={errors.fkOrderHeaderId?.message}
                    />
                  )}
                />
              )}
            />
            <Controller
              name="fkProductId"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <Autocomplete
                  options={productData?.items || []}
                  getOptionLabel={(option) => `${(option as any).id} - ${(option as any).productCode || ''}`}
                  value={(productData?.items || []).find((i: any) => i.id === field.value) || null}
                  onChange={(_, newValue) => field.onChange(newValue ? (newValue as any).id : 0)}
                  isOptionEqualToValue={(option, value) => (option as any).id === (value as any)?.id}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label="Product ID"
                      title="Product"
                      required
                      error={Boolean(errors.fkProductId)}
                      helperText={errors.fkProductId?.message}
                    />
                  )}
                />
              )}
            />
            <Controller
              name="quantity"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Quantity"
                  type="number"
                  fullWidth
                  required
                  error={Boolean(errors.quantity)}
                  helperText={errors.quantity?.message}
                />
              )}
            />
            <Controller
              name="unitPrice"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Unit Price"
                  type="number"
                  fullWidth
                  required
                  error={Boolean(errors.unitPrice)}
                  helperText={errors.unitPrice?.message}
                />
              )}
            />
            <Controller
              name="discountPercent"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Discount Percent"
                  type="number"
                  fullWidth
                  error={Boolean(errors.discountPercent)}
                  helperText={errors.discountPercent?.message}
                />
              )}
            />
            <Controller
              name="lineNumber"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Line Number"
                  type="number"
                  fullWidth
                  required
                  error={Boolean(errors.lineNumber)}
                  helperText={errors.lineNumber?.message}
                />
              )}
            />
            {isEditMode && existingData && (
              <>
                <Divider sx={{ my: 1 }} />
                <Typography variant="subtitle2" color="text.secondary">
                  Computed Fields
                </Typography>
                <TextField
                  label="Unit Cost"
                  value={existingData.unitCost ?? ''}
                  disabled
                  fullWidth
                />
                <TextField
                  label="Line Total"
                  value={existingData.lineTotal ?? ''}
                  disabled
                  fullWidth
                />
                <TextField
                  label="Total Cost"
                  value={existingData.totalCost ?? ''}
                  disabled
                  fullWidth
                />
                <TextField
                  label="Profit"
                  value={existingData.profit ?? ''}
                  disabled
                  fullWidth
                />
              </>
            )}
            <Box display="flex" gap={2} mt={2}>
              <Button type="submit" variant="contained" disabled={isSubmitting}>
                {isSubmitting ? 'Saving...' : (isEditMode ? 'Update' : 'Create')}
              </Button>
              {!embedded && (
                <Button variant="outlined" onClick={() => navigate('/orderLines')}>
                  Cancel
                </Button>
              )}
            </Box>
          </Box>
        </form>
      </Paper>
    </Box>
    </PermissionGate>
  );
}

