// OrderHeaderForm.tsx
// Generated by CodeCreator
import { useEffect, useState, useCallback } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  TextField,
  Button,
  Box,
  Paper,
  Typography,
  FormControlLabel,
  Checkbox,
  CircularProgress,
  MenuItem,
  Divider,
  Autocomplete,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Alert,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Snackbar,
} from '@mui/material';
import { ExpandMore as ExpandMoreIcon } from '@mui/icons-material';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useOrderHeader, useCreateOrderHeader, useUpdateOrderHeader } from '../hooks/useOrderHeader';
import { orderHeaderSchema, type OrderHeaderFormData } from '../types/OrderHeader';
import { PermissionGate } from '../contexts/AuthContext';
import { useEnumValues } from '../hooks/useEnumValues';
import { useQuery } from '@tanstack/react-query';
import { CustomerApi } from '../api/CustomerApi';

interface OrderHeaderFormProps {
  embedded?: boolean;
  onSuccess?: () => void;
}

export default function OrderHeaderForm({ embedded, onSuccess }: OrderHeaderFormProps = {}) {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const isEditMode = !embedded && Boolean(id);
  const [searchParams] = useSearchParams();
  const cloneFromId = searchParams.get('cloneFrom');

  const enmPaymentMethodOptions = useEnumValues('PaymentMethod');
  const enmPaymentStatusOptions = useEnumValues('PaymentStatus');
  const enmDeliveryMethodOptions = useEnumValues('DeliveryMethod');
  const enmDeliveryDayOptions = useEnumValues('DeliveryDay');
  const enmOrderStatusOptions = useEnumValues('OrderStatus');

  const { data: customerData } = useQuery({
    queryKey: ['customers', 'all'],
    queryFn: () => CustomerApi.getAll(0, 9999, ''),
    staleTime: 5 * 60 * 1000,
  });

  const parsedId = id ? Number(id) : 0;
  const { data: existingData, isLoading: isLoadingData } = useOrderHeader(parsedId);
  const cloneParsedId = cloneFromId ? Number(cloneFromId) : 0;
  const { data: cloneSourceData } = useOrderHeader(cloneParsedId);
  const createMutation = useCreateOrderHeader();
  const updateMutation = useUpdateOrderHeader();

  const {
    control,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting, isDirty },
  } = useForm<OrderHeaderFormData>({
    resolver: zodResolver(orderHeaderSchema),
  });

  useEffect(() => {
    if (isEditMode && existingData) {
      reset({
        orderNumber: existingData.orderNumber,
        fkCustomerId: existingData.fkCustomerId,
        orderDate: existingData.orderDate,
        enmPaymentMethod: existingData.enmPaymentMethod ?? 0,
        enmPaymentStatus: existingData.enmPaymentStatus ?? 0,
        paymentDate: existingData.paymentDate ?? '',
        invoiceNumber: existingData.invoiceNumber ?? '',
        enmDeliveryMethod: existingData.enmDeliveryMethod ?? 0,
        deliveryDate: existingData.deliveryDate ?? '',
        enmDeliveryDay: existingData.enmDeliveryDay ?? 0,
        enmOrderStatus: existingData.enmOrderStatus ?? 0,
        notes: existingData.notes ?? '',
        notes2: existingData.notes2 ?? '',
      });
    }
  }, [isEditMode, existingData, reset]);

  useEffect(() => {
    if (!isEditMode && cloneFromId && cloneSourceData) {
      reset({
        orderNumber: 0,  // Unique - must change before saving
        fkCustomerId: cloneSourceData.fkCustomerId,
        orderDate: cloneSourceData.orderDate,
        enmPaymentMethod: cloneSourceData.enmPaymentMethod ?? 0,
        enmPaymentStatus: cloneSourceData.enmPaymentStatus ?? 0,
        paymentDate: cloneSourceData.paymentDate ?? '',
        invoiceNumber: cloneSourceData.invoiceNumber ?? '',
        enmDeliveryMethod: cloneSourceData.enmDeliveryMethod ?? 0,
        deliveryDate: cloneSourceData.deliveryDate ?? '',
        enmDeliveryDay: cloneSourceData.enmDeliveryDay ?? 0,
        enmOrderStatus: cloneSourceData.enmOrderStatus ?? 0,
        notes: cloneSourceData.notes ?? '',
        notes2: cloneSourceData.notes2 ?? '',
      });
    }
  }, [cloneFromId, cloneSourceData, isEditMode, reset]);

  const [conflictData, setConflictData] = useState<Record<string,unknown> | null>(null);

  const onSubmit = async (formData: OrderHeaderFormData) => {
    try {
      if (isEditMode) {
        const payload = { ...formData, _etag: (existingData as unknown as Record<string,unknown>)?._etag } as Record<string,unknown>;
        await updateMutation.mutateAsync({ id: parsedId, data: payload as unknown as OrderHeaderFormData });
      } else {
        await createMutation.mutateAsync(formData);
      }
      localStorage.removeItem(draftKey); // Clear draft on successful save
      if (embedded && onSuccess) {
        onSuccess();
      } else {
        navigate('/orderHeaders');
      }
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'name' in error && (error as Error).name === 'ConflictError') {
        setConflictData({ message: (error as Error).message });
        return;
      }
      const axiosErr = error as { response?: { status?: number; data?: Record<string,unknown> } };
      if (axiosErr.response?.status === 409) {
        setConflictData(axiosErr.response.data as Record<string,unknown>);
      } else {
        console.error('Failed to save orderHeader:', error);
      }
    }
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && (e.key === 'Enter' || e.key === 's')) {
        e.preventDefault();
        handleSubmit(onSubmit)();
      }
      if (e.key === 'Escape') {
        navigate('/orderHeaders');
      }
    };
  
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }); // re-registers on every render to capture latest form state

  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isDirty && !isSubmitting) {
        e.preventDefault();
      }
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [isDirty, isSubmitting]);

  // Auto-save draft to localStorage every 30 seconds
  const draftKey = `draft_orderHeader_${isEditMode ? id : 'new'}`;
  const [hasDraft, setHasDraft] = useState(false);
  const [draftRestored, setDraftRestored] = useState(false);
  useEffect(() => {
    if (draftRestored) return;
    const saved = localStorage.getItem(draftKey);
    if (saved) setHasDraft(true);
  }, [draftKey, draftRestored]);
  useEffect(() => {
    if (!isDirty) return;
    const timer = setInterval(() => {
      const formValues = control._formValues;
      if (formValues) localStorage.setItem(draftKey, JSON.stringify(formValues));
    }, 30000);
    return () => clearInterval(timer);
  }, [isDirty, draftKey, control]);
  const restoreDraft = useCallback(() => {
    const saved = localStorage.getItem(draftKey);
    if (saved) { try { reset(JSON.parse(saved)); } catch {} }
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey, reset]);
  const discardDraft = useCallback(() => {
    localStorage.removeItem(draftKey);
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey]);

  // Warn on browser close/refresh when form is dirty
  useEffect(() => {
    const handler = (e: BeforeUnloadEvent) => { if (isDirty && !isSubmitting) { e.preventDefault(); } };
    window.addEventListener('beforeunload', handler);
    return () => window.removeEventListener('beforeunload', handler);
  }, [isDirty, isSubmitting]);

  if ((isEditMode && isLoadingData) || (cloneFromId && !cloneSourceData)) {
    return (
      <Box display="flex" justifyContent="center" p={4}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <PermissionGate entity="orderHeader" action="write">
    <Box sx={{ p: embedded ? 1 : 3, maxWidth: embedded ? '100%' : 800, mx: 'auto' }}>
      {/* Auto-save draft banner */}
      {hasDraft && !draftRestored && (
        <Alert severity="info" sx={{ mb: 2 }} action={
          <Box>
            <Button size="small" onClick={restoreDraft}>Restore</Button>
            <Button size="small" color="inherit" onClick={discardDraft}>Discard</Button>
          </Box>
        }>Unsaved draft found. Restore or discard?</Alert>
      )}
      {/* Navigation guard handled by beforeunload event */}
      {/* Concurrency conflict dialog */}
      <Dialog open={Boolean(conflictData)} onClose={() => setConflictData(null)} maxWidth="sm" fullWidth>
        <DialogTitle color="error">Conflict — Record Modified</DialogTitle>
        <DialogContent>
          <DialogContentText>
            <>{(conflictData as Record<string,unknown>)?.message ?? 'This record was modified by another user since you loaded it.'}{' '}Your changes were not saved. Please refresh and try again.</>
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setConflictData(null); window.location.reload(); }} variant="contained">Refresh &amp; Retry</Button>
        </DialogActions>
      </Dialog>
      {!embedded && (
        <Typography variant="h5" mb={3}>
          {isEditMode ? 'Edit Order Header' : cloneFromId ? 'Clone Order Header' : 'Add Order Header'}
        </Typography>
      )}
      {cloneFromId && (
        <Alert severity="warning" sx={{ mb: 2 }}>
          Cloning record — the following unique fields were cleared and <strong>must be filled with new values</strong> before saving:
          <br />• Order Number
        </Alert>
      )}
      <Paper sx={{ p: 3, elevation: embedded ? 0 : undefined }}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Box display="flex" flexDirection="column" gap={2}>
            <Controller
              name="orderNumber"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Order Number"
                  type="number"
                  fullWidth
                  autoFocus
                  required
                  error={Boolean(errors.orderNumber)}
                  helperText={errors.orderNumber?.message}
                />
              )}
            />
            <Controller
              name="fkCustomerId"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <Autocomplete
                  options={customerData?.items || []}
                  getOptionLabel={(option) => `${(option as any).id} - ${(option as any).customerCode || ''}`}
                  value={(customerData?.items || []).find((i: any) => i.id === field.value) || null}
                  onChange={(_, newValue) => field.onChange(newValue ? (newValue as any).id : 0)}
                  isOptionEqualToValue={(option, value) => (option as any).id === (value as any)?.id}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label="Customer ID"
                      title="Customer"
                      required
                      error={Boolean(errors.fkCustomerId)}
                      helperText={errors.fkCustomerId?.message}
                    />
                  )}
                />
              )}
            />
            <Controller
              name="orderDate"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 16); })()}
                  label="Order Date"
                  type="datetime-local"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  required
                  error={Boolean(errors.orderDate)}
                  helperText={errors.orderDate?.message}
                />
              )}
            />
            <Controller
              name="enmPaymentMethod"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Payment Method"
                  select
                  fullWidth
                  error={Boolean(errors.enmPaymentMethod)}
                  helperText={errors.enmPaymentMethod?.message}
                >
                  {enmPaymentMethodOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="enmPaymentStatus"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Payment Status"
                  select
                  fullWidth
                  error={Boolean(errors.enmPaymentStatus)}
                  helperText={errors.enmPaymentStatus?.message}
                >
                  {enmPaymentStatusOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="paymentDate"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 10); })()}
                  label="Payment Date"
                  type="date"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  error={Boolean(errors.paymentDate)}
                  helperText={errors.paymentDate?.message}
                />
              )}
            />
            <Controller
              name="invoiceNumber"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Invoice Number"
                  type="text"
                  fullWidth
                  error={Boolean(errors.invoiceNumber)}
                  helperText={errors.invoiceNumber?.message}
                />
              )}
            />
            <Controller
              name="enmDeliveryMethod"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Delivery Method"
                  select
                  fullWidth
                  error={Boolean(errors.enmDeliveryMethod)}
                  helperText={errors.enmDeliveryMethod?.message}
                >
                  {enmDeliveryMethodOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="deliveryDate"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 10); })()}
                  label="Delivery Date"
                  type="date"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  error={Boolean(errors.deliveryDate)}
                  helperText={errors.deliveryDate?.message}
                />
              )}
            />
            <Controller
              name="enmDeliveryDay"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Delivery Day"
                  select
                  fullWidth
                  error={Boolean(errors.enmDeliveryDay)}
                  helperText={errors.enmDeliveryDay?.message}
                >
                  {enmDeliveryDayOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="enmOrderStatus"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Order Status"
                  select
                  fullWidth
                  error={Boolean(errors.enmOrderStatus)}
                  helperText={errors.enmOrderStatus?.message}
                >
                  {enmOrderStatusOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="notes"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Notes"
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.notes)}
                  helperText={errors.notes?.message}
                />
              )}
            />
            <Controller
              name="notes2"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Notes2"
                  title="Notes 2"
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.notes2)}
                  helperText={errors.notes2?.message}
                />
              )}
            />
            {isEditMode && existingData && (
              <>
                <Divider sx={{ my: 1 }} />
                <Typography variant="subtitle2" color="text.secondary">
                  Computed Fields
                </Typography>
                <TextField
                  label="Total Amount"
                  value={existingData.totalAmount ?? ''}
                  disabled
                  fullWidth
                />
                <TextField
                  label="VATAmount"
                  value={existingData.vatAmount ?? ''}
                  disabled
                  fullWidth
                />
                <TextField
                  label="Total With VAT"
                  value={existingData.totalWithVat ?? ''}
                  disabled
                  fullWidth
                />
                <TextField
                  label="Order Month"
                  value={existingData.orderMonth ?? ''}
                  disabled
                  fullWidth
                />
                <TextField
                  label="Quarter"
                  value={existingData.quarter ?? ''}
                  disabled
                  fullWidth
                />
              </>
            )}
            <Box display="flex" gap={2} mt={2}>
              <Button type="submit" variant="contained" disabled={isSubmitting}>
                {isSubmitting ? 'Saving...' : (isEditMode ? 'Update' : 'Create')}
              </Button>
              {!embedded && (
                <Button variant="outlined" onClick={() => navigate('/orderHeaders')}>
                  Cancel
                </Button>
              )}
            </Box>
          </Box>
        </form>
      </Paper>
    </Box>
    </PermissionGate>
  );
}

