// OrderLineView.tsx
// Generated by CodeCreator
import { useState, useCallback } from 'react';
import {
  Box,
  Paper,
  Typography,
  Button,
  Skeleton,
  Chip,
  IconButton,
  Tooltip,
  Snackbar,
} from '@mui/material';
import Grid from '@mui/material/Grid2';
import PrintIcon from '@mui/icons-material/Print';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import { PermissionGate } from '../contexts/AuthContext';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { useOrderLine } from '../hooks/useOrderLine';
import { Tabs, Tab } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import { api } from '../api/client';

export default function OrderLineView() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const parsedId = id ? Number(id) : 0;
  const { data: entity, isLoading, isError } = useOrderLine(parsedId);

  const [copiedField, setCopiedField] = useState('');
  const copyToClipboard = useCallback((value: unknown, fieldName: string) => {
    navigator.clipboard.writeText(String(value ?? '')).then(() => setCopiedField(fieldName));
  }, []);

  const [activeTab, setActiveTab] = useState(0);
  const { data: auditData } = useQuery({
    queryKey: ['audit', 'OrderLine', parsedId],
    queryFn: () => api.get(`/audit/OrderLine/${parsedId}`).then((r) => r.data as { items: unknown[]; total: number }),
    enabled: Boolean(parsedId) && activeTab === 1,
  });

  if (isLoading) {
    return (
      <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
        <Skeleton variant="text" width={250} height={40} sx={{ mb: 3 }} />
        <Paper sx={{ p: 3 }}>
          <Grid container spacing={2}>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
          </Grid>
        </Paper>
      </Box>
    );
  }

  if (isError || !entity) {
    return (
      <Box p={4}>
        <Typography color="error">Order Line not found.</Typography>
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
      <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h5">Order Line Details</Typography>
        <Box display="flex" gap={1}>
          <PermissionGate entity="orderLine" action="write">
            <Button variant="contained" onClick={() => navigate(`/orderLines/${entity.id}/edit`)}>
              Edit
            </Button>
          </PermissionGate>
          <PermissionGate entity="orderLine" action="write">
            <Button variant="outlined" startIcon={<ContentCopyIcon />} onClick={() => navigate(`/orderLines/new?cloneFrom=${entity.id}`)}>
              Clone
            </Button>
          </PermissionGate>
          <Button variant="outlined" onClick={() => navigate('/orderLines')}>
            Back to List
          </Button>
          <Button variant="outlined" startIcon={<PrintIcon />} onClick={() => window.print()} className="no-print">
            Print
          </Button>
        </Box>
      </Box>
      <Paper sx={{ p: 3 }}>
        <Grid container spacing={2}>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                ID
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy ID" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.id, 'ID')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.id}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary" title="Order Header">
                Order Header ID
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Order Header ID" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.fkOrderHeaderId, 'Order Header ID')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              <Link to={`/orderHeaders/${entity.fkOrderHeaderId}`} style={{ color: 'inherit', textDecoration: 'underline' }}>
                {entity.fkOrderHeaderId}
              </Link>
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary" title="Product">
                Product ID
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Product ID" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.fkProductId, 'Product ID')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              <Link to={`/products/${entity.fkProductId}`} style={{ color: 'inherit', textDecoration: 'underline' }}>
                {entity.fkProductId}
              </Link>
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Quantity
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Quantity" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.quantity, 'Quantity')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.quantity}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Unit Price
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Unit Price" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.unitPrice, 'Unit Price')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.unitPrice}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Discount Percent
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Discount Percent" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.discountPercent, 'Discount Percent')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.discountPercent ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Unit Cost
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Unit Cost" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.unitCost, 'Unit Cost')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.unitCost ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Line Number
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Line Number" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.lineNumber, 'Line Number')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.lineNumber}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Line Total
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Line Total" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.lineTotal, 'Line Total')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.lineTotal ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Total Cost
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Total Cost" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.totalCost, 'Total Cost')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.totalCost ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                Profit
              </Typography>
              <Tooltip title="Copy" className="no-print">
                <IconButton size="small" aria-label="Copy Profit" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.profit, 'Profit')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.profit ?? '-'}
            </Typography>
          </Grid>
        </Grid>
      </Paper>

      <Box sx={{ mt: 3 }}>
        <Tabs value={activeTab} onChange={(_, v) => setActiveTab(v)} sx={{ borderBottom: 1, borderColor: 'divider' }}>
          <Tab label="Details" />
          <Tab label="History" />
        </Tabs>

        {/* History tab — fetches from c_AuditIndexed */}
        {activeTab === 1 && (
          <Box sx={{ pt: 2 }}>
            {auditData?.items ? (
              <Box>
                {(auditData.items as { id: number; fieldName: string; oldValue: string; newValue: string; changedByUser: string; occurredAt: string; operation: string }[]).map((a) => (
                  <Paper key={a.id} variant="outlined" sx={{ p: 1.5, mb: 1, display: 'flex', gap: 2, alignItems: 'center' }}>
                    <Typography variant="caption" color="text.secondary" sx={{ minWidth: 140 }}>
                      {new Date(a.occurredAt).toLocaleString()}
                    </Typography>
                    <Typography variant="body2" sx={{ fontWeight: 600 }}>{a.changedByUser}</Typography>
                    <Typography variant="body2">
                      {a.operation === 'Added' ? 'Created record' : `Changed ${a.fieldName}`}
                      {a.oldValue && a.newValue ? ` from "${a.oldValue}" to "${a.newValue}"` : a.newValue ? `: "${a.newValue}"` : ''}
                    </Typography>
                  </Paper>
                ))}
                {auditData.items.length === 0 && <Typography color="text.secondary">No history available</Typography>}
              </Box>
            ) : <Typography>Loading history...</Typography>}
          </Box>
        )}
      </Box>
      <Snackbar
        open={Boolean(copiedField)}
        autoHideDuration={2000}
        onClose={() => setCopiedField('')}
        message={`${copiedField} copied to clipboard`}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      />
    </Box>
  );
}

