// OrderLineList.tsx
// Generated by CodeCreator
import { useState, useCallback } from 'react';
import type { GridSortModel } from '@mui/x-data-grid';
import { type GridColDef, GridActionsCellItem } from '@mui/x-data-grid';
import { Box, Alert, Button, Dialog, DialogTitle, DialogContent } from '@mui/material';
import { Visibility as ViewIcon } from '@mui/icons-material';
import { ContentCopy as ContentCopyIcon } from '@mui/icons-material';
import { OpenInNew as OpenInNewIcon } from '@mui/icons-material';
import { Edit as EditIcon } from '@mui/icons-material';
import { Delete as DeleteIcon } from '@mui/icons-material';
import { useNavigate, Link } from 'react-router-dom';
import { useOrderLines, useUpdateOrderLine, useDeleteOrderLine } from '../hooks/useOrderLine';
import AppDataGrid from '../components/shared/AppDataGrid';
import ConfirmDialog from '../components/shared/ConfirmDialog';
import { useNotification } from '../contexts/NotificationContext';
import { PermissionGate } from '../contexts/AuthContext';
import OrderLineForm from './OrderLineForm';
import type { UpdateOrderLineRequest } from '../types/OrderLine';
import FilterBuilder from '../components/shared/FilterBuilder';
import FilterListIcon from '@mui/icons-material/FilterList';
import { Collapse } from '@mui/material';

export default function OrderLineList() {
  const [paginationModel, setPaginationModel] = useState({ page: 0, pageSize: 25 });
  const [search, setSearch] = useState('');
  const [sortModel, setSortModel] = useState<GridSortModel>([]);
  const [showFilters, setShowFilters] = useState(false);
  const [activeFilters, setActiveFilters] = useState<Record<string, unknown>>({});
  const sortField = sortModel[0]?.field ?? '';
  const sortDir = sortModel[0]?.sort ?? 'asc';
  const handleSortModelChange = useCallback((model: GridSortModel) => {
    setSortModel(model);
    setPaginationModel((prev) => ({ ...prev, page: 0 }));
  }, []);
  const { data, isLoading, isError, error } = useOrderLines(paginationModel.page, paginationModel.pageSize, search, sortField, sortDir);
  const deleteMutation = useDeleteOrderLine();
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const [selectedIds, setSelectedIds] = useState<(string | number)[]>([]);
  const [bulkDeleteConfirm, setBulkDeleteConfirm] = useState(false);
  const navigate = useNavigate();
  const { showSuccess } = useNotification();
  const updateMutation = useUpdateOrderLine();
  const [quickCreateOpen, setQuickCreateOpen] = useState(false);

  const columns: GridColDef[] = [
    { field: 'id', headerName: 'ID', width: 80, type: 'number' },
    {
      field: 'fkOrderHeaderId',
      headerName: 'Order Header ID',
      width: 120,
      renderCell: (params) => params.value ? (
        <Link to={`/orderHeaders/${params.value}`} style={{ color: 'inherit', textDecoration: 'underline' }}  onClick={(e) => e.stopPropagation()}>
          {params.value}
        </Link>
      ) : '',
    },
    {
      field: 'fkProductId',
      headerName: 'Product ID',
      width: 120,
      renderCell: (params) => params.value ? (
        <Link to={`/products/${params.value}`} style={{ color: 'inherit', textDecoration: 'underline' }}  onClick={(e) => e.stopPropagation()}>
          {params.value}
        </Link>
      ) : '',
    },
    { field: 'quantity', headerName: 'Quantity', width: 120 },
    { field: 'unitPrice', headerName: 'Unit Price', width: 130 },
    { field: 'discountPercent', headerName: 'Discount Percent', width: 130 },
    { field: 'unitCost', headerName: 'Unit Cost', width: 130 },
    { field: 'lineNumber', headerName: 'Line Number', width: 120 },
    { field: 'lineTotal', headerName: 'Line Total', width: 130 },
    { field: 'totalCost', headerName: 'Total Cost', width: 130 },
    { field: 'profit', headerName: 'Profit', width: 130 },
    {
      field: 'actions',
      type: 'actions',
      headerName: 'Actions',
      width: 140,
      getActions: (params) => [
        <GridActionsCellItem
          key="view"
          icon={<ViewIcon />}
          label="View"
          onClick={() => navigate(`/orderLines/${params.id}`)}
        />,
        <GridActionsCellItem
          key="edit"
          icon={<EditIcon />}
          label="Edit"
          onClick={() => navigate(`/orderLines/${params.id}/edit`)}
        />,
        <GridActionsCellItem
          key="delete"
          icon={<DeleteIcon />}
          label="Delete"
          onClick={() => setDeleteId(params.id as number)}
        />,
      ],
    },
  ];

  if (isError) {
    return (
      <Box sx={{ p: 3 }}>
        <Alert severity="error" sx={{ mb: 2 }}>
          Failed to load order lines: {(error as Error)?.message || 'Unknown error'}
        </Alert>
      </Box>
    );
  }

  const filterFields = [
    { field: 'fkOrderHeaderId', label: 'Order Header ID', type: 'number' as const },
    { field: 'fkProductId', label: 'Product ID', type: 'number' as const },
    { field: 'quantity', label: 'Quantity', type: 'number' as const },
    { field: 'unitPrice', label: 'Unit Price', type: 'number' as const },
    { field: 'discountPercent', label: 'Discount Percent', type: 'number' as const },
    { field: 'unitCost', label: 'Unit Cost', type: 'number' as const },
    { field: 'lineNumber', label: 'Line Number', type: 'number' as const },
    { field: 'lineTotal', label: 'Line Total', type: 'number' as const },
    { field: 'totalCost', label: 'Total Cost', type: 'number' as const },
    { field: 'profit', label: 'Profit', type: 'number' as const },
  ];

  return (
    <Box sx={{ p: 3 }}>
      <Box display="flex" justifyContent="flex-end" mb={1}>
        <Button size="small" startIcon={<FilterListIcon />} onClick={() => setShowFilters((p) => !p)} color={Object.keys(activeFilters).length > 0 ? 'primary' : 'inherit'}>
          {showFilters ? 'Hide Filters' : `Filters${Object.keys(activeFilters).length > 0 ? ` (${Object.keys(activeFilters).length})` : ''}`}
        </Button>
      </Box>
      <Collapse in={showFilters}>
        <FilterBuilder fields={filterFields} onApply={(f) => { setActiveFilters(f as Record<string, unknown>); setPaginationModel((p) => ({ ...p, page: 0 })); }} onClear={() => setActiveFilters({})} />
      </Collapse>
      <AppDataGrid
        entityName="orderLine"
        title="Order Line List"
        rows={data?.items || []}
        columns={columns}
        loading={isLoading}
        getRowId={(row) => (row as any).id as string | number}
        rowCount={data?.total || 0}
        paginationModel={paginationModel}
        onPaginationModelChange={setPaginationModel}
        serverSearch={search}
        onServerSearchChange={setSearch}
        sortModel={sortModel}
        onSortModelChange={handleSortModelChange}
        onRowClick={(id) => navigate(`/orderLines/${id}`)}
        checkboxSelection
        onSelectionChange={(ids) => setSelectedIds(ids)}
        onContextMenuActions={(id, row) => [
          { label: 'Open', icon: <OpenInNewIcon fontSize="small" />, onClick: () => navigate(`/orderLines/${id}`) },
          { label: 'Copy ID', icon: <ContentCopyIcon fontSize="small" />, onClick: () => { navigator.clipboard.writeText(String(id)); showSuccess('ID copied'); } },
          { label: 'Copy Row', icon: <ContentCopyIcon fontSize="small" />, onClick: () => { navigator.clipboard.writeText(JSON.stringify(row, null, 2)); showSuccess('Row copied'); } },
          { label: 'Duplicate', icon: <ContentCopyIcon fontSize="small" />, onClick: () => navigate(`/orderLines/new?cloneFrom=${id}`), divider: true },
          { label: 'Edit', icon: <EditIcon fontSize="small" />, onClick: () => navigate(`/orderLines/${id}/edit`) },
          { label: 'Delete', icon: <DeleteIcon fontSize="small" />, onClick: () => setDeleteId(id as number), divider: true },
        ]}
        onCreateNew={() => navigate('/orderLines/new')}
        editable
        processRowUpdate={async (newRow, oldRow) => { await updateMutation.mutateAsync({ id: (newRow as any).id as number, data: newRow as unknown as UpdateOrderLineRequest }); return newRow; }}
        onBulkEdit={async (ids, field, value) => {
          await Promise.all(ids.map((id) => updateMutation.mutateAsync({ id: id as number, data: { [field]: value } as unknown as UpdateOrderLineRequest })));
        }}
        bulkEditableFields={[
          { field: 'fkOrderHeaderId', label: 'Order Header ID', type: 'number' },
          { field: 'fkProductId', label: 'Product ID', type: 'number' },
          { field: 'quantity', label: 'Quantity', type: 'number' },
          { field: 'unitPrice', label: 'Unit Price', type: 'number' },
          { field: 'discountPercent', label: 'Discount Percent', type: 'number' },
          { field: 'lineNumber', label: 'Line Number', type: 'number' },
        ]}
        headerActions={
          <>
            <PermissionGate entity="orderLine" action="delete">
              {selectedIds.length > 0 && (
                <Button variant="outlined" color="error" onClick={() => setBulkDeleteConfirm(true)}>
                  Delete Selected ({selectedIds.length})
                </Button>
              )}
            </PermissionGate>
            <PermissionGate entity="orderLine" action="write">
              <Button variant="contained" onClick={() => navigate('/orderLines/new')}>
                Add New
              </Button>
              <Button variant="outlined" onClick={() => setQuickCreateOpen(true)}>
                Quick Create
              </Button>
            </PermissionGate>
          </>
        }
      />
      <Dialog open={quickCreateOpen} onClose={() => setQuickCreateOpen(false)} maxWidth="md" fullWidth>
        <DialogTitle>Quick Create Order Line</DialogTitle>
        <DialogContent>
          <OrderLineForm embedded onSuccess={() => setQuickCreateOpen(false)} />
        </DialogContent>
      </Dialog>
      <ConfirmDialog
        open={deleteId !== null}
        title="Delete Order Line"
        message="Are you sure you want to delete this order line? This action cannot be undone."
        confirmDisabled={deleteMutation.isPending}
        onConfirm={() => {
          if (deleteId !== null) {
            deleteMutation.mutate(deleteId);
          }
          setDeleteId(null);
        }}
        onCancel={() => setDeleteId(null)}
      />
      <ConfirmDialog
        open={bulkDeleteConfirm}
        title="Delete Multiple Order Lines"
        message={`Are you sure you want to delete ${selectedIds.length} order line(s)? This action cannot be undone.`}
        severity="error"
        onConfirm={async () => {
          try {
            await Promise.all(selectedIds.map((id) => deleteMutation.mutateAsync(id as number)));
          } catch { /* individual errors handled by mutation onError */ }
          setSelectedIds([]);
          setBulkDeleteConfirm(false);
        }}
        onCancel={() => setBulkDeleteConfirm(false)}
      />
    </Box>
  );
}

