// ProductForm.tsx
// Generated by CodeCreator
import { useEffect, useState, useCallback } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  TextField,
  Button,
  Box,
  Paper,
  Typography,
  FormControlLabel,
  Checkbox,
  CircularProgress,
  MenuItem,
  Divider,
  Autocomplete,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Alert,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Snackbar,
} from '@mui/material';
import { ExpandMore as ExpandMoreIcon } from '@mui/icons-material';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useProduct, useCreateProduct, useUpdateProduct } from '../hooks/useProduct';
import { productSchema, type ProductFormData } from '../types/Product';
import { PermissionGate } from '../contexts/AuthContext';
import { useEnumValues } from '../hooks/useEnumValues';

interface ProductFormProps {
  embedded?: boolean;
  onSuccess?: () => void;
}

export default function ProductForm({ embedded, onSuccess }: ProductFormProps = {}) {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const isEditMode = !embedded && Boolean(id);
  const [searchParams] = useSearchParams();
  const cloneFromId = searchParams.get('cloneFrom');

  const enmCategoryOptions = useEnumValues('Category');

  const parsedId = id ? Number(id) : 0;
  const { data: existingData, isLoading: isLoadingData } = useProduct(parsedId);
  const cloneParsedId = cloneFromId ? Number(cloneFromId) : 0;
  const { data: cloneSourceData } = useProduct(cloneParsedId);
  const createMutation = useCreateProduct();
  const updateMutation = useUpdateProduct();

  const {
    control,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting, isDirty },
  } = useForm<ProductFormData>({
    resolver: zodResolver(productSchema),
  });

  useEffect(() => {
    if (isEditMode && existingData) {
      reset({
        productCode: existingData.productCode,
        productName: existingData.productName,
        enmCategory: existingData.enmCategory ?? 0,
        unitOfMeasure: existingData.unitOfMeasure ?? '',
        notes: existingData.notes ?? '',
        baseCost: existingData.baseCost ?? 0,
      });
    }
  }, [isEditMode, existingData, reset]);

  useEffect(() => {
    if (!isEditMode && cloneFromId && cloneSourceData) {
      reset({
        productCode: '',  // Unique - must change before saving
        productName: cloneSourceData.productName,
        enmCategory: cloneSourceData.enmCategory ?? 0,
        unitOfMeasure: cloneSourceData.unitOfMeasure ?? '',
        notes: cloneSourceData.notes ?? '',
        baseCost: cloneSourceData.baseCost ?? 0,
      });
    }
  }, [cloneFromId, cloneSourceData, isEditMode, reset]);

  const [conflictData, setConflictData] = useState<Record<string,unknown> | null>(null);

  const onSubmit = async (formData: ProductFormData) => {
    try {
      if (isEditMode) {
        const payload = { ...formData, _etag: (existingData as unknown as Record<string,unknown>)?._etag } as Record<string,unknown>;
        await updateMutation.mutateAsync({ id: parsedId, data: payload as unknown as ProductFormData });
      } else {
        await createMutation.mutateAsync(formData);
      }
      localStorage.removeItem(draftKey); // Clear draft on successful save
      if (embedded && onSuccess) {
        onSuccess();
      } else {
        navigate('/products');
      }
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'name' in error && (error as Error).name === 'ConflictError') {
        setConflictData({ message: (error as Error).message });
        return;
      }
      const axiosErr = error as { response?: { status?: number; data?: Record<string,unknown> } };
      if (axiosErr.response?.status === 409) {
        setConflictData(axiosErr.response.data as Record<string,unknown>);
      } else {
        console.error('Failed to save product:', error);
      }
    }
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && (e.key === 'Enter' || e.key === 's')) {
        e.preventDefault();
        handleSubmit(onSubmit)();
      }
      if (e.key === 'Escape') {
        navigate('/products');
      }
    };
  
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }); // re-registers on every render to capture latest form state

  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isDirty && !isSubmitting) {
        e.preventDefault();
      }
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [isDirty, isSubmitting]);

  // Auto-save draft to localStorage every 30 seconds
  const draftKey = `draft_product_${isEditMode ? id : 'new'}`;
  const [hasDraft, setHasDraft] = useState(false);
  const [draftRestored, setDraftRestored] = useState(false);
  useEffect(() => {
    if (draftRestored) return;
    const saved = localStorage.getItem(draftKey);
    if (saved) setHasDraft(true);
  }, [draftKey, draftRestored]);
  useEffect(() => {
    if (!isDirty) return;
    const timer = setInterval(() => {
      const formValues = control._formValues;
      if (formValues) localStorage.setItem(draftKey, JSON.stringify(formValues));
    }, 30000);
    return () => clearInterval(timer);
  }, [isDirty, draftKey, control]);
  const restoreDraft = useCallback(() => {
    const saved = localStorage.getItem(draftKey);
    if (saved) { try { reset(JSON.parse(saved)); } catch {} }
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey, reset]);
  const discardDraft = useCallback(() => {
    localStorage.removeItem(draftKey);
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey]);

  // Warn on browser close/refresh when form is dirty
  useEffect(() => {
    const handler = (e: BeforeUnloadEvent) => { if (isDirty && !isSubmitting) { e.preventDefault(); } };
    window.addEventListener('beforeunload', handler);
    return () => window.removeEventListener('beforeunload', handler);
  }, [isDirty, isSubmitting]);

  if ((isEditMode && isLoadingData) || (cloneFromId && !cloneSourceData)) {
    return (
      <Box display="flex" justifyContent="center" p={4}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <PermissionGate entity="product" action="write">
    <Box sx={{ p: embedded ? 1 : 3, maxWidth: embedded ? '100%' : 800, mx: 'auto' }}>
      {/* Auto-save draft banner */}
      {hasDraft && !draftRestored && (
        <Alert severity="info" sx={{ mb: 2 }} action={
          <Box>
            <Button size="small" onClick={restoreDraft}>Restore</Button>
            <Button size="small" color="inherit" onClick={discardDraft}>Discard</Button>
          </Box>
        }>Unsaved draft found. Restore or discard?</Alert>
      )}
      {/* Navigation guard handled by beforeunload event */}
      {/* Concurrency conflict dialog */}
      <Dialog open={Boolean(conflictData)} onClose={() => setConflictData(null)} maxWidth="sm" fullWidth>
        <DialogTitle color="error">Conflict — Record Modified</DialogTitle>
        <DialogContent>
          <DialogContentText>
            <>{(conflictData as Record<string,unknown>)?.message ?? 'This record was modified by another user since you loaded it.'}{' '}Your changes were not saved. Please refresh and try again.</>
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setConflictData(null); window.location.reload(); }} variant="contained">Refresh &amp; Retry</Button>
        </DialogActions>
      </Dialog>
      {!embedded && (
        <Typography variant="h5" mb={3}>
          {isEditMode ? 'Edit Product' : cloneFromId ? 'Clone Product' : 'Add Product'}
        </Typography>
      )}
      {cloneFromId && (
        <Alert severity="warning" sx={{ mb: 2 }}>
          Cloning record — the following unique fields were cleared and <strong>must be filled with new values</strong> before saving:
          <br />• Product Code
        </Alert>
      )}
      <Paper sx={{ p: 3, elevation: embedded ? 0 : undefined }}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Box display="flex" flexDirection="column" gap={2}>
            <Controller
              name="productCode"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Product Code"
                  type="text"
                  fullWidth
                  autoFocus
                  required
                  error={Boolean(errors.productCode)}
                  helperText={errors.productCode?.message}
                />
              )}
            />
            <Controller
              name="productName"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Product Name"
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  required
                  error={Boolean(errors.productName)}
                  helperText={errors.productName?.message}
                />
              )}
            />
            <Controller
              name="enmCategory"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Category"
                  select
                  fullWidth
                  error={Boolean(errors.enmCategory)}
                  helperText={errors.enmCategory?.message}
                >
                  {enmCategoryOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="unitOfMeasure"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Unit Of Measure"
                  type="text"
                  fullWidth
                  error={Boolean(errors.unitOfMeasure)}
                  helperText={errors.unitOfMeasure?.message}
                />
              )}
            />
            <Controller
              name="notes"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Notes"
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.notes)}
                  helperText={errors.notes?.message}
                />
              )}
            />
            <Controller
              name="baseCost"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Base Cost"
                  type="number"
                  fullWidth
                  error={Boolean(errors.baseCost)}
                  helperText={errors.baseCost?.message}
                />
              )}
            />
            {isEditMode && existingData && (
              <>
                <Divider sx={{ my: 1 }} />
                <Typography variant="subtitle2" color="text.secondary">
                  Computed Fields
                </Typography>
                <TextField
                  label="Is Active"
                  value={existingData.isActive ? 'Yes' : 'No'}
                  disabled
                  fullWidth
                />
                <TextField
                  label="Current Stock"
                  value={existingData.currentStock ?? ''}
                  disabled
                  fullWidth
                />
              </>
            )}
            <Box display="flex" gap={2} mt={2}>
              <Button type="submit" variant="contained" disabled={isSubmitting}>
                {isSubmitting ? 'Saving...' : (isEditMode ? 'Update' : 'Create')}
              </Button>
              {!embedded && (
                <Button variant="outlined" onClick={() => navigate('/products')}>
                  Cancel
                </Button>
              )}
            </Box>
          </Box>
        </form>
      </Paper>
    </Box>
    </PermissionGate>
  );
}

