// ProductPriceHistForm.tsx
// Generated by CodeCreator
import { useEffect, useState, useCallback } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  TextField,
  Button,
  Box,
  Paper,
  Typography,
  FormControlLabel,
  Checkbox,
  CircularProgress,
  MenuItem,
  Divider,
  Autocomplete,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Alert,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Snackbar,
} from '@mui/material';
import { ExpandMore as ExpandMoreIcon } from '@mui/icons-material';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useProductPriceHist, useCreateProductPriceHist, useUpdateProductPriceHist } from '../hooks/useProductPriceHist';
import { productPriceHistSchema, type ProductPriceHistFormData } from '../types/ProductPriceHist';
import { PermissionGate } from '../contexts/AuthContext';
import { useEnumValues } from '../hooks/useEnumValues';

interface ProductPriceHistFormProps {
  embedded?: boolean;
  onSuccess?: () => void;
}

export default function ProductPriceHistForm({ embedded, onSuccess }: ProductPriceHistFormProps = {}) {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const isEditMode = !embedded && Boolean(id);
  const [searchParams] = useSearchParams();
  const cloneFromId = searchParams.get('cloneFrom');

  const enmCustomerTypeOptions = useEnumValues('CustomerType');

  const parsedId = id ? Number(id) : 0;
  const { data: existingData, isLoading: isLoadingData } = useProductPriceHist(parsedId);
  const cloneParsedId = cloneFromId ? Number(cloneFromId) : 0;
  const { data: cloneSourceData } = useProductPriceHist(cloneParsedId);
  const createMutation = useCreateProductPriceHist();
  const updateMutation = useUpdateProductPriceHist();

  const {
    control,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting, isDirty },
  } = useForm<ProductPriceHistFormData>({
    resolver: zodResolver(productPriceHistSchema),
  });

  useEffect(() => {
    if (isEditMode && existingData) {
      reset({
        productId: existingData.productId,
        enmCustomerType: existingData.enmCustomerType,
        baseCost: existingData.baseCost ?? 0,
        sellingPrice: existingData.sellingPrice,
        minQuantity: existingData.minQuantity ?? 0,
        discountPercent: existingData.discountPercent ?? 0,
        validFrom: existingData.validFrom,
        validTo: existingData.validTo,
        archivedDate: existingData.archivedDate ?? '',
        archivedReason: existingData.archivedReason ?? '',
        originalPriceId: existingData.originalPriceId ?? 0,
        notes: existingData.notes ?? '',
        addFieldsHere: existingData.addFieldsHere ?? '',
      });
    }
  }, [isEditMode, existingData, reset]);

  useEffect(() => {
    if (!isEditMode && cloneFromId && cloneSourceData) {
      reset({
        productId: cloneSourceData.productId,
        enmCustomerType: cloneSourceData.enmCustomerType,
        baseCost: cloneSourceData.baseCost ?? 0,
        sellingPrice: cloneSourceData.sellingPrice,
        minQuantity: cloneSourceData.minQuantity ?? 0,
        discountPercent: cloneSourceData.discountPercent ?? 0,
        validFrom: cloneSourceData.validFrom,
        validTo: cloneSourceData.validTo,
        archivedDate: cloneSourceData.archivedDate ?? '',
        archivedReason: cloneSourceData.archivedReason ?? '',
        originalPriceId: cloneSourceData.originalPriceId ?? 0,
        notes: cloneSourceData.notes ?? '',
        addFieldsHere: cloneSourceData.addFieldsHere ?? '',
      });
    }
  }, [cloneFromId, cloneSourceData, isEditMode, reset]);

  const [conflictData, setConflictData] = useState<Record<string,unknown> | null>(null);

  const onSubmit = async (formData: ProductPriceHistFormData) => {
    try {
      if (isEditMode) {
        const payload = { ...formData, _etag: (existingData as unknown as Record<string,unknown>)?._etag } as Record<string,unknown>;
        await updateMutation.mutateAsync({ id: parsedId, data: payload as unknown as ProductPriceHistFormData });
      } else {
        await createMutation.mutateAsync(formData);
      }
      localStorage.removeItem(draftKey); // Clear draft on successful save
      if (embedded && onSuccess) {
        onSuccess();
      } else {
        navigate('/productPriceHists');
      }
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'name' in error && (error as Error).name === 'ConflictError') {
        setConflictData({ message: (error as Error).message });
        return;
      }
      const axiosErr = error as { response?: { status?: number; data?: Record<string,unknown> } };
      if (axiosErr.response?.status === 409) {
        setConflictData(axiosErr.response.data as Record<string,unknown>);
      } else {
        console.error('Failed to save productPriceHist:', error);
      }
    }
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && (e.key === 'Enter' || e.key === 's')) {
        e.preventDefault();
        handleSubmit(onSubmit)();
      }
      if (e.key === 'Escape') {
        navigate('/productPriceHists');
      }
    };
  
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }); // re-registers on every render to capture latest form state

  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isDirty && !isSubmitting) {
        e.preventDefault();
      }
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [isDirty, isSubmitting]);

  // Auto-save draft to localStorage every 30 seconds
  const draftKey = `draft_productPriceHist_${isEditMode ? id : 'new'}`;
  const [hasDraft, setHasDraft] = useState(false);
  const [draftRestored, setDraftRestored] = useState(false);
  useEffect(() => {
    if (draftRestored) return;
    const saved = localStorage.getItem(draftKey);
    if (saved) setHasDraft(true);
  }, [draftKey, draftRestored]);
  useEffect(() => {
    if (!isDirty) return;
    const timer = setInterval(() => {
      const formValues = control._formValues;
      if (formValues) localStorage.setItem(draftKey, JSON.stringify(formValues));
    }, 30000);
    return () => clearInterval(timer);
  }, [isDirty, draftKey, control]);
  const restoreDraft = useCallback(() => {
    const saved = localStorage.getItem(draftKey);
    if (saved) { try { reset(JSON.parse(saved)); } catch {} }
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey, reset]);
  const discardDraft = useCallback(() => {
    localStorage.removeItem(draftKey);
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey]);

  // Warn on browser close/refresh when form is dirty
  useEffect(() => {
    const handler = (e: BeforeUnloadEvent) => { if (isDirty && !isSubmitting) { e.preventDefault(); } };
    window.addEventListener('beforeunload', handler);
    return () => window.removeEventListener('beforeunload', handler);
  }, [isDirty, isSubmitting]);

  if ((isEditMode && isLoadingData) || (cloneFromId && !cloneSourceData)) {
    return (
      <Box display="flex" justifyContent="center" p={4}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <PermissionGate entity="productPriceHist" action="write">
    <Box sx={{ p: embedded ? 1 : 3, maxWidth: embedded ? '100%' : 800, mx: 'auto' }}>
      {/* Auto-save draft banner */}
      {hasDraft && !draftRestored && (
        <Alert severity="info" sx={{ mb: 2 }} action={
          <Box>
            <Button size="small" onClick={restoreDraft}>Restore</Button>
            <Button size="small" color="inherit" onClick={discardDraft}>Discard</Button>
          </Box>
        }>Unsaved draft found. Restore or discard?</Alert>
      )}
      {/* Navigation guard handled by beforeunload event */}
      {/* Concurrency conflict dialog */}
      <Dialog open={Boolean(conflictData)} onClose={() => setConflictData(null)} maxWidth="sm" fullWidth>
        <DialogTitle color="error">Conflict — Record Modified</DialogTitle>
        <DialogContent>
          <DialogContentText>
            <>{(conflictData as Record<string,unknown>)?.message ?? 'This record was modified by another user since you loaded it.'}{' '}Your changes were not saved. Please refresh and try again.</>
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setConflictData(null); window.location.reload(); }} variant="contained">Refresh &amp; Retry</Button>
        </DialogActions>
      </Dialog>
      {!embedded && (
        <Typography variant="h5" mb={3}>
          {isEditMode ? 'Edit Product Price Hist' : cloneFromId ? 'Clone Product Price Hist' : 'Add Product Price Hist'}
        </Typography>
      )}
      <Paper sx={{ p: 3, elevation: embedded ? 0 : undefined }}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Box display="flex" flexDirection="column" gap={2}>
            <Controller
              name="productId"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Product ID"
                  type="number"
                  fullWidth
                  autoFocus
                  required
                  error={Boolean(errors.productId)}
                  helperText={errors.productId?.message}
                />
              )}
            />
            <Controller
              name="enmCustomerType"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Customer Type"
                  select
                  fullWidth
                  required
                  error={Boolean(errors.enmCustomerType)}
                  helperText={errors.enmCustomerType?.message}
                >
                  {enmCustomerTypeOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="baseCost"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Base Cost"
                  type="number"
                  fullWidth
                  error={Boolean(errors.baseCost)}
                  helperText={errors.baseCost?.message}
                />
              )}
            />
            <Controller
              name="sellingPrice"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Selling Price"
                  type="number"
                  fullWidth
                  required
                  error={Boolean(errors.sellingPrice)}
                  helperText={errors.sellingPrice?.message}
                />
              )}
            />
            <Controller
              name="minQuantity"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Min Quantity"
                  type="number"
                  fullWidth
                  error={Boolean(errors.minQuantity)}
                  helperText={errors.minQuantity?.message}
                />
              )}
            />
            <Controller
              name="discountPercent"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Discount Percent"
                  type="number"
                  fullWidth
                  error={Boolean(errors.discountPercent)}
                  helperText={errors.discountPercent?.message}
                />
              )}
            />
            <Controller
              name="validFrom"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 10); })()}
                  label="Valid From"
                  type="date"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  required
                  error={Boolean(errors.validFrom)}
                  helperText={errors.validFrom?.message}
                />
              )}
            />
            <Controller
              name="validTo"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 10); })()}
                  label="Valid To"
                  type="date"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  required
                  error={Boolean(errors.validTo)}
                  helperText={errors.validTo?.message}
                />
              )}
            />
            <Controller
              name="archivedDate"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 16); })()}
                  label="Archived Date"
                  type="datetime-local"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  error={Boolean(errors.archivedDate)}
                  helperText={errors.archivedDate?.message}
                />
              )}
            />
            <Controller
              name="archivedReason"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Archived Reason"
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.archivedReason)}
                  helperText={errors.archivedReason?.message}
                />
              )}
            />
            <Controller
              name="originalPriceId"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Original Price ID"
                  type="number"
                  fullWidth
                  error={Boolean(errors.originalPriceId)}
                  helperText={errors.originalPriceId?.message}
                />
              )}
            />
            <Controller
              name="notes"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Notes"
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.notes)}
                  helperText={errors.notes?.message}
                />
              )}
            />
            <Controller
              name="addFieldsHere"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Add Fields Here"
                  type="text"
                  fullWidth
                  error={Boolean(errors.addFieldsHere)}
                  helperText={errors.addFieldsHere?.message}
                />
              )}
            />
            <Box display="flex" gap={2} mt={2}>
              <Button type="submit" variant="contained" disabled={isSubmitting}>
                {isSubmitting ? 'Saving...' : (isEditMode ? 'Update' : 'Create')}
              </Button>
              {!embedded && (
                <Button variant="outlined" onClick={() => navigate('/productPriceHists')}>
                  Cancel
                </Button>
              )}
            </Box>
          </Box>
        </form>
      </Paper>
    </Box>
    </PermissionGate>
  );
}

