// ProductView.tsx
// Generated by CodeCreator
import { useState, useCallback } from 'react';
import {
  Box,
  Paper,
  Typography,
  Button,
  Skeleton,
  Chip,
  IconButton,
  Tooltip,
  Snackbar,
} from '@mui/material';
import Grid from '@mui/material/Grid2';
import PrintIcon from '@mui/icons-material/Print';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import { PermissionGate } from '../contexts/AuthContext';
import { fieldLabel } from '../i18n/fieldLabels';
import he from '../i18n/he';
import { useNavigate, useParams } from 'react-router-dom';
import { useProduct } from '../hooks/useProduct';
import { useEnumValues } from '../hooks/useEnumValues';
import { Tabs, Tab } from '@mui/material';
import { useQuery } from '@tanstack/react-query';
import AppDataGrid from '../components/shared/AppDataGrid';
import { type GridColDef } from '@mui/x-data-grid';
import { OrderLineApi } from '../api/OrderLineApi';
import { ProductPriceApi } from '../api/ProductPriceApi';
import { api } from '../api/client';

export default function ProductView() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const parsedId = id ? Number(id) : 0;
  const { data: entity, isLoading, isError } = useProduct(parsedId);
  const enmCategoryOptions = useEnumValues('Category');

  const [copiedField, setCopiedField] = useState('');
  const copyToClipboard = useCallback((value: unknown, fieldName: string) => {
    navigator.clipboard.writeText(String(value ?? '')).then(() => setCopiedField(fieldName));
  }, []);

  const [activeTab, setActiveTab] = useState(0);
  const { data: orderLineData } = useQuery({
    queryKey: ['orderLines', 'by-parent', parsedId],
    queryFn: () => OrderLineApi.getAll(0, 100, '', '', 'asc', { productId: parsedId }),
    enabled: Boolean(parsedId) && activeTab > 0,
  });
  const { data: productPriceData } = useQuery({
    queryKey: ['productPrices', 'by-parent', parsedId],
    queryFn: () => ProductPriceApi.getAll(0, 100, '', '', 'asc', { productId: parsedId }),
    enabled: Boolean(parsedId) && activeTab > 0,
  });
  const { data: auditData } = useQuery({
    queryKey: ['audit', 'Product', parsedId],
    queryFn: () => api.get(`/audit/Product/${parsedId}`).then((r) => r.data as { items: unknown[]; total: number }),
    enabled: Boolean(parsedId) && activeTab === 3,
  });

  if (isLoading) {
    return (
      <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
        <Skeleton variant="text" width={250} height={40} sx={{ mb: 3 }} />
        <Paper sx={{ p: 3 }}>
          <Grid container spacing={2}>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <Skeleton variant="text" width={80} height={20} />
              <Skeleton variant="text" width="100%" height={28} />
            </Grid>
          </Grid>
        </Paper>
      </Box>
    );
  }

  if (isError || !entity) {
    return (
      <Box p={4}>
        <Typography color="error">{he.messages.notFound}</Typography>
      </Box>
    );
  }

  return (
    <Box sx={{ p: 3, maxWidth: 800, mx: 'auto' }}>
      <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
        <Typography variant="h5">{he.actions.details}</Typography>
        <Box display="flex" gap={1}>
          <PermissionGate entity="product" action="write">
            <Button variant="contained" onClick={() => navigate(`/products/${entity.id}/edit`)}>
              {he.actions.edit}
            </Button>
          </PermissionGate>
          <PermissionGate entity="product" action="write">
            <Button variant="outlined" startIcon={<ContentCopyIcon />} onClick={() => navigate(`/products/new?cloneFrom=${entity.id}`)}>
              {he.actions.duplicate}
            </Button>
          </PermissionGate>
          <Button variant="outlined" onClick={() => navigate('/products')}>
            {he.actions.backToList}
          </Button>
          <Button variant="outlined" startIcon={<PrintIcon />} onClick={() => window.print()} className="no-print">
            {he.actions.print}
          </Button>
        </Box>
      </Box>
      <Paper sx={{ p: 3 }}>
        <Grid container spacing={2}>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('id') ?? 'ID'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy ID" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.id, 'ID')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.id}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('productCode') ?? 'Product Code'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Product Code" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.productCode, 'Product Code')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.productCode}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('productName') ?? 'Product Name'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Product Name" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.productName, 'Product Name')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.productName}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('enmCategory') ?? 'Category'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Category" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.enmCategory, 'Category')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {enmCategoryOptions.find((o) => o.value === entity.enmCategory)?.label || String(entity.enmCategory)}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('unitOfMeasure') ?? 'Unit Of Measure'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Unit Of Measure" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.unitOfMeasure, 'Unit Of Measure')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.unitOfMeasure ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('notes') ?? 'Notes'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Notes" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.notes, 'Notes')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.notes ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('isActive') ?? 'Is Active'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Is Active" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.isActive, 'Is Active')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Box>
              <Chip
                label={entity.isActive ? he.messages.yes : he.messages.no}
                color={entity.isActive ? 'success' : 'default'}
                size="small"
              />
            </Box>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('currentStock') ?? 'Current Stock'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Current Stock" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.currentStock, 'Current Stock')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.currentStock ?? '-'}
            </Typography>
          </Grid>
          <Grid size={{ xs: 12, sm: 6 }}>
            <Box display="flex" alignItems="center" gap={0.5}>
              <Typography variant="caption" color="text.secondary">
                {fieldLabel('baseCost') ?? 'Base Cost'}
              </Typography>
              <Tooltip title={he.actions.copy} className="no-print">
                <IconButton size="small" aria-label="Copy Base Cost" sx={{ p: 0, opacity: 0.4, '&:hover': { opacity: 1 } }} onClick={() => copyToClipboard(entity.baseCost, 'Base Cost')}>
                  <ContentCopyIcon sx={{ fontSize: 14 }} />
                </IconButton>
              </Tooltip>
            </Box>
            <Typography variant="body1">
              {entity.baseCost ?? '-'}
            </Typography>
          </Grid>
        </Grid>
      </Paper>

      <Box sx={{ mt: 3 }}>
        <Tabs value={activeTab} onChange={(_, v) => setActiveTab(v)} sx={{ borderBottom: 1, borderColor: 'divider' }}>
          <Tab label={he.actions.details} />
          <Tab label={he.entities.orderLine.p} />
          <Tab label={he.entities.productPrice.p} />
          <Tab label={he.grid.history} />
        </Tabs>
        {activeTab === 1 && (
          <Box sx={{ pt: 2 }}>
            <AppDataGrid
              title="Order Lines"
              rows={orderLineData?.items || []}
              columns={[
                { field: 'id', headerName: 'ID', width: 80 },
                { field: 'fkOrderHeaderId', headerName: 'Order Header ID', flex: 1, minWidth: 120 },
                { field: 'fkProductId', headerName: 'Product ID', flex: 1, minWidth: 120 },
                { field: 'quantity', headerName: 'Quantity', flex: 1, minWidth: 120 },
                { field: 'unitPrice', headerName: 'Unit Price', flex: 1, minWidth: 120 },
                { field: 'discountPercent', headerName: 'Discount Percent', flex: 1, minWidth: 120 },
              ] as GridColDef[]}
              loading={false}
              getRowId={(row) => (row as any).id as string | number}
              onRowClick={(childId) => navigate(`/orderLines/${childId}`)}
            />
          </Box>
        )}
        {activeTab === 2 && (
          <Box sx={{ pt: 2 }}>
            <AppDataGrid
              title="Product Prices"
              rows={productPriceData?.items || []}
              columns={[
                { field: 'id', headerName: 'ID', width: 80 },
                { field: 'fkProductId', headerName: 'Product ID', flex: 1, minWidth: 120 },
                { field: 'enmCustomerType', headerName: 'Customer Type', flex: 1, minWidth: 120 },
                { field: 'sellingPrice', headerName: 'Selling Price', flex: 1, minWidth: 120 },
                { field: 'minQuantity', headerName: 'Min Quantity', flex: 1, minWidth: 120 },
                { field: 'discountPercent', headerName: 'Discount Percent', flex: 1, minWidth: 120 },
              ] as GridColDef[]}
              loading={false}
              getRowId={(row) => (row as any).id as string | number}
              onRowClick={(childId) => navigate(`/productPrices/${childId}`)}
            />
          </Box>
        )}

        {/* History tab — fetches from c_AuditIndexed */}
        {activeTab === 3 && (
          <Box sx={{ pt: 2 }}>
            {auditData?.items ? (
              <Box>
                {(auditData.items as { id: number; fieldName: string; oldValue: string; newValue: string; changedByUser: string; occurredAt: string; operation: string }[]).map((a) => (
                  <Paper key={a.id} variant="outlined" sx={{ p: 1.5, mb: 1, display: 'flex', gap: 2, alignItems: 'center' }}>
                    <Typography variant="caption" color="text.secondary" sx={{ minWidth: 140 }}>
                      {new Date(a.occurredAt).toLocaleString()}
                    </Typography>
                    <Typography variant="body2" sx={{ fontWeight: 600 }}>{a.changedByUser}</Typography>
                    <Typography variant="body2">
                      {a.operation === 'Added' ? 'Created record' : `Changed ${a.fieldName}`}
                      {a.oldValue && a.newValue ? ` from "${a.oldValue}" to "${a.newValue}"` : a.newValue ? `: "${a.newValue}"` : ''}
                    </Typography>
                  </Paper>
                ))}
                {auditData.items.length === 0 && <Typography color="text.secondary">No history available</Typography>}
              </Box>
            ) : <Typography>Loading history...</Typography>}
          </Box>
        )}
      </Box>
      <Snackbar
        open={Boolean(copiedField)}
        autoHideDuration={2000}
        onClose={() => setCopiedField('')}
        message={`${copiedField} copied to clipboard`}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
      />
    </Box>
  );
}

