// ProductPriceHistList.tsx
// Generated by CodeCreator
import { useState, useCallback } from 'react';
import type { GridSortModel } from '@mui/x-data-grid';
import { type GridColDef, GridActionsCellItem } from '@mui/x-data-grid';
import { Box, Alert, Button, Dialog, DialogTitle, DialogContent } from '@mui/material';
import { Visibility as ViewIcon } from '@mui/icons-material';
import { ContentCopy as ContentCopyIcon } from '@mui/icons-material';
import { OpenInNew as OpenInNewIcon } from '@mui/icons-material';
import { Edit as EditIcon } from '@mui/icons-material';
import { Delete as DeleteIcon } from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import { useProductPriceHists, useUpdateProductPriceHist, useDeleteProductPriceHist } from '../hooks/useProductPriceHist';
import AppDataGrid from '../components/shared/AppDataGrid';
import ConfirmDialog from '../components/shared/ConfirmDialog';
import { useEnumValues } from '../hooks/useEnumValues';
import { useNotification } from '../contexts/NotificationContext';
import { PermissionGate } from '../contexts/AuthContext';
import ProductPriceHistForm from './ProductPriceHistForm';
import type { UpdateProductPriceHistRequest } from '../types/ProductPriceHist';
import FilterBuilder from '../components/shared/FilterBuilder';
import FilterListIcon from '@mui/icons-material/FilterList';
import { Collapse } from '@mui/material';

export default function ProductPriceHistList() {
  const [paginationModel, setPaginationModel] = useState({ page: 0, pageSize: 25 });
  const [search, setSearch] = useState('');
  const [sortModel, setSortModel] = useState<GridSortModel>([]);
  const [showFilters, setShowFilters] = useState(false);
  const [activeFilters, setActiveFilters] = useState<Record<string, unknown>>({});
  const sortField = sortModel[0]?.field ?? '';
  const sortDir = sortModel[0]?.sort ?? 'asc';
  const handleSortModelChange = useCallback((model: GridSortModel) => {
    setSortModel(model);
    setPaginationModel((prev) => ({ ...prev, page: 0 }));
  }, []);
  const { data, isLoading, isError, error } = useProductPriceHists(paginationModel.page, paginationModel.pageSize, search, sortField, sortDir);
  const deleteMutation = useDeleteProductPriceHist();
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const [selectedIds, setSelectedIds] = useState<(string | number)[]>([]);
  const [bulkDeleteConfirm, setBulkDeleteConfirm] = useState(false);
  const navigate = useNavigate();
  const { showSuccess } = useNotification();
  const updateMutation = useUpdateProductPriceHist();
  const [quickCreateOpen, setQuickCreateOpen] = useState(false);
  const enmCustomerTypeOptions = useEnumValues('CustomerType');

  const columns: GridColDef[] = [
    { field: 'id', headerName: 'ID', width: 80, type: 'number' },
    { field: 'productId', headerName: 'Product ID', width: 120 },
    {
      field: 'enmCustomerType',
      headerName: 'Customer Type',
      width: 150,
      valueFormatter: (value) => {
        const opt = enmCustomerTypeOptions.find((o) => o.value === value);
        return opt ? opt.label : String(value ?? '');
      },
    },
    { field: 'baseCost', headerName: 'Base Cost', width: 130 },
    { field: 'sellingPrice', headerName: 'Selling Price', width: 130 },
    { field: 'minQuantity', headerName: 'Min Quantity', width: 120 },
    { field: 'discountPercent', headerName: 'Discount Percent', width: 130 },
    {
      field: 'validFrom',
      headerName: 'Valid From',
      width: 130,
      valueFormatter: (value) => value ? new Date(value as string).toLocaleDateString() : '',
    },
    {
      field: 'validTo',
      headerName: 'Valid To',
      width: 130,
      valueFormatter: (value) => value ? new Date(value as string).toLocaleDateString() : '',
    },
    {
      field: 'archivedDate',
      headerName: 'Archived Date',
      width: 130,
      valueFormatter: (value) => value ? new Date(value as string).toLocaleDateString() : '',
    },
    { field: 'archivedReason', headerName: 'Archived Reason', flex: 1, minWidth: 150 },
    { field: 'originalPriceId', headerName: 'Original Price ID', width: 120 },
    { field: 'notes', headerName: 'Notes', flex: 1, minWidth: 150 },
    { field: 'addFieldsHere', headerName: 'Add Fields Here', flex: 1, minWidth: 150 },
    {
      field: 'actions',
      type: 'actions',
      headerName: 'Actions',
      width: 140,
      getActions: (params) => [
        <GridActionsCellItem
          key="view"
          icon={<ViewIcon />}
          label="View"
          onClick={() => navigate(`/productPriceHists/${params.id}`)}
        />,
        <GridActionsCellItem
          key="edit"
          icon={<EditIcon />}
          label="Edit"
          onClick={() => navigate(`/productPriceHists/${params.id}/edit`)}
        />,
        <GridActionsCellItem
          key="delete"
          icon={<DeleteIcon />}
          label="Delete"
          onClick={() => setDeleteId(params.id as number)}
        />,
      ],
    },
  ];

  if (isError) {
    return (
      <Box sx={{ p: 3 }}>
        <Alert severity="error" sx={{ mb: 2 }}>
          Failed to load product price hists: {(error as Error)?.message || 'Unknown error'}
        </Alert>
      </Box>
    );
  }

  const filterFields = [
    { field: 'productId', label: 'Product ID', type: 'number' as const },
    { field: 'enmCustomerType', label: 'Customer Type', type: 'string' as const },
    { field: 'baseCost', label: 'Base Cost', type: 'number' as const },
    { field: 'sellingPrice', label: 'Selling Price', type: 'number' as const },
    { field: 'minQuantity', label: 'Min Quantity', type: 'number' as const },
    { field: 'discountPercent', label: 'Discount Percent', type: 'number' as const },
    { field: 'validFrom', label: 'Valid From', type: 'date' as const },
    { field: 'validTo', label: 'Valid To', type: 'date' as const },
    { field: 'archivedDate', label: 'Archived Date', type: 'date' as const },
    { field: 'archivedReason', label: 'Archived Reason', type: 'string' as const },
    { field: 'originalPriceId', label: 'Original Price ID', type: 'number' as const },
    { field: 'notes', label: 'Notes', type: 'string' as const },
    { field: 'addFieldsHere', label: 'Add Fields Here', type: 'string' as const },
  ];

  return (
    <Box sx={{ p: 3 }}>
      <Box display="flex" justifyContent="flex-end" mb={1}>
        <Button size="small" startIcon={<FilterListIcon />} onClick={() => setShowFilters((p) => !p)} color={Object.keys(activeFilters).length > 0 ? 'primary' : 'inherit'}>
          {showFilters ? 'Hide Filters' : `Filters${Object.keys(activeFilters).length > 0 ? ` (${Object.keys(activeFilters).length})` : ''}`}
        </Button>
      </Box>
      <Collapse in={showFilters}>
        <FilterBuilder fields={filterFields} onApply={(f) => { setActiveFilters(f as Record<string, unknown>); setPaginationModel((p) => ({ ...p, page: 0 })); }} onClear={() => setActiveFilters({})} />
      </Collapse>
      <AppDataGrid
        entityName="productPriceHist"
        title="Product Price Hist List"
        rows={data?.items || []}
        columns={columns}
        loading={isLoading}
        getRowId={(row) => (row as any).id as string | number}
        rowCount={data?.total || 0}
        paginationModel={paginationModel}
        onPaginationModelChange={setPaginationModel}
        serverSearch={search}
        onServerSearchChange={setSearch}
        sortModel={sortModel}
        onSortModelChange={handleSortModelChange}
        onRowClick={(id) => navigate(`/productPriceHists/${id}`)}
        checkboxSelection
        onSelectionChange={(ids) => setSelectedIds(ids)}
        onContextMenuActions={(id, row) => [
          { label: 'Open', icon: <OpenInNewIcon fontSize="small" />, onClick: () => navigate(`/productPriceHists/${id}`) },
          { label: 'Copy ID', icon: <ContentCopyIcon fontSize="small" />, onClick: () => { navigator.clipboard.writeText(String(id)); showSuccess('ID copied'); } },
          { label: 'Copy Row', icon: <ContentCopyIcon fontSize="small" />, onClick: () => { navigator.clipboard.writeText(JSON.stringify(row, null, 2)); showSuccess('Row copied'); } },
          { label: 'Duplicate', icon: <ContentCopyIcon fontSize="small" />, onClick: () => navigate(`/productPriceHists/new?cloneFrom=${id}`), divider: true },
          { label: 'Edit', icon: <EditIcon fontSize="small" />, onClick: () => navigate(`/productPriceHists/${id}/edit`) },
          { label: 'Delete', icon: <DeleteIcon fontSize="small" />, onClick: () => setDeleteId(id as number), divider: true },
        ]}
        onCreateNew={() => navigate('/productPriceHists/new')}
        editable
        processRowUpdate={async (newRow, oldRow) => { await updateMutation.mutateAsync({ id: (newRow as any).id as number, data: newRow as unknown as UpdateProductPriceHistRequest }); return newRow; }}
        onBulkEdit={async (ids, field, value) => {
          await Promise.all(ids.map((id) => updateMutation.mutateAsync({ id: id as number, data: { [field]: value } as unknown as UpdateProductPriceHistRequest })));
        }}
        bulkEditableFields={[
          { field: 'productId', label: 'Product ID', type: 'number' },
          { field: 'enmCustomerType', label: 'Customer Type', type: 'select' },
          { field: 'baseCost', label: 'Base Cost', type: 'number' },
          { field: 'sellingPrice', label: 'Selling Price', type: 'number' },
          { field: 'minQuantity', label: 'Min Quantity', type: 'number' },
          { field: 'discountPercent', label: 'Discount Percent', type: 'number' },
          { field: 'validFrom', label: 'Valid From', type: 'date' },
          { field: 'validTo', label: 'Valid To', type: 'date' },
          { field: 'archivedDate', label: 'Archived Date', type: 'date' },
          { field: 'archivedReason', label: 'Archived Reason', type: 'string' },
          { field: 'originalPriceId', label: 'Original Price ID', type: 'number' },
          { field: 'notes', label: 'Notes', type: 'string' },
          { field: 'addFieldsHere', label: 'Add Fields Here', type: 'string' },
        ]}
        headerActions={
          <>
            <PermissionGate entity="productPriceHist" action="delete">
              {selectedIds.length > 0 && (
                <Button variant="outlined" color="error" onClick={() => setBulkDeleteConfirm(true)}>
                  Delete Selected ({selectedIds.length})
                </Button>
              )}
            </PermissionGate>
            <PermissionGate entity="productPriceHist" action="write">
              <Button variant="contained" onClick={() => navigate('/productPriceHists/new')}>
                Add New
              </Button>
              <Button variant="outlined" onClick={() => setQuickCreateOpen(true)}>
                Quick Create
              </Button>
            </PermissionGate>
          </>
        }
      />
      <Dialog open={quickCreateOpen} onClose={() => setQuickCreateOpen(false)} maxWidth="md" fullWidth>
        <DialogTitle>Quick Create Product Price Hist</DialogTitle>
        <DialogContent>
          <ProductPriceHistForm embedded onSuccess={() => setQuickCreateOpen(false)} />
        </DialogContent>
      </Dialog>
      <ConfirmDialog
        open={deleteId !== null}
        title="Delete Product Price Hist"
        message="Are you sure you want to delete this product price hist? This action cannot be undone."
        confirmDisabled={deleteMutation.isPending}
        onConfirm={() => {
          if (deleteId !== null) {
            deleteMutation.mutate(deleteId);
          }
          setDeleteId(null);
        }}
        onCancel={() => setDeleteId(null)}
      />
      <ConfirmDialog
        open={bulkDeleteConfirm}
        title="Delete Multiple Product Price Hists"
        message={`Are you sure you want to delete ${selectedIds.length} product price hist(s)? This action cannot be undone.`}
        severity="error"
        onConfirm={async () => {
          try {
            await Promise.all(selectedIds.map((id) => deleteMutation.mutateAsync(id as number)));
          } catch { /* individual errors handled by mutation onError */ }
          setSelectedIds([]);
          setBulkDeleteConfirm(false);
        }}
        onCancel={() => setBulkDeleteConfirm(false)}
      />
    </Box>
  );
}

