// SupplierOrderForm.tsx
// Generated by CodeCreator
import { useEffect, useState, useCallback } from 'react';
import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import {
  TextField,
  Button,
  Box,
  Paper,
  Typography,
  FormControlLabel,
  Checkbox,
  CircularProgress,
  MenuItem,
  Divider,
  Autocomplete,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Alert,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogContentText,
  DialogActions,
  Snackbar,
} from '@mui/material';
import { ExpandMore as ExpandMoreIcon } from '@mui/icons-material';
import SendIcon from '@mui/icons-material/Send';
import ContentCopyIcon from '@mui/icons-material/ContentCopy';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useSupplierOrder, useCreateSupplierOrder, useUpdateSupplierOrder } from '../hooks/useSupplierOrder';
import { supplierOrderSchema, type SupplierOrderFormData } from '../types/SupplierOrder';
import { PermissionGate } from '../contexts/AuthContext';
import { useEnumValues } from '../hooks/useEnumValues';
import { useNotification } from '../contexts/NotificationContext';
import { useQuery } from '@tanstack/react-query';
import { OrderHeaderApi } from '../api/OrderHeaderApi';
import { SupplierOrderApi } from '../api/SupplierOrderApi';

interface SupplierOrderFormProps {
  embedded?: boolean;
  onSuccess?: () => void;
}

export default function SupplierOrderForm({ embedded, onSuccess }: SupplierOrderFormProps = {}) {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const isEditMode = !embedded && Boolean(id);
  const [searchParams] = useSearchParams();
  const cloneFromId = searchParams.get('cloneFrom');

  const enmEmailStatusOptions = useEnumValues('EmailStatus');
  const enmDeliveryMethodOptions = useEnumValues('DeliveryMethod');

  const { data: orderHeaderData } = useQuery({
    queryKey: ['orderHeaders', 'all'],
    queryFn: () => OrderHeaderApi.getAll(0, 9999, ''),
    staleTime: 5 * 60 * 1000,
  });

  const parsedId = id ? Number(id) : 0;
  const { data: existingData, isLoading: isLoadingData } = useSupplierOrder(parsedId);
  const cloneParsedId = cloneFromId ? Number(cloneFromId) : 0;
  const { data: cloneSourceData } = useSupplierOrder(cloneParsedId);
  const createMutation = useCreateSupplierOrder();
  const updateMutation = useUpdateSupplierOrder();

  const {
    control,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting, isDirty },
  } = useForm<SupplierOrderFormData>({
    resolver: zodResolver(supplierOrderSchema),
  });

  useEffect(() => {
    if (isEditMode && existingData) {
      reset({
        fkOrderHeaderId: existingData.fkOrderHeaderId,
        supplierEmail: existingData.supplierEmail ?? '',
        emailSubject: existingData.emailSubject ?? '',
        emailBody: existingData.emailBody ?? '',
        enmEmailStatus: existingData.enmEmailStatus,
        sentDate: existingData.sentDate ?? '',
        enmDeliveryMethod: existingData.enmDeliveryMethod ?? 0,
        requestedDeliveryDate: existingData.requestedDeliveryDate ?? '',
        requestedDeliveryDay: existingData.requestedDeliveryDay ?? '',
        notes: existingData.notes ?? '',
      });
    }
  }, [isEditMode, existingData, reset]);

  useEffect(() => {
    if (!isEditMode && cloneFromId && cloneSourceData) {
      reset({
        fkOrderHeaderId: cloneSourceData.fkOrderHeaderId,
        supplierEmail: cloneSourceData.supplierEmail ?? '',
        emailSubject: cloneSourceData.emailSubject ?? '',
        emailBody: cloneSourceData.emailBody ?? '',
        enmEmailStatus: cloneSourceData.enmEmailStatus,
        sentDate: cloneSourceData.sentDate ?? '',
        enmDeliveryMethod: cloneSourceData.enmDeliveryMethod ?? 0,
        requestedDeliveryDate: cloneSourceData.requestedDeliveryDate ?? '',
        requestedDeliveryDay: cloneSourceData.requestedDeliveryDay ?? '',
        notes: cloneSourceData.notes ?? '',
      });
    }
  }, [cloneFromId, cloneSourceData, isEditMode, reset]);

  const [conflictData, setConflictData] = useState<Record<string,unknown> | null>(null);

  // ── Send to supplier (POST /api/supplierOrders/{id}/send) ──
  const { showSuccess, showError, showInfo } = useNotification();
  const [sending, setSending] = useState(false);
  const [sendFallback, setSendFallback] = useState<{ subject?: string; body?: string; message: string } | null>(null);

  const handleSendToSupplier = async () => {
    if (!parsedId) return;
    setSending(true);
    try {
      const result = await SupplierOrderApi.send(parsedId);
      if (result.sent) {
        showSuccess(result.message || 'המייל נשלח לספק בהצלחה');
      } else if (result.body) {
        // Sending failed/unavailable but the server composed the email — let the user copy it
        setSendFallback({ subject: result.subject, body: result.body, message: result.message });
      } else {
        showError(result.message || 'שליחת המייל לספק נכשלה');
      }
    } catch (err: unknown) {
      showError((err as Error)?.message || 'שליחת המייל לספק נכשלה');
    } finally {
      setSending(false);
    }
  };

  const handleCopyEmail = async () => {
    if (!sendFallback) return;
    const text = `${sendFallback.subject ?? ''}\n\n${sendFallback.body ?? ''}`.trim();
    try {
      await navigator.clipboard.writeText(text);
      showInfo('תוכן המייל הועתק ללוח');
    } catch {
      showError('העתקה ללוח נכשלה');
    }
  };

  const onSubmit = async (formData: SupplierOrderFormData) => {
    try {
      if (isEditMode) {
        const payload = { ...formData, _etag: (existingData as unknown as Record<string,unknown>)?._etag } as Record<string,unknown>;
        await updateMutation.mutateAsync({ id: parsedId, data: payload as unknown as SupplierOrderFormData });
      } else {
        await createMutation.mutateAsync(formData);
      }
      localStorage.removeItem(draftKey); // Clear draft on successful save
      if (embedded && onSuccess) {
        onSuccess();
      } else {
        navigate('/supplierOrders');
      }
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'name' in error && (error as Error).name === 'ConflictError') {
        setConflictData({ message: (error as Error).message });
        return;
      }
      const axiosErr = error as { response?: { status?: number; data?: Record<string,unknown> } };
      if (axiosErr.response?.status === 409) {
        setConflictData(axiosErr.response.data as Record<string,unknown>);
      } else {
        console.error('Failed to save supplierOrder:', error);
      }
    }
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && (e.key === 'Enter' || e.key === 's')) {
        e.preventDefault();
        handleSubmit(onSubmit)();
      }
      // Note: the window-level Escape-navigates-away handler was removed —
      // it hijacked Escape from dialogs/autocompletes and discarded user edits.
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }); // re-registers on every render to capture latest form state

  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (isDirty && !isSubmitting) {
        e.preventDefault();
      }
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [isDirty, isSubmitting]);

  // Auto-save draft to localStorage every 30 seconds
  const draftKey = `draft_supplierOrder_${isEditMode ? id : 'new'}`;
  const [hasDraft, setHasDraft] = useState(false);
  const [draftRestored, setDraftRestored] = useState(false);
  useEffect(() => {
    if (draftRestored) return;
    const saved = localStorage.getItem(draftKey);
    if (saved) setHasDraft(true);
  }, [draftKey, draftRestored]);
  useEffect(() => {
    if (!isDirty) return;
    const timer = setInterval(() => {
      const formValues = control._formValues;
      if (formValues) localStorage.setItem(draftKey, JSON.stringify(formValues));
    }, 30000);
    return () => clearInterval(timer);
  }, [isDirty, draftKey, control]);
  const restoreDraft = useCallback(() => {
    const saved = localStorage.getItem(draftKey);
    if (saved) { try { reset(JSON.parse(saved)); } catch {} }
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey, reset]);
  const discardDraft = useCallback(() => {
    localStorage.removeItem(draftKey);
    setHasDraft(false); setDraftRestored(true);
  }, [draftKey]);

  // Warn on browser close/refresh when form is dirty
  useEffect(() => {
    const handler = (e: BeforeUnloadEvent) => { if (isDirty && !isSubmitting) { e.preventDefault(); } };
    window.addEventListener('beforeunload', handler);
    return () => window.removeEventListener('beforeunload', handler);
  }, [isDirty, isSubmitting]);

  if ((isEditMode && isLoadingData) || (cloneFromId && !cloneSourceData)) {
    return (
      <Box display="flex" justifyContent="center" p={4}>
        <CircularProgress />
      </Box>
    );
  }

  return (
    <PermissionGate entity="supplierOrder" action="write">
    <Box sx={{ p: embedded ? 1 : 3, maxWidth: embedded ? '100%' : 800, mx: 'auto' }}>
      {/* Auto-save draft banner */}
      {hasDraft && !draftRestored && (
        <Alert severity="info" sx={{ mb: 2 }} action={
          <Box>
            <Button size="small" onClick={restoreDraft}>Restore</Button>
            <Button size="small" color="inherit" onClick={discardDraft}>Discard</Button>
          </Box>
        }>Unsaved draft found. Restore or discard?</Alert>
      )}
      {/* Send-to-supplier fallback dialog: sending failed but the email was composed */}
      <Dialog open={Boolean(sendFallback)} onClose={() => setSendFallback(null)} maxWidth="sm" fullWidth>
        <DialogTitle>שליחה לספק לא בוצעה</DialogTitle>
        <DialogContent>
          <Alert severity="warning" sx={{ mb: 2 }}>{sendFallback?.message || 'המייל לא נשלח אוטומטית. ניתן להעתיק את התוכן ולשלוח ידנית.'}</Alert>
          {sendFallback?.subject && (
            <TextField
              label="נושא"
              value={sendFallback.subject}
              fullWidth
              sx={{ mb: 2 }}
              slotProps={{ input: { readOnly: true } }}
            />
          )}
          <TextField
            label="תוכן המייל"
            value={sendFallback?.body ?? ''}
            fullWidth
            multiline
            rows={8}
            slotProps={{ input: { readOnly: true } }}
          />
        </DialogContent>
        <DialogActions>
          <Button startIcon={<ContentCopyIcon />} onClick={handleCopyEmail}>העתק ללוח</Button>
          <Button variant="contained" onClick={() => setSendFallback(null)}>סגור</Button>
        </DialogActions>
      </Dialog>
      {/* Navigation guard handled by beforeunload event */}
      {/* Concurrency conflict dialog */}
      <Dialog open={Boolean(conflictData)} onClose={() => setConflictData(null)} maxWidth="sm" fullWidth>
        <DialogTitle color="error">Conflict — Record Modified</DialogTitle>
        <DialogContent>
          <DialogContentText>
            <>{(conflictData as Record<string,unknown>)?.message ?? 'This record was modified by another user since you loaded it.'}{' '}Your changes were not saved. Please refresh and try again.</>
          </DialogContentText>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setConflictData(null); window.location.reload(); }} variant="contained">Refresh &amp; Retry</Button>
        </DialogActions>
      </Dialog>
      {!embedded && (
        <Typography variant="h5" mb={3}>
          {isEditMode ? 'Edit Supplier Order' : cloneFromId ? 'Clone Supplier Order' : 'Add Supplier Order'}
        </Typography>
      )}
      <Paper sx={{ p: 3, elevation: embedded ? 0 : undefined }}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Box display="flex" flexDirection="column" gap={2}>
            <Controller
              name="fkOrderHeaderId"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <Autocomplete
                  options={orderHeaderData?.items || []}
                  getOptionLabel={(option) => `${(option as any).id} - ${(option as any).invoiceNumber || ''}`}
                  value={(orderHeaderData?.items || []).find((i: any) => i.id === field.value) || null}
                  onChange={(_, newValue) => field.onChange(newValue ? (newValue as any).id : 0)}
                  isOptionEqualToValue={(option, value) => (option as any).id === (value as any)?.id}
                  renderInput={(params) => (
                    <TextField
                      {...params}
                      label="Order Header ID"
                      title="Order Header"
                      autoFocus
                      required
                      error={Boolean(errors.fkOrderHeaderId)}
                      helperText={errors.fkOrderHeaderId?.message}
                    />
                  )}
                />
              )}
            />
            <Controller
              name="supplierEmail"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Supplier Email"
                  type="email"
                  fullWidth
                  error={Boolean(errors.supplierEmail)}
                  helperText={errors.supplierEmail?.message}
                />
              )}
            />
            <Controller
              name="emailSubject"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Email Subject"
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.emailSubject)}
                  helperText={errors.emailSubject?.message}
                />
              )}
            />
            <Controller
              name="emailBody"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Email Body"
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.emailBody)}
                  helperText={errors.emailBody?.message}
                />
              )}
            />
            <Controller
              name="enmEmailStatus"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Email Status"
                  select
                  fullWidth
                  required
                  error={Boolean(errors.enmEmailStatus)}
                  helperText={errors.enmEmailStatus?.message}
                >
                  {enmEmailStatusOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="sentDate"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 16); })()}
                  label="Sent Date"
                  type="datetime-local"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  error={Boolean(errors.sentDate)}
                  helperText={errors.sentDate?.message}
                />
              )}
            />
            <Controller
              name="enmDeliveryMethod"
              control={control}
              defaultValue={0}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Delivery Method"
                  select
                  fullWidth
                  error={Boolean(errors.enmDeliveryMethod)}
                  helperText={errors.enmDeliveryMethod?.message}
                >
                  {enmDeliveryMethodOptions.map((opt) => (
                    <MenuItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </MenuItem>
                  ))}
                </TextField>
              )}
            />
            <Controller
              name="requestedDeliveryDate"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  value={(() => { const v = String(field.value ?? ''); return (!v || v < '1900') ? '' : v.substring(0, 10); })()}
                  label="Requested Delivery Date"
                  type="date"
                  slotProps={{ inputLabel: { shrink: true } }}
                  fullWidth
                  error={Boolean(errors.requestedDeliveryDate)}
                  helperText={errors.requestedDeliveryDate?.message}
                />
              )}
            />
            <Controller
              name="requestedDeliveryDay"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Requested Delivery Day"
                  type="text"
                  fullWidth
                  error={Boolean(errors.requestedDeliveryDay)}
                  helperText={errors.requestedDeliveryDay?.message}
                />
              )}
            />
            <Controller
              name="notes"
              control={control}
              defaultValue={''}
              render={({ field }) => (
                <TextField
                  {...field}
                  label="Notes"
                  type="textarea"
                  multiline
                  rows={4}
                  fullWidth
                  error={Boolean(errors.notes)}
                  helperText={errors.notes?.message}
                />
              )}
            />
            {isEditMode && existingData && (
              <>
                <Divider sx={{ my: 1 }} />
                <Typography variant="subtitle2" color="text.secondary">
                  Computed Fields
                </Typography>
                <TextField
                  label="Total Cost"
                  value={existingData.totalCost ?? ''}
                  disabled
                  fullWidth
                />
              </>
            )}
            <Box display="flex" gap={2} mt={2}>
              <Button type="submit" variant="contained" disabled={isSubmitting}>
                {isSubmitting ? 'Saving...' : (isEditMode ? 'Update' : 'Create')}
              </Button>
              {isEditMode && existingData && (
                <Button
                  variant="outlined"
                  color="success"
                  startIcon={<SendIcon />}
                  onClick={handleSendToSupplier}
                  disabled={sending || isSubmitting}
                >
                  {sending ? 'שולח...' : 'שלח לספק'}
                </Button>
              )}
              {!embedded && (
                <Button variant="outlined" onClick={() => navigate('/supplierOrders')}>
                  Cancel
                </Button>
              )}
            </Box>
          </Box>
        </form>
      </Paper>
    </Box>
    </PermissionGate>
  );
}

