// SupplierOrderList.tsx
// Generated by CodeCreator
import { useState, useCallback } from 'react';
import type { GridSortModel } from '@mui/x-data-grid';
import { type GridColDef, GridActionsCellItem } from '@mui/x-data-grid';
import { Box, Alert, Button, Dialog, DialogTitle, DialogContent } from '@mui/material';
import { Visibility as ViewIcon } from '@mui/icons-material';
import { ContentCopy as ContentCopyIcon } from '@mui/icons-material';
import { OpenInNew as OpenInNewIcon } from '@mui/icons-material';
import { Edit as EditIcon } from '@mui/icons-material';
import { Delete as DeleteIcon } from '@mui/icons-material';
import { useNavigate, Link } from 'react-router-dom';
import { useSupplierOrders, useUpdateSupplierOrder, useDeleteSupplierOrder } from '../hooks/useSupplierOrder';
import AppDataGrid from '../components/shared/AppDataGrid';
import ConfirmDialog from '../components/shared/ConfirmDialog';
import { useEnumValues } from '../hooks/useEnumValues';
import { useNotification } from '../contexts/NotificationContext';
import { PermissionGate } from '../contexts/AuthContext';
import SupplierOrderForm from './SupplierOrderForm';
import type { UpdateSupplierOrderRequest } from '../types/SupplierOrder';
import FilterBuilder from '../components/shared/FilterBuilder';
import FilterListIcon from '@mui/icons-material/FilterList';
import { Collapse } from '@mui/material';

export default function SupplierOrderList() {
  const [paginationModel, setPaginationModel] = useState({ page: 0, pageSize: 25 });
  const [search, setSearch] = useState('');
  const [sortModel, setSortModel] = useState<GridSortModel>([]);
  const [showFilters, setShowFilters] = useState(false);
  const [activeFilters, setActiveFilters] = useState<Record<string, unknown>>({});
  const sortField = sortModel[0]?.field ?? '';
  const sortDir = sortModel[0]?.sort ?? 'asc';
  const handleSortModelChange = useCallback((model: GridSortModel) => {
    setSortModel(model);
    setPaginationModel((prev) => ({ ...prev, page: 0 }));
  }, []);
  const { data, isLoading, isError, error } = useSupplierOrders(paginationModel.page, paginationModel.pageSize, search, sortField, sortDir);
  const deleteMutation = useDeleteSupplierOrder();
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const [selectedIds, setSelectedIds] = useState<(string | number)[]>([]);
  const [bulkDeleteConfirm, setBulkDeleteConfirm] = useState(false);
  const navigate = useNavigate();
  const { showSuccess } = useNotification();
  const updateMutation = useUpdateSupplierOrder();
  const [quickCreateOpen, setQuickCreateOpen] = useState(false);
  const enmEmailStatusOptions = useEnumValues('EmailStatus');
  const enmDeliveryMethodOptions = useEnumValues('DeliveryMethod');

  const columns: GridColDef[] = [
    { field: 'id', headerName: 'ID', width: 80, type: 'number' },
    {
      field: 'fkOrderHeaderId',
      headerName: 'Order Header ID',
      width: 120,
      renderCell: (params) => params.value ? (
        <Link to={`/orderHeaders/${params.value}`} style={{ color: 'inherit', textDecoration: 'underline' }}  onClick={(e) => e.stopPropagation()}>
          {params.value}
        </Link>
      ) : '',
    },
    { field: 'supplierEmail', headerName: 'Supplier Email', flex: 1, minWidth: 150 },
    { field: 'emailSubject', headerName: 'Email Subject', flex: 1, minWidth: 150 },
    { field: 'emailBody', headerName: 'Email Body', flex: 1, minWidth: 150 },
    {
      field: 'enmEmailStatus',
      headerName: 'Email Status',
      width: 150,
      valueFormatter: (value) => {
        const opt = enmEmailStatusOptions.find((o) => o.value === value);
        return opt ? opt.label : String(value ?? '');
      },
    },
    {
      field: 'sentDate',
      headerName: 'Sent Date',
      width: 130,
      valueFormatter: (value) => value ? new Date(value as string).toLocaleDateString() : '',
    },
    { field: 'totalCost', headerName: 'Total Cost', width: 130 },
    {
      field: 'enmDeliveryMethod',
      headerName: 'Delivery Method',
      width: 150,
      valueFormatter: (value) => {
        const opt = enmDeliveryMethodOptions.find((o) => o.value === value);
        return opt ? opt.label : String(value ?? '');
      },
    },
    {
      field: 'requestedDeliveryDate',
      headerName: 'Requested Delivery Date',
      width: 130,
      valueFormatter: (value) => value ? new Date(value as string).toLocaleDateString() : '',
    },
    { field: 'requestedDeliveryDay', headerName: 'Requested Delivery Day', flex: 1, minWidth: 150 },
    { field: 'notes', headerName: 'Notes', flex: 1, minWidth: 150 },
    {
      field: 'actions',
      type: 'actions',
      headerName: 'Actions',
      width: 140,
      getActions: (params) => [
        <GridActionsCellItem
          key="view"
          icon={<ViewIcon />}
          label="View"
          onClick={() => navigate(`/supplierOrders/${params.id}`)}
        />,
        <GridActionsCellItem
          key="edit"
          icon={<EditIcon />}
          label="Edit"
          onClick={() => navigate(`/supplierOrders/${params.id}/edit`)}
        />,
        <GridActionsCellItem
          key="delete"
          icon={<DeleteIcon />}
          label="Delete"
          onClick={() => setDeleteId(params.id as number)}
        />,
      ],
    },
  ];

  if (isError) {
    return (
      <Box sx={{ p: 3 }}>
        <Alert severity="error" sx={{ mb: 2 }}>
          Failed to load supplier orders: {(error as Error)?.message || 'Unknown error'}
        </Alert>
      </Box>
    );
  }

  const filterFields = [
    { field: 'fkOrderHeaderId', label: 'Order Header ID', type: 'number' as const },
    { field: 'supplierEmail', label: 'Supplier Email', type: 'string' as const },
    { field: 'emailSubject', label: 'Email Subject', type: 'string' as const },
    { field: 'emailBody', label: 'Email Body', type: 'string' as const },
    { field: 'enmEmailStatus', label: 'Email Status', type: 'string' as const },
    { field: 'sentDate', label: 'Sent Date', type: 'date' as const },
    { field: 'totalCost', label: 'Total Cost', type: 'number' as const },
    { field: 'enmDeliveryMethod', label: 'Delivery Method', type: 'string' as const },
    { field: 'requestedDeliveryDate', label: 'Requested Delivery Date', type: 'date' as const },
    { field: 'requestedDeliveryDay', label: 'Requested Delivery Day', type: 'string' as const },
    { field: 'notes', label: 'Notes', type: 'string' as const },
  ];

  return (
    <Box sx={{ p: 3 }}>
      <Box display="flex" justifyContent="flex-end" mb={1}>
        <Button size="small" startIcon={<FilterListIcon />} onClick={() => setShowFilters((p) => !p)} color={Object.keys(activeFilters).length > 0 ? 'primary' : 'inherit'}>
          {showFilters ? 'Hide Filters' : `Filters${Object.keys(activeFilters).length > 0 ? ` (${Object.keys(activeFilters).length})` : ''}`}
        </Button>
      </Box>
      <Collapse in={showFilters}>
        <FilterBuilder fields={filterFields} onApply={(f) => { setActiveFilters(f as Record<string, unknown>); setPaginationModel((p) => ({ ...p, page: 0 })); }} onClear={() => setActiveFilters({})} />
      </Collapse>
      <AppDataGrid
        entityName="supplierOrder"
        title="Supplier Order List"
        rows={data?.items || []}
        columns={columns}
        loading={isLoading}
        getRowId={(row) => (row as any).id as string | number}
        rowCount={data?.total || 0}
        paginationModel={paginationModel}
        onPaginationModelChange={setPaginationModel}
        serverSearch={search}
        onServerSearchChange={setSearch}
        sortModel={sortModel}
        onSortModelChange={handleSortModelChange}
        onRowClick={(id) => navigate(`/supplierOrders/${id}`)}
        checkboxSelection
        onSelectionChange={(ids) => setSelectedIds(ids)}
        onContextMenuActions={(id, row) => [
          { label: 'Open', icon: <OpenInNewIcon fontSize="small" />, onClick: () => navigate(`/supplierOrders/${id}`) },
          { label: 'Copy ID', icon: <ContentCopyIcon fontSize="small" />, onClick: () => { navigator.clipboard.writeText(String(id)); showSuccess('ID copied'); } },
          { label: 'Copy Row', icon: <ContentCopyIcon fontSize="small" />, onClick: () => { navigator.clipboard.writeText(JSON.stringify(row, null, 2)); showSuccess('Row copied'); } },
          { label: 'Duplicate', icon: <ContentCopyIcon fontSize="small" />, onClick: () => navigate(`/supplierOrders/new?cloneFrom=${id}`), divider: true },
          { label: 'Edit', icon: <EditIcon fontSize="small" />, onClick: () => navigate(`/supplierOrders/${id}/edit`) },
          { label: 'Delete', icon: <DeleteIcon fontSize="small" />, onClick: () => setDeleteId(id as number), divider: true },
        ]}
        onCreateNew={() => navigate('/supplierOrders/new')}
        editable
        processRowUpdate={async (newRow, oldRow) => { await updateMutation.mutateAsync({ id: (newRow as any).id as number, data: newRow as unknown as UpdateSupplierOrderRequest }); return newRow; }}
        onBulkEdit={async (ids, field, value) => {
          await Promise.all(ids.map((id) => updateMutation.mutateAsync({ id: id as number, data: { [field]: value } as unknown as UpdateSupplierOrderRequest })));
        }}
        bulkEditableFields={[
          { field: 'fkOrderHeaderId', label: 'Order Header ID', type: 'number' },
          { field: 'supplierEmail', label: 'Supplier Email', type: 'string' },
          { field: 'emailSubject', label: 'Email Subject', type: 'string' },
          { field: 'emailBody', label: 'Email Body', type: 'string' },
          { field: 'enmEmailStatus', label: 'Email Status', type: 'select' },
          { field: 'sentDate', label: 'Sent Date', type: 'date' },
          { field: 'enmDeliveryMethod', label: 'Delivery Method', type: 'select' },
          { field: 'requestedDeliveryDate', label: 'Requested Delivery Date', type: 'date' },
          { field: 'requestedDeliveryDay', label: 'Requested Delivery Day', type: 'string' },
          { field: 'notes', label: 'Notes', type: 'string' },
        ]}
        headerActions={
          <>
            <PermissionGate entity="supplierOrder" action="delete">
              {selectedIds.length > 0 && (
                <Button variant="outlined" color="error" onClick={() => setBulkDeleteConfirm(true)}>
                  Delete Selected ({selectedIds.length})
                </Button>
              )}
            </PermissionGate>
            <PermissionGate entity="supplierOrder" action="write">
              <Button variant="contained" onClick={() => navigate('/supplierOrders/new')}>
                Add New
              </Button>
              <Button variant="outlined" onClick={() => setQuickCreateOpen(true)}>
                Quick Create
              </Button>
            </PermissionGate>
          </>
        }
      />
      <Dialog open={quickCreateOpen} onClose={() => setQuickCreateOpen(false)} maxWidth="md" fullWidth>
        <DialogTitle>Quick Create Supplier Order</DialogTitle>
        <DialogContent>
          <SupplierOrderForm embedded onSuccess={() => setQuickCreateOpen(false)} />
        </DialogContent>
      </Dialog>
      <ConfirmDialog
        open={deleteId !== null}
        title="Delete Supplier Order"
        message="Are you sure you want to delete this supplier order? This action cannot be undone."
        confirmDisabled={deleteMutation.isPending}
        onConfirm={() => {
          if (deleteId !== null) {
            deleteMutation.mutate(deleteId);
          }
          setDeleteId(null);
        }}
        onCancel={() => setDeleteId(null)}
      />
      <ConfirmDialog
        open={bulkDeleteConfirm}
        title="Delete Multiple Supplier Orders"
        message={`Are you sure you want to delete ${selectedIds.length} supplier order(s)? This action cannot be undone.`}
        severity="error"
        onConfirm={async () => {
          try {
            await Promise.all(selectedIds.map((id) => deleteMutation.mutateAsync(id as number)));
          } catch { /* individual errors handled by mutation onError */ }
          setSelectedIds([]);
          setBulkDeleteConfirm(false);
        }}
        onCancel={() => setBulkDeleteConfirm(false)}
      />
    </Box>
  );
}

