// BeehiveBuyerTrackingApi.ts
// Generated by CodeCreator
import { api } from './client';
import type { BeehiveBuyerTracking, CreateBeehiveBuyerTrackingRequest, UpdateBeehiveBuyerTrackingRequest } from '../types/BeehiveBuyerTracking';

const API_URL = '/beehiveBuyerTrackings';

export const BeehiveBuyerTrackingApi = {
  getAll: (page: number = 0, pageSize: number = 25, search: string = '', sortField: string = '', sortDir: string = 'asc', filters?: Record<string, unknown>) =>
    api.get<{ items: BeehiveBuyerTracking[]; total: number }>(API_URL, { params: { page, pageSize, search, sortField, sortDir, ...filters } }).then((r) => r.data),

  getById: (id: number | string) =>
    api.get<BeehiveBuyerTracking>(`${API_URL}/${id}`).then((r) => r.data),

  create: (data: CreateBeehiveBuyerTrackingRequest) =>
    api.post<BeehiveBuyerTracking>(API_URL, data).then((r) => r.data),

  update: (id: number | string, data: UpdateBeehiveBuyerTrackingRequest & { _etag?: string }) => {
    const headers: Record<string, string> = {};
    if (data._etag) { headers['If-Match'] = `"${data._etag}"`; }
    const { _etag, ...payload } = data;
    return api.put<BeehiveBuyerTracking>(`${API_URL}/${id}`, { ...payload, id }, { headers }).then((r) => r.data);
  },

  delete: (id: number | string) =>
    api.delete(`${API_URL}/${id}`).then((r) => r.data),

};

