// client.ts
// Generated by CodeCreator - Shared API client
import axios from 'axios';

const api = axios.create({
  baseURL: '/api',
  timeout: 30000,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Request interceptor - attach auth token
api.interceptors.request.use((config) => {
  const token = localStorage.getItem('auth_token');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// Response interceptor - retry on 5xx/timeout with exponential backoff, handle 401
const MAX_RETRIES = 3;
const RETRY_DELAY = 1000;

api.interceptors.response.use(
  (response) => response,
  async (error) => {
    const config = error.config;
    // Retry logic for transient server errors (5xx, network errors, timeouts)
    const status = error.response?.status;
    const isRetryable = !status || status >= 500;
    if (isRetryable && config && !config.__retryCount) config.__retryCount = 0;
    if (isRetryable && config && config.__retryCount < MAX_RETRIES && config.method === 'get') {
      config.__retryCount += 1;
      const delay = RETRY_DELAY * Math.pow(2, config.__retryCount - 1);
      await new Promise((r) => setTimeout(r, delay));
      return api(config);
    }
    // Handle 401 Unauthorized — try token refresh once before logout
    if (status === 401 && !config?.url?.includes('/auth/') && !config?.__isRefreshAttempt) {
      try {
        const refreshResp = await api.post<{ token: string }>('/auth/refresh', {}, { __isRefreshAttempt: true } as unknown as undefined);
        const newToken = refreshResp.data.token;
        localStorage.setItem('auth_token', newToken);
        const storedUser = localStorage.getItem('auth_user');
        if (storedUser) { try { const u = JSON.parse(storedUser); u.token = newToken; localStorage.setItem('auth_user', JSON.stringify(u)); } catch {} }
        config.headers.Authorization = `Bearer ${newToken}`;
        return api(config); // Retry original request with new token
      } catch {
        localStorage.removeItem('auth_token');
        localStorage.removeItem('auth_user');
        window.location.href = '/';
      }
    } else if (status === 401) {
      localStorage.removeItem('auth_token');
      localStorage.removeItem('auth_user');
      window.location.href = '/';
    }
    // Extract server error message from response body
    const serverMessage = error.response?.data;
    if (typeof serverMessage === 'string' && serverMessage.length > 0) {
      error.message = serverMessage;
    } else if (serverMessage?.message) {
      error.message = serverMessage.message;
    } else if (serverMessage?.title) {
      error.message = serverMessage.title;
    }
    return Promise.reject(error);
  }
);

export { api };

