// CustomerDebtApi.ts
// Generated by CodeCreator
import { api } from './client';
import type { CustomerDebt, CreateCustomerDebtRequest, UpdateCustomerDebtRequest } from '../types/CustomerDebt';

const API_URL = '/customerDebts';

export const CustomerDebtApi = {
  getAll: (page: number = 0, pageSize: number = 25, search: string = '', sortField: string = '', sortDir: string = 'asc', filters?: Record<string, unknown>) =>
    api.get<{ items: CustomerDebt[]; total: number }>(API_URL, { params: { page, pageSize, search, sortField, sortDir, ...filters } }).then((r) => r.data),

  getById: (id: number | string) =>
    api.get<CustomerDebt>(`${API_URL}/${id}`).then((r) => r.data),

  create: (data: CreateCustomerDebtRequest) =>
    api.post<CustomerDebt>(API_URL, data).then((r) => r.data),

  update: (id: number | string, data: UpdateCustomerDebtRequest & { _etag?: string }) => {
    const headers: Record<string, string> = {};
    if (data._etag) { headers['If-Match'] = `"${data._etag}"`; }
    const { _etag, ...payload } = data;
    return api.put<CustomerDebt>(`${API_URL}/${id}`, { ...payload, id }, { headers }).then((r) => r.data);
  },

  delete: (id: number | string) =>
    api.delete(`${API_URL}/${id}`).then((r) => r.data),

};

