// EnumApi.ts
// Generated by CodeCreator - Enum values API client
import { api } from './client';

export interface EnumOption {
  value: number;
  /** English enum member name, e.g. "New". Stable across regenerations —
   *  match on this, never on `value`. */
  name: string;
  /** Hebrew display text from c_Enumeration.locText. */
  label: string;
}

export interface EnumTypeValues {
  enumType: string;
  values: EnumOption[];
}

let cachedEnums: EnumTypeValues[] | null = null;

export const EnumApi = {
  getAll: async (): Promise<EnumTypeValues[]> => {
    if (cachedEnums) return cachedEnums;
    const { data } = await api.get<EnumTypeValues[]>('/enums');
    cachedEnums = data;
    return data;
  },
};

