// OrderLineApi.ts
// Generated by CodeCreator
import { api } from './client';
import type { OrderLine, CreateOrderLineRequest, UpdateOrderLineRequest } from '../types/OrderLine';

const API_URL = '/orderLines';

export const OrderLineApi = {
  getAll: (page: number = 0, pageSize: number = 25, search: string = '', sortField: string = '', sortDir: string = 'asc', filters?: Record<string, unknown>) =>
    api.get<{ items: OrderLine[]; total: number }>(API_URL, { params: { page, pageSize, search, sortField, sortDir, ...filters } }).then((r) => r.data),

  getById: (id: number | string) =>
    api.get<OrderLine>(`${API_URL}/${id}`).then((r) => r.data),

  create: (data: CreateOrderLineRequest) =>
    api.post<OrderLine>(API_URL, data).then((r) => r.data),

  update: (id: number | string, data: UpdateOrderLineRequest & { _etag?: string }) => {
    const headers: Record<string, string> = {};
    if (data._etag) { headers['If-Match'] = `"${data._etag}"`; }
    const { _etag, ...payload } = data;
    return api.put<OrderLine>(`${API_URL}/${id}`, { ...payload, id }, { headers }).then((r) => r.data);
  },

  delete: (id: number | string) =>
    api.delete(`${API_URL}/${id}`).then((r) => r.data),

};

