// ProductPriceHistApi.ts
// Generated by CodeCreator
import { api } from './client';
import type { ProductPriceHist, CreateProductPriceHistRequest, UpdateProductPriceHistRequest } from '../types/ProductPriceHist';

const API_URL = '/productPriceHists';

export const ProductPriceHistApi = {
  getAll: (page: number = 0, pageSize: number = 25, search: string = '', sortField: string = '', sortDir: string = 'asc', filters?: Record<string, unknown>) =>
    api.get<{ items: ProductPriceHist[]; total: number }>(API_URL, { params: { page, pageSize, search, sortField, sortDir, ...filters } }).then((r) => r.data),

  getById: (id: number | string) =>
    api.get<ProductPriceHist>(`${API_URL}/${id}`).then((r) => r.data),

  create: (data: CreateProductPriceHistRequest) =>
    api.post<ProductPriceHist>(API_URL, data).then((r) => r.data),

  update: (id: number | string, data: UpdateProductPriceHistRequest & { _etag?: string }) => {
    const headers: Record<string, string> = {};
    if (data._etag) { headers['If-Match'] = `"${data._etag}"`; }
    const { _etag, ...payload } = data;
    return api.put<ProductPriceHist>(`${API_URL}/${id}`, { ...payload, id }, { headers }).then((r) => r.data);
  },

  delete: (id: number | string) =>
    api.delete(`${API_URL}/${id}`).then((r) => r.data),

};

