// ProductApi.ts
// Generated by CodeCreator
import { api } from './client';
import type { Product, CreateProductRequest, UpdateProductRequest } from '../types/Product';

const API_URL = '/products';

export const ProductApi = {
  getAll: (page: number = 0, pageSize: number = 25, search: string = '', sortField: string = '', sortDir: string = 'asc', filters?: Record<string, unknown>) =>
    api.get<{ items: Product[]; total: number }>(API_URL, { params: { page, pageSize, search, sortField, sortDir, ...filters } }).then((r) => r.data),

  getById: (id: number | string) =>
    api.get<Product>(`${API_URL}/${id}`).then((r) => r.data),

  create: (data: CreateProductRequest) =>
    api.post<Product>(API_URL, data).then((r) => r.data),

  update: (id: number | string, data: UpdateProductRequest & { _etag?: string }) => {
    const headers: Record<string, string> = {};
    if (data._etag) { headers['If-Match'] = `"${data._etag}"`; }
    const { _etag, ...payload } = data;
    return api.put<Product>(`${API_URL}/${id}`, { ...payload, id }, { headers }).then((r) => r.data);
  },

  delete: (id: number | string) =>
    api.delete(`${API_URL}/${id}`).then((r) => r.data),

};

