// SupplierOrderApi.ts
// Generated by CodeCreator
import { api } from './client';
import type { SupplierOrder, CreateSupplierOrderRequest, UpdateSupplierOrderRequest } from '../types/SupplierOrder';

const API_URL = '/supplierOrders';

export const SupplierOrderApi = {
  getAll: (page: number = 0, pageSize: number = 25, search: string = '', sortField: string = '', sortDir: string = 'asc', filters?: Record<string, unknown>) =>
    api.get<{ items: SupplierOrder[]; total: number }>(API_URL, { params: { page, pageSize, search, sortField, sortDir, ...filters } }).then((r) => r.data),

  getById: (id: number | string) =>
    api.get<SupplierOrder>(`${API_URL}/${id}`).then((r) => r.data),

  create: (data: CreateSupplierOrderRequest) =>
    api.post<SupplierOrder>(API_URL, data).then((r) => r.data),

  update: (id: number | string, data: UpdateSupplierOrderRequest & { _etag?: string }) => {
    const headers: Record<string, string> = {};
    if (data._etag) { headers['If-Match'] = `"${data._etag}"`; }
    const { _etag, ...payload } = data;
    return api.put<SupplierOrder>(`${API_URL}/${id}`, { ...payload, id }, { headers }).then((r) => r.data);
  },

  delete: (id: number | string) =>
    api.delete(`${API_URL}/${id}`).then((r) => r.data),

  send: (id: number | string) =>
    api.post<{ sent: boolean; message: string; to?: string; subject?: string; body?: string }>(`${API_URL}/${id}/send`, {}).then((r) => r.data),

};

