'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChangePassword

  '''<summary>
  '''form1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''imgLogo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents imgLogo As Global.System.Web.UI.WebControls.Image

  '''<summary>
  '''lblSystemName control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblSystemName As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblInstructions control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblInstructions As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblPresentPassword control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPresentPassword As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtPresentPassword control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtPresentPassword As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblNewPassword control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblNewPassword As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtNewPassword control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtNewPassword As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblRetypePassword control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblRetypePassword As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtRetypePassword control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtRetypePassword As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnSend control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnSend As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''lblResponseFailed control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblResponseFailed As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblResponseSucceeded control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblResponseSucceeded As Global.System.Web.UI.WebControls.Label
End Class