// App.tsx - Main application with collapsible sidebar, dark mode, breadcrumbs
// Generated by CodeCreator
import React, { useState, useMemo, lazy, Suspense, useCallback } from 'react';
import { Routes, Route, Navigate, useNavigate, useLocation } from 'react-router-dom';
import { useIsFetching } from '@tanstack/react-query';
import {
  Box,
  AppBar,
  Toolbar,
  Typography,
  Drawer,
  List,
  ListItem,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Divider,
  IconButton,
  TextField,
  Collapse,
  Breadcrumbs,
  Link,
  Button,
  CircularProgress,
  InputAdornment,
  useMediaQuery,
  useTheme,
} from '@mui/material';
import TableChartIcon from '@mui/icons-material/TableChart';
import DarkModeIcon from '@mui/icons-material/DarkMode';
import LightModeIcon from '@mui/icons-material/LightMode';
import ExpandLess from '@mui/icons-material/ExpandLess';
import ExpandMore from '@mui/icons-material/ExpandMore';
import SearchIcon from '@mui/icons-material/Search';
import ClearIcon from '@mui/icons-material/Clear';
import HomeIcon from '@mui/icons-material/Home';
import NavigateNextIcon from '@mui/icons-material/NavigateNext';
import FolderIcon from '@mui/icons-material/Folder';
import MenuIcon from '@mui/icons-material/Menu';
import LogoutIcon from '@mui/icons-material/Logout';
import VpnKeyIcon from '@mui/icons-material/VpnKey';
import DashboardIcon from '@mui/icons-material/Dashboard';
import StarIcon from '@mui/icons-material/Star';
import StarBorderIcon from '@mui/icons-material/StarBorder';
import HistoryIcon from '@mui/icons-material/History';
import CreditCardIcon from '@mui/icons-material/CreditCard';
import PeopleIcon from '@mui/icons-material/People';
import ReceiptIcon from '@mui/icons-material/Receipt';
import AssessmentIcon from '@mui/icons-material/Assessment';
import SecurityIcon from '@mui/icons-material/Security';
import AttachMoneyIcon from '@mui/icons-material/AttachMoney';
import StoreIcon from '@mui/icons-material/Store';
import SettingsIcon from '@mui/icons-material/Settings';
import InventoryIcon from '@mui/icons-material/Inventory';
import AccountBalanceIcon from '@mui/icons-material/AccountBalance';
import CategoryIcon from '@mui/icons-material/Category';
import NotificationsIcon from '@mui/icons-material/Notifications';
import DescriptionIcon from '@mui/icons-material/Description';
import LocalShippingIcon from '@mui/icons-material/LocalShipping';
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import KeyboardIcon from '@mui/icons-material/Keyboard';
import Dialog from '@mui/material/Dialog';
import DialogContent from '@mui/material/DialogContent';
import DialogTitle from '@mui/material/DialogTitle';
import Chip from '@mui/material/Chip';
import Tooltip from '@mui/material/Tooltip';
import LinearProgress from '@mui/material/LinearProgress';
import { useThemeMode } from './contexts/ThemeContext';
import { useAuth } from './contexts/AuthContext';
import { entityRoutes, sidebarGroups } from './routes';
import useTranslation from './i18n/useTranslation';
import LoginPage from './pages/LoginPage';
import Dashboard from './pages/Dashboard';
import UserAdminList from './pages/UserAdminList';
import ParametersList from './pages/ParametersList';
import ChangeMyPassword from './pages/ChangeMyPassword';

// Lazy-load all page components
const pages = import.meta.glob('./pages/*.tsx') as Record<string, () => Promise<{ default: React.ComponentType }>>;

function lazyPage(name: string) {
  const path = `./pages/${name}.tsx`;
  if (pages[path]) {
    return lazy(pages[path]);
  }
  return lazy(() => Promise.resolve({ default: () => <div>Page not found: {name}</div> }));
}

// Build lazy components map
const pageComponents: Record<string, Record<string, React.LazyExoticComponent<React.ComponentType>>> = {};
entityRoutes.forEach((r) => {
  // Standalone pages register their own route below and have no generated
  // List/Form/View trio to load. Leaving them out here also leaves them out of
  // the route generation, which keys off this map.
  if (r.standalone) return;
  const pascal = r.entity.charAt(0).toUpperCase() + r.entity.slice(1);
  pageComponents[r.entity] = {
    List: lazyPage(`${pascal}List`),
    Form: lazyPage(`${pascal}Form`),
    View: lazyPage(`${pascal}View`),
  };
});

// Dynamic group icon mapping - maps common name patterns to icons
const groupIconMap: Array<[RegExp, React.ReactElement]> = [
  [/card/i, <CreditCardIcon fontSize="small" />],
  [/customer|client|user|person|member/i, <PeopleIcon fontSize="small" />],
  [/transaction|payment|pay|billing|invoice/i, <ReceiptIcon fontSize="small" />],
  [/report|statistic|analytic|dashboard|summary/i, <AssessmentIcon fontSize="small" />],
  [/security|risk|auth|permission|role/i, <SecurityIcon fontSize="small" />],
  [/money|fund|balance|wallet|finance|account/i, <AttachMoneyIcon fontSize="small" />],
  [/store|shop|merchant|vendor|supplier/i, <StoreIcon fontSize="small" />],
  [/setting|config|preference|param/i, <SettingsIcon fontSize="small" />],
  [/inventory|stock|warehouse|product/i, <InventoryIcon fontSize="small" />],
  [/bank|branch|institution/i, <AccountBalanceIcon fontSize="small" />],
  [/categor|type|kind|class/i, <CategoryIcon fontSize="small" />],
  [/notification|alert|message|log/i, <NotificationsIcon fontSize="small" />],
  [/document|file|template|agreement/i, <DescriptionIcon fontSize="small" />],
  [/shipping|delivery|order|dispatch/i, <LocalShippingIcon fontSize="small" />],
];

function getGroupIcon(groupName: string): React.ReactElement {
  for (const [pattern, icon] of groupIconMap) {
    if (pattern.test(groupName)) return icon;
  }
  return <FolderIcon fontSize="small" />;
}

// Favorites management - persisted in localStorage
function useFavorites() {
  const [favorites, setFavorites] = useState<string[]>(() => {
    try {
      return JSON.parse(localStorage.getItem('cc_favorites') || '[]');
    } catch { return []; }
  });

  const toggleFavorite = (path: string) => {
    setFavorites((prev) => {
      const next = prev.includes(path) ? prev.filter((p) => p !== path) : [...prev, path];
      localStorage.setItem('cc_favorites', JSON.stringify(next));
      return next;
    });
  };

  const isFavorite = (path: string) => favorites.includes(path);
  const favoriteRoutes = entityRoutes.filter((r) => favorites.includes(r.path));
  return { favorites, toggleFavorite, isFavorite, favoriteRoutes };
}

// Recently opened items - last 5 visited entities
function useRecentItems() {
  const [recentPaths, setRecentPaths] = useState<string[]>(() => {
    try {
      return JSON.parse(localStorage.getItem('cc_recent_items') || '[]');
    } catch { return []; }
  });

  const addRecent = (path: string) => {
    setRecentPaths((prev) => {
      const next = [path, ...prev.filter((p) => p !== path)].slice(0, 5);
      localStorage.setItem('cc_recent_items', JSON.stringify(next));
      return next;
    });
  };

  const recentRoutes = recentPaths
    .map((p) => entityRoutes.find((r) => r.path === p))
    .filter(Boolean) as typeof entityRoutes;
  return { addRecent, recentRoutes };
}

// Command Palette - Ctrl+K quick navigation
function CommandPalette({ open, onClose }: { open: boolean; onClose: () => void }) {
  const navigate = useNavigate();
  const [query, setQuery] = useState('');
  const [selectedIndex, setSelectedIndex] = useState(0);

  const results = useMemo(() => {
    if (!query) return entityRoutes.slice(0, 8);
    const lower = query.toLowerCase();
    return entityRoutes.filter((r) =>
      r.label.toLowerCase().includes(lower) || r.entity.toLowerCase().includes(lower) || r.group.toLowerCase().includes(lower)
    );
  }, [query]);

  React.useEffect(() => { if (open) { setQuery(''); setSelectedIndex(0); } }, [open]);
  React.useEffect(() => { setSelectedIndex(0); }, [query]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setSelectedIndex((i) => Math.min(i + 1, results.length - 1));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setSelectedIndex((i) => Math.max(i - 1, 0));
    } else if (e.key === 'Enter' && results[selectedIndex]) {
      navigate(results[selectedIndex].path);
      onClose();
    }
  };

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth PaperProps={{ sx: { position: 'fixed', top: '15%', m: 0 } }}>
      <DialogContent sx={{ p: 0 }}>
        <TextField
          fullWidth autoFocus placeholder="חפש... (↑↓ ניווט, Enter לבחירה)"
          value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={handleKeyDown}
          slotProps={{ input: { startAdornment: <InputAdornment position="start"><SearchIcon /></InputAdornment>, sx: { fontSize: '1.1rem' } } }}
          sx={{ '& .MuiOutlinedInput-notchedOutline': { border: 'none' } }}
        />
        <Divider />
        <List dense sx={{ maxHeight: 320, overflow: 'auto', py: 0.5 }}>
          {results.length === 0 && (
            <Typography variant="body2" color="text.secondary" sx={{ p: 2, textAlign: 'center' }}>לא נמצאו תוצאות</Typography>
          )}
          {results.map((r, i) => (
            <ListItemButton
              key={r.path} selected={i === selectedIndex}
              onClick={() => { navigate(r.path); onClose(); }}
              onMouseEnter={() => setSelectedIndex(i)}
              sx={{ py: 0.75 }}
            >
              <ListItemIcon sx={{ minWidth: 36 }}>{getGroupIcon(r.group)}</ListItemIcon>
              <ListItemText primary={r.label} secondary={r.group} primaryTypographyProps={{ fontSize: '0.9rem' }} />
              {r.readOnly && <Chip label="View" size="small" variant="outlined" sx={{ ml: 1 }} />}
            </ListItemButton>
          ))}
        </List>
        <Divider />
        <Box sx={{ display: 'flex', gap: 1, p: 1, justifyContent: 'center' }}>
          <Typography variant="caption" color="text.secondary">↑↓ Navigate</Typography>
          <Typography variant="caption" color="text.secondary">↵ Open</Typography>
          <Typography variant="caption" color="text.secondary">Esc Close</Typography>
        </Box>
      </DialogContent>
    </Dialog>
  );
}

class ErrorBoundary extends React.Component<
  { children: React.ReactNode },
  { hasError: boolean; error: Error | null }
> {
  constructor(props: { children: React.ReactNode }) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error: Error) {
    return { hasError: true, error };
  }

  render() {
    if (this.state.hasError) {
      return (
        <Box sx={{ p: 4, textAlign: 'center' }}>
          <Typography variant="h5" color="error" gutterBottom>
            משהו השתבש
          </Typography>
          <Typography color="text.secondary" sx={{ mb: 2 }}>
            {this.state.error?.message || 'אירעה שגיאה לא צפויה'}
          </Typography>
          <Button variant="contained" onClick={() => this.setState({ hasError: false, error: null })}>
            נסה שוב
          </Button>
        </Box>
      );
    }
    return this.props.children;
  }
}

const drawerWidth = 260;
const miniDrawerWidth = 58;

function AppBreadcrumbs() {
  const location = useLocation();
  const navigate = useNavigate();
  const parts = location.pathname.split('/').filter(Boolean);

  if (parts.length === 0) return null;

  const route = entityRoutes.find((r) => location.pathname.startsWith(r.path));
  if (!route) return null;

  const crumbs: { label: string; href?: string }[] = [{ label: 'בית', href: '/' }];
  crumbs.push({ label: route.label, href: route.path });

  if (parts.length >= 2) {
    if (parts[1] === 'new') {
      crumbs.push({ label: 'חדש' });
    } else if (parts.length === 2) {
      crumbs.push({ label: `#${parts[1]}` });
    } else if (parts[2] === 'edit') {
      crumbs.push({ label: `#${parts[1]}`, href: `${route.path}/${parts[1]}` });
      crumbs.push({ label: 'עריכה' });
    }
  }

  return (
    <Breadcrumbs separator={<NavigateNextIcon fontSize="small" />} sx={{ mb: 2 }}>
      {crumbs.map((c, i) =>
        i < crumbs.length - 1 && c.href ? (
          <Link
            key={i}
            underline="hover"
            color="inherit"
            href={c.href}
            onClick={(e) => { e.preventDefault(); navigate(c.href!); }}
            sx={{ display: 'flex', alignItems: 'center', gap: 0.5, cursor: 'pointer' }}
          >
            {i === 0 && <HomeIcon fontSize="small" />}
            {c.label}
          </Link>
        ) : (
          <Typography key={i} color="text.primary">{c.label}</Typography>
        )
      )}
    </Breadcrumbs>
  );
}

function NavSidebar({
  mobileOpen, onMobileClose, favorites, recentRoutes, isMini, onToggleMini,
}: {
  mobileOpen: boolean; onMobileClose: () => void;
  favorites: ReturnType<typeof useFavorites>;
  recentRoutes: typeof entityRoutes;
  isMini: boolean; onToggleMini: () => void;
}) {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));
  const navigate = useNavigate();
  const location = useLocation();
  const [search, setSearch] = useState('');
  const [openGroups, setOpenGroups] = useState<Record<string, boolean>>(() => {
    const current = entityRoutes.find((r) => location.pathname.startsWith(r.path));
    const initial: Record<string, boolean> = {};
    if (current) initial[current.group] = true;
    return initial;
  });
  const [showFavorites, setShowFavorites] = useState(true);
  const [showRecent, setShowRecent] = useState(true);

  const effectiveWidth = isMini && !isMobile ? miniDrawerWidth : drawerWidth;

  const toggleGroup = (group: string) => {
    setOpenGroups((prev) => ({ ...prev, [group]: !prev[group] }));
  };

  const filteredRoutes = useMemo(() => {
    // Raw generated CRUD entries (e.g. orderHeaders / orderLines) are hidden from the sidebar
    const visibleRoutes = entityRoutes.filter((r) => !r.hideInNav);
    if (!search) return visibleRoutes;
    const lower = search.toLowerCase();
    return visibleRoutes.filter((r) => r.label.toLowerCase().includes(lower));
  }, [search]);

  const groupedRoutes = useMemo(() => {
    const map: Record<string, typeof entityRoutes> = {};
    filteredRoutes.forEach((r) => {
      if (!map[r.group]) map[r.group] = [];
      map[r.group].push(r);
    });
    return map;
  }, [filteredRoutes]);

  const handleNav = (path: string) => {
    navigate(path);
    if (isMobile) onMobileClose();
  };

  return (
    <Drawer
      variant={isMobile ? 'temporary' : 'permanent'}
      open={isMobile ? mobileOpen : true}
      onClose={onMobileClose}
      ModalProps={{ keepMounted: true }}
      sx={{
        width: isMobile ? 0 : effectiveWidth,
        flexShrink: 0,
        transition: 'width 0.2s ease',
        '& .MuiDrawer-paper': {
          width: isMobile ? drawerWidth : effectiveWidth,
          boxSizing: 'border-box',
          mt: isMobile ? 0 : '64px',
          overflowX: 'hidden',
          transition: 'width 0.2s ease',
        },
      }}
    >
      <List dense disablePadding>
        <Tooltip title={isMini && !isMobile ? 'לוח בקרה' : ''} placement="right">
          <ListItemButton selected={location.pathname === '/'} onClick={() => handleNav('/')} sx={{ justifyContent: isMini && !isMobile ? 'center' : 'initial' }}>
            <ListItemIcon sx={{ minWidth: isMini && !isMobile ? 'auto' : 36, justifyContent: 'center' }}><DashboardIcon fontSize="small" /></ListItemIcon>
            {!(isMini && !isMobile) && <ListItemText primary="לוח בקרה" primaryTypographyProps={{ fontWeight: 600, fontSize: '0.875rem' }} />}
          </ListItemButton>
        </Tooltip>
      </List>
      <Divider />
      {!(isMini && !isMobile) && <Box sx={{ p: 1 }}>
        <TextField
          size="small"
          fullWidth
          placeholder="חיפוש... (Ctrl+K)"
          value={search}
          onChange={(e) => {
            setSearch(e.target.value);
            if (e.target.value) {
              const all: Record<string, boolean> = {};
              sidebarGroups.forEach((g) => (all[g] = true));
              setOpenGroups(all);
            }
          }}
          slotProps={{
            input: {
              startAdornment: (
                <InputAdornment position="start">
                  <SearchIcon fontSize="small" />
                </InputAdornment>
              ),
              endAdornment: search ? (
                <InputAdornment position="end">
                  <IconButton size="small" onClick={() => setSearch('')}>
                    <ClearIcon fontSize="small" />
                  </IconButton>
                </InputAdornment>
              ) : null,
            },
          }}
        />
      </Box>}
      <Divider />
      <Box sx={{ overflow: 'auto', flex: 1 }}>
        {!(isMini && !isMobile) && favorites.favoriteRoutes.length > 0 && !search && (
          <>
            <ListItemButton onClick={() => setShowFavorites((p) => !p)} sx={{ py: 0.5 }}>
              <ListItemIcon sx={{ minWidth: 36 }}><StarIcon fontSize="small" sx={{ color: 'warning.main' }} /></ListItemIcon>
              <ListItemText primary="מועדפים" primaryTypographyProps={{ fontWeight: 600, fontSize: '0.8rem', color: 'text.secondary' }} />
              {showFavorites ? <ExpandLess fontSize="small" /> : <ExpandMore fontSize="small" />}
            </ListItemButton>
            <Collapse in={showFavorites} timeout="auto" unmountOnExit>
              <List dense disablePadding>
                {favorites.favoriteRoutes.map((route) => (
                  <ListItemButton key={route.path} selected={location.pathname.startsWith(route.path)} onClick={() => handleNav(route.path)} sx={{ pl: 4 }}>
                    <ListItemIcon sx={{ minWidth: 28 }}>{getGroupIcon(route.group)}</ListItemIcon>
                    <ListItemText primary={route.label} primaryTypographyProps={{ fontSize: '0.8rem' }} />
                  </ListItemButton>
                ))}
              </List>
            </Collapse>
            <Divider sx={{ my: 0.5 }} />
          </>
        )}
        {!(isMini && !isMobile) && recentRoutes.length > 0 && !search && (
          <>
            <ListItemButton onClick={() => setShowRecent((p) => !p)} sx={{ py: 0.5 }}>
              <ListItemIcon sx={{ minWidth: 36 }}><HistoryIcon fontSize="small" /></ListItemIcon>
              <ListItemText primary="אחרונים" primaryTypographyProps={{ fontWeight: 600, fontSize: '0.8rem', color: 'text.secondary' }} />
              {showRecent ? <ExpandLess fontSize="small" /> : <ExpandMore fontSize="small" />}
            </ListItemButton>
            <Collapse in={showRecent} timeout="auto" unmountOnExit>
              <List dense disablePadding>
                {recentRoutes.map((route) => (
                  <ListItemButton key={route.path} selected={location.pathname.startsWith(route.path)} onClick={() => handleNav(route.path)} sx={{ pl: 4 }}>
                    <ListItemIcon sx={{ minWidth: 28 }}>{getGroupIcon(route.group)}</ListItemIcon>
                    <ListItemText primary={route.label} primaryTypographyProps={{ fontSize: '0.8rem' }} />
                  </ListItemButton>
                ))}
              </List>
            </Collapse>
            <Divider sx={{ my: 0.5 }} />
          </>
        )}
        <List dense>
          {sidebarGroups.map((group) => {
            const routes = groupedRoutes[group];
            if (!routes || routes.length === 0) return null;
            const isOpen = openGroups[group] ?? false;
            const hasActiveChild = routes.some((r) => location.pathname.startsWith(r.path));
            const mini = isMini && !isMobile;

            return (
              <Box key={group}>
                <Tooltip title={mini ? group : ''} placement="right">
                  <ListItemButton
                    onClick={() => mini ? handleNav(routes[0].path) : toggleGroup(group)}
                    sx={{ bgcolor: hasActiveChild ? 'action.selected' : 'transparent', justifyContent: mini ? 'center' : 'initial', px: mini ? 1 : 2 }}
                  >
                    <ListItemIcon sx={{ minWidth: mini ? 'auto' : 36, justifyContent: 'center' }}>
                      {getGroupIcon(group)}
                    </ListItemIcon>
                    {!mini && <ListItemText
                      primary={group}
                      primaryTypographyProps={{ fontWeight: hasActiveChild ? 700 : 500, fontSize: '0.875rem' }}
                    />}
                    {!mini && <Typography variant="caption" color="text.secondary" sx={{ mr: 0.5 }}>
                      {routes.length}
                    </Typography>}
                    {!mini && (isOpen ? <ExpandLess fontSize="small" /> : <ExpandMore fontSize="small" />)}
                  </ListItemButton>
                </Tooltip>
                {!mini && <Collapse in={isOpen} timeout="auto" unmountOnExit>
                  <List dense disablePadding>
                    {routes.map((route) => (
                      <ListItemButton
                        key={route.path}
                        selected={location.pathname.startsWith(route.path)}
                        onClick={() => handleNav(route.path)}
                        sx={{ pl: 5, pr: 1 }}
                      >
                        <ListItemText
                          primary={route.label}
                          primaryTypographyProps={{ fontSize: '0.8rem' }}
                        />
                        <Tooltip title={favorites.isFavorite(route.path) ? 'Remove from favorites' : 'Add to favorites'}>
                          <IconButton
                            size="small"
                            onClick={(e) => { e.stopPropagation(); favorites.toggleFavorite(route.path); }}
                            sx={{ opacity: favorites.isFavorite(route.path) ? 1 : 0, '&:hover': { opacity: 1 }, transition: 'opacity 0.2s' }}
                          >
                            {favorites.isFavorite(route.path) ? <StarIcon fontSize="small" sx={{ color: 'warning.main' }} /> : <StarBorderIcon fontSize="small" />}
                          </IconButton>
                        </Tooltip>
                      </ListItemButton>
                    ))}
                  </List>
                </Collapse>}
              </Box>
            );
          })}
        </List>
      </Box>
      {!isMobile && (
        <>
          <Divider />
          <Box sx={{ display: 'flex', justifyContent: isMini ? 'center' : 'flex-end', p: 0.5 }}>
            <Tooltip title={isMini ? 'Expand sidebar' : 'Collapse sidebar'} placement="right">
              <IconButton size="small" onClick={onToggleMini}>
                {isMini ? <ChevronRightIcon fontSize="small" /> : <ChevronLeftIcon fontSize="small" />}
              </IconButton>
            </Tooltip>
          </Box>
        </>
      )}
    </Drawer>
  );
}

// Keyboard Shortcuts Help Dialog
function ShortcutsHelpDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const shortcuts = [
    { keys: 'Ctrl+K', description: 'פתח חיפוש מהיר' },
    { keys: 'Ctrl+S', description: 'שמור טופס' },
    { keys: 'Ctrl+Enter', description: 'שמור טופס' },
    { keys: 'Escape', description: 'חזור / סגור' },
    { keys: '[', description: 'כווץ/הרחב תפריט' },
    { keys: '?', description: 'הצג עזרה' },
  ];

  return (
    <Dialog open={open} onClose={onClose} maxWidth="xs" fullWidth>
      <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
        <KeyboardIcon /> קיצורי מקלדת
      </DialogTitle>
      <DialogContent>
        <List dense>
          {shortcuts.map((s) => (
            <ListItem key={s.keys} sx={{ px: 0 }}>
              <ListItemText primary={s.description} />
              <Chip label={s.keys} size="small" variant="outlined" sx={{ fontFamily: 'monospace', fontWeight: 600 }} />
            </ListItem>
          ))}
        </List>
      </DialogContent>
    </Dialog>
  );
}

function PageFallback() {
  return (
    <Box display="flex" justifyContent="center" alignItems="center" p={4}>
      <CircularProgress />
    </Box>
  );
}

export default function App() {
  const { isDarkMode, toggleTheme } = useThemeMode();
  const { isAuthenticated, user, logout } = useAuth();
  const navigate = useNavigate();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [cmdPaletteOpen, setCmdPaletteOpen] = useState(false);
  const [shortcutsOpen, setShortcutsOpen] = useState(false);
  const [sidebarMini, setSidebarMini] = useState(() => localStorage.getItem('cc_sidebar_mini') === 'true');
  const isFetching = useIsFetching();
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));
  const location = useLocation();
  const favs = useFavorites();
  const { addRecent, recentRoutes } = useRecentItems();

  const toggleSidebarMini = () => {
    setSidebarMini((prev) => {
      localStorage.setItem('cc_sidebar_mini', String(!prev));
      return !prev;
    });
  };

  // Track recently opened entities
  React.useEffect(() => {
    const match = entityRoutes.find((r) => location.pathname === r.path || location.pathname.startsWith(r.path + '/'));
    if (match) addRecent(match.path);
  }, [location.pathname]);

  // Global keyboard shortcuts: Ctrl+K, '[' toggle sidebar, '?' help
  React.useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      const tag = (e.target as HTMLElement)?.tagName;
      const isInput = tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT';
      if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
        e.preventDefault();
        setCmdPaletteOpen((prev) => !prev);
      }
      if (!isInput && e.key === '[') {
        toggleSidebarMini();
      }
      if (!isInput && e.key === '?' && !e.ctrlKey && !e.metaKey) {
        setShortcutsOpen((prev) => !prev);
      }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, []);

  // Show login page when not authenticated
  if (!isAuthenticated) {
    return <LoginPage />;
  }

  return (
    <Box sx={{ display: 'flex' }}>
      <AppBar position="fixed" sx={{ zIndex: (t) => t.zIndex.drawer + 1 }}>
        <Toolbar>
          {isMobile && (
            <IconButton color="inherit" edge="start" onClick={() => setMobileOpen(true)} sx={{ mr: 1 }}>
              <MenuIcon />
            </IconButton>
          )}
          <Typography variant="h6" noWrap component="div" sx={{ flexGrow: 1, fontWeight: 700 }}>
            ניהול הזמנות
          </Typography>
          <Button
            variant="outlined"
            size="small"
            onClick={() => setCmdPaletteOpen(true)}
            sx={{
              color: 'inherit', borderColor: 'rgba(255,255,255,0.3)', textTransform: 'none',
              mr: 2, px: 1.5, fontSize: '0.8rem', display: { xs: 'none', sm: 'flex' }, gap: 1,
            }}
          >
            <SearchIcon fontSize="small" /> חיפוש
            <Typography component="span" sx={{ fontSize: '0.7rem', border: '1px solid rgba(255,255,255,0.3)', borderRadius: 0.5, px: 0.5, ml: 0.5 }}>
              Ctrl+K
            </Typography>
          </Button>
          <Typography variant="body2" color="inherit" sx={{ mr: 1 }}>
            {user?.username}
          </Typography>
          <Tooltip title="Keyboard shortcuts (?)">
            <IconButton color="inherit" onClick={() => setShortcutsOpen(true)}>
              <KeyboardIcon />
            </IconButton>
          </Tooltip>
          <IconButton color="inherit" onClick={toggleTheme} title={isDarkMode ? 'Light mode' : 'Dark mode'}>
            {isDarkMode ? <LightModeIcon /> : <DarkModeIcon />}
          </IconButton>
          {/* Every account starts on the shared initial password, so this has
              to be reachable by anyone who can log in -- not gated on a role,
              and not only by knowing the URL. */}
          <Tooltip title="שינוי סיסמה">
            <IconButton color="inherit" onClick={() => navigate('/change-password')}>
              <VpnKeyIcon />
            </IconButton>
          </Tooltip>
          <IconButton color="inherit" onClick={logout} title="יציאה">
            <LogoutIcon />
          </IconButton>
        </Toolbar>
      </AppBar>
      <NavSidebar mobileOpen={mobileOpen} onMobileClose={() => setMobileOpen(false)} favorites={favs} recentRoutes={recentRoutes} isMini={sidebarMini} onToggleMini={toggleSidebarMini} />
      <CommandPalette open={cmdPaletteOpen} onClose={() => setCmdPaletteOpen(false)} />
      <ShortcutsHelpDialog open={shortcutsOpen} onClose={() => setShortcutsOpen(false)} />
      {isFetching > 0 && <LinearProgress sx={{ position: 'fixed', top: 64, left: 0, right: 0, zIndex: (t) => t.zIndex.drawer + 2, height: 2 }} />}
      <Box component="main" sx={{ flexGrow: 1, mt: '64px', p: 3, minHeight: 'calc(100vh - 64px)' }}>
        <AppBreadcrumbs />
        <ErrorBoundary>
        <Suspense fallback={<PageFallback />}>
          <Routes>
            <Route path="/" element={<Dashboard />} />
            {/* Dashboard was reachable only at "/". A direct hit or bookmark on
                /dashboard rendered a blank page with no console error. */}
            <Route path="/dashboard" element={<Dashboard />} />
            <Route path="/users" element={<UserAdminList />} />
            <Route path="/parameters" element={<ParametersList />} />
            <Route path="/change-password" element={<ChangeMyPassword />} />
            {entityRoutes.map((route) => {
              const comps = pageComponents[route.entity];
              if (!comps) return null;
              const ListPage = comps.List;
              const FormPage = comps.Form;
              const ViewPage = comps.View;
              const routes = [
                <Route key={`${route.path}-list`} path={route.path} element={<ListPage />} />,
              ];
              if (!route.readOnly) {
                routes.push(
                  <Route key={`${route.path}-new`} path={`${route.path}/new`} element={<FormPage />} />,
                  <Route key={`${route.path}-edit`} path={`${route.path}/:id/edit`} element={<FormPage />} />,
                );
              }
              routes.push(<Route key={`${route.path}-view`} path={`${route.path}/:id`} element={<ViewPage />} />);
              return routes;
            })}
          </Routes>
        </Suspense>
        </ErrorBoundary>
      </Box>
    </Box>
  );
}

