// AppFormField.tsx
// Generated by CodeCreator - Reusable form field component
import { Controller, type Control, type FieldValues, type Path } from 'react-hook-form';
import { TextField, FormControlLabel, Checkbox, MenuItem } from '@mui/material';

export interface SelectOption {
  value: string;
  label: string;
}

interface AppFormFieldProps<T extends FieldValues> {
  name: Path<T>;
  control: Control<T>;
  label: string;
  type?: 'text' | 'number' | 'date' | 'datetime-local' | 'time' | 'checkbox' | 'textarea' | 'password' | 'select';
  required?: boolean;
  error?: string;
  defaultValue?: unknown;
  disabled?: boolean;
  rows?: number;
  options?: SelectOption[];
}

export default function AppFormField<T extends FieldValues>({
  name,
  control,
  label,
  type = 'text',
  required = false,
  error,
  defaultValue,
  disabled = false,
  rows = 4,
  options = [],
}: AppFormFieldProps<T>) {
  if (type === 'checkbox') {
    return (
      <Controller
        name={name}
        control={control}
        defaultValue={(defaultValue ?? false) as never}
        render={({ field }) => (
          <FormControlLabel
            control={
              <Checkbox
                checked={Boolean(field.value)}
                onChange={field.onChange}
                disabled={disabled}
              />
            }
            label={label}
          />
        )}
      />
    );
  }

  const isDateType = type === 'date' || type === 'datetime-local' || type === 'time';
  const isTextarea = type === 'textarea';
  const isSelect = type === 'select';

  return (
    <Controller
      name={name}
      control={control}
      defaultValue={(defaultValue ?? '') as never}
      render={({ field }) => (
        <TextField
          {...field}
          label={label}
          type={isTextarea || isSelect ? 'text' : type}
          fullWidth
          required={required}
          disabled={disabled}
          error={Boolean(error)}
          helperText={error}
          multiline={isTextarea}
          rows={isTextarea ? rows : undefined}
          select={isSelect}
          slotProps={{ inputLabel: isDateType ? { shrink: true } : undefined }}
        >
          {isSelect && options.map((opt) => (
            <MenuItem key={opt.value} value={opt.value}>
              {opt.label}
            </MenuItem>
          ))}
        </TextField>
      )}
    />
  );
}

