// FilterBuilder.tsx
// Generated by CodeCreator - Advanced filter builder for DataGrid
import { useState, useCallback, type ReactNode } from 'react';
import {
  Box, Button, IconButton, TextField, Select, MenuItem, FormControl, InputLabel, Paper, Typography,
} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import DeleteIcon from '@mui/icons-material/Delete';
import FilterListIcon from '@mui/icons-material/FilterList';
import type { GridFilterModel, GridFilterItem } from '@mui/x-data-grid';

interface FilterField {
  field: string;
  label: string;
  type?: 'string' | 'number' | 'date' | 'boolean';
}

interface FilterRow {
  id: number;
  field: string;
  operator: string;
  value: string;
}

interface FilterBuilderProps {
  fields: FilterField[];
  onApply: (filterModel: GridFilterModel | Record<string, unknown>) => void;
  onClear?: () => void;
}

const OPERATORS = [
  { value: 'contains', label: 'Contains' },
  { value: 'equals', label: 'Equals' },
  { value: 'startsWith', label: 'Starts with' },
  { value: 'endsWith', label: 'Ends with' },
  { value: '>', label: 'Greater than' },
  { value: '<', label: 'Less than' },
];

let nextId = 1;

export default function FilterBuilder({ fields, onApply, onClear }: FilterBuilderProps) {
  const [rows, setRows] = useState<FilterRow[]>([]);

  const addRow = useCallback(() => {
    setRows((prev) => [...prev, { id: nextId++, field: fields[0]?.field ?? '', operator: 'contains', value: '' }]);
  }, [fields]);

  const removeRow = useCallback((id: number) => {
    setRows((prev) => prev.filter((r) => r.id !== id));
  }, []);

  const updateRow = useCallback((id: number, key: keyof FilterRow, value: string) => {
    setRows((prev) => prev.map((r) => (r.id === id ? { ...r, [key]: value } : r)));
  }, []);

  const handleApply = useCallback(() => {
    const items: GridFilterItem[] = rows
      .filter((r) => r.field && r.value)
      .map((r, idx) => ({ id: idx, field: r.field, operator: r.operator, value: r.value }));
    onApply({ items });
  }, [rows, onApply]);

  const handleClear = useCallback(() => {
    setRows([]);
    onApply({ items: [] });
    onClear?.();
  }, [onApply, onClear]);

  return (
    <Paper variant="outlined" sx={{ p: 2, mb: 2 }}>
      <Box display="flex" alignItems="center" justifyContent="space-between" mb={1}>
        <Box display="flex" alignItems="center" gap={1}>
          <FilterListIcon fontSize="small" color="primary" />
          <Typography variant="subtitle2">Advanced Filters</Typography>
        </Box>
        <Button size="small" startIcon={<AddIcon />} onClick={addRow}>Add Filter</Button>
      </Box>

      {rows.map((row) => (
        <Box key={row.id} display="flex" gap={1} alignItems="center" mb={1}>
          <FormControl size="small" sx={{ minWidth: 150 }}>
            <InputLabel>Field</InputLabel>
            <Select value={row.field} label="Field" onChange={(e) => updateRow(row.id, 'field', e.target.value)}>
              {fields.map((f) => (
                <MenuItem key={f.field} value={f.field}>{f.label}</MenuItem>
              ))}
            </Select>
          </FormControl>
          <FormControl size="small" sx={{ minWidth: 140 }}>
            <InputLabel>Operator</InputLabel>
            <Select value={row.operator} label="Operator" onChange={(e) => updateRow(row.id, 'operator', e.target.value)}>
              {OPERATORS.map((op) => (
                <MenuItem key={op.value} value={op.value}>{op.label}</MenuItem>
              ))}
            </Select>
          </FormControl>
          <TextField size="small" label="Value" value={row.value} onChange={(e) => updateRow(row.id, 'value', e.target.value)} sx={{ flex: 1 }} />
          <IconButton size="small" onClick={() => removeRow(row.id)} color="error">
            <DeleteIcon fontSize="small" />
          </IconButton>
        </Box>
      ))}

      {rows.length > 0 && (
        <Box display="flex" gap={1} justifyContent="flex-end" mt={1}>
          <Button size="small" onClick={handleClear}>Clear</Button>
          <Button size="small" variant="contained" onClick={handleApply}>Apply Filters</Button>
        </Box>
      )}
    </Paper>
  );
}

