// BeehiveBuyerTracking.ts
// Generated by CodeCreator
import { z } from 'zod';

export interface BeehiveBuyerTracking {
  id: number;
  fkCustomerId: number;
  lastOrderDate: string | null;
  beehiveQuantity: number | null;
  reminderMonth: number | null;
  readonly isRelevant: boolean;
  notes: string | null;
  /** Concurrency control: hash of record state at time of GET */
  _etag?: string;
}

export interface CreateBeehiveBuyerTrackingRequest {
  fkCustomerId: number;
  lastOrderDate?: string | null;
  beehiveQuantity?: number | null;
  reminderMonth?: number | null;
  notes?: string | null;
}

export type UpdateBeehiveBuyerTrackingRequest = CreateBeehiveBuyerTrackingRequest;

export const beehiveBuyerTrackingSchema = z.object({
  fkCustomerId: z.coerce.number(),
  lastOrderDate: z.string().optional().nullable(),
  beehiveQuantity: z.coerce.number().optional().nullable(),
  reminderMonth: z.coerce.number().optional().nullable(),
  notes: z.string().optional().nullable(),
});

export type BeehiveBuyerTrackingFormData = z.infer<typeof beehiveBuyerTrackingSchema>;

