// CustomerDebt.ts
// Generated by CodeCreator
import { z } from 'zod';

export interface CustomerDebt {
  id: number;
  fkCustomerId: number;
  fkOrderHeaderId: number | null;
  debtAmount: number;
  paidAmount: number | null;
  readonly remainingAmount: number | null;
  debtDate: string;
  dueDate: string | null;
  enmDebtStatus: number | null;
  notes: string | null;
  readonly needsAttention: boolean;
  productTypes: string | null;
  deliveryDate: string | null;
  /** Concurrency control: hash of record state at time of GET */
  _etag?: string;
}

export interface CreateCustomerDebtRequest {
  fkCustomerId: number;
  fkOrderHeaderId?: number | null;
  debtAmount: number;
  paidAmount?: number | null;
  debtDate: string;
  dueDate?: string | null;
  enmDebtStatus?: number | null;
  notes?: string | null;
  productTypes?: string | null;
  deliveryDate?: string | null;
}

export type UpdateCustomerDebtRequest = CreateCustomerDebtRequest;

export const customerDebtSchema = z.object({
  fkCustomerId: z.coerce.number(),
  fkOrderHeaderId: z.coerce.number().optional().nullable(),
  debtAmount: z.coerce.number(),
  paidAmount: z.coerce.number().optional().nullable(),
  debtDate: z.string().min(1, 'Debt Date is required'),
  dueDate: z.string().optional().nullable(),
  enmDebtStatus: z.coerce.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  productTypes: z.string().max(500).optional().nullable(),
  deliveryDate: z.string().optional().nullable(),
});

export type CustomerDebtFormData = z.infer<typeof customerDebtSchema>;

