// Customer.ts
// Generated by CodeCreator
import { z } from 'zod';

export interface Customer {
  id: number;
  customerCode: string;
  customerName: string;
  phone: string | null;
  email: string | null;
  address: string | null;
  city: string | null;
  taxId: string | null;
  enmCustomerType: number | null;
  paymentTermsDays: number | null;
  notes: string | null;
  readonly isActive: boolean | null;
  location: string | null;
  accountantEmail: string | null;
  enmAccountantMethod: number | null;
  invoiceName: string | null;
  profitabilityCode: string | null;
  readonly customerIdentifier: string | null;
  /** Concurrency control: hash of record state at time of GET */
  _etag?: string;
}

export interface CreateCustomerRequest {
  customerCode: string;
  customerName: string;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  city?: string | null;
  taxId?: string | null;
  enmCustomerType?: number | null;
  paymentTermsDays?: number | null;
  notes?: string | null;
  location?: string | null;
  accountantEmail?: string | null;
  enmAccountantMethod?: number | null;
  invoiceName?: string | null;
  profitabilityCode?: string | null;
}

export type UpdateCustomerRequest = CreateCustomerRequest;

export const customerSchema = z.object({
  customerCode: z.string().min(1, 'Customer Code is required').max(50),
  customerName: z.string().min(1, 'Customer Name is required').max(255),
  phone: z.string().max(20).optional().nullable(),
  email: z.string().email('Invalid email address').max(255).optional().nullable(),
  address: z.string().optional().nullable(),
  city: z.string().max(100).optional().nullable(),
  taxId: z.string().max(20).optional().nullable(),
  enmCustomerType: z.coerce.number().optional().nullable(),
  paymentTermsDays: z.coerce.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  location: z.string().max(100).optional().nullable(),
  accountantEmail: z.string().email('Invalid email address').max(255).optional().nullable(),
  enmAccountantMethod: z.coerce.number().optional().nullable(),
  invoiceName: z.string().max(255).optional().nullable(),
  profitabilityCode: z.string().max(50).optional().nullable(),
});

export type CustomerFormData = z.infer<typeof customerSchema>;

