// Delivery.ts
// Generated by CodeCreator
import { z } from 'zod';

export interface Delivery {
  id: number;
  fkOrderHeaderId: number;
  deliveryAddress: string | null;
  contactPhone: string | null;
  contactName: string | null;
  enmDeliveryMethod: number | null;
  orderedDate: string | null;
  receivedDate: string | null;
  arrivalToHubDate: string | null;
  arrivalToCustomerDate: string | null;
  enmDeliveryStatus: number;
  location: string | null;
  readonly productsSummary: string | null;
  notes: string | null;
  /** Concurrency control: hash of record state at time of GET */
  _etag?: string;
}

export interface CreateDeliveryRequest {
  fkOrderHeaderId: number;
  deliveryAddress?: string | null;
  contactPhone?: string | null;
  contactName?: string | null;
  enmDeliveryMethod?: number | null;
  orderedDate?: string | null;
  receivedDate?: string | null;
  arrivalToHubDate?: string | null;
  arrivalToCustomerDate?: string | null;
  enmDeliveryStatus: number;
  location?: string | null;
  notes?: string | null;
}

export type UpdateDeliveryRequest = CreateDeliveryRequest;

export const deliverySchema = z.object({
  fkOrderHeaderId: z.coerce.number(),
  deliveryAddress: z.string().max(500).optional().nullable(),
  contactPhone: z.string().max(50).optional().nullable(),
  contactName: z.string().max(255).optional().nullable(),
  enmDeliveryMethod: z.coerce.number().optional().nullable(),
  orderedDate: z.string().optional().nullable(),
  receivedDate: z.string().optional().nullable(),
  arrivalToHubDate: z.string().optional().nullable(),
  arrivalToCustomerDate: z.string().optional().nullable(),
  enmDeliveryStatus: z.coerce.number(),
  location: z.string().max(500).optional().nullable(),
  notes: z.string().optional().nullable(),
});

export type DeliveryFormData = z.infer<typeof deliverySchema>;

