// OrderLine.ts
// Generated by CodeCreator
import { z } from 'zod';

export interface OrderLine {
  id: number;
  fkOrderHeaderId: number;
  fkProductId: number;
  quantity: number;
  unitPrice: number;
  discountPercent: number | null;
  readonly unitCost: number | null;
  lineNumber: number;
  readonly lineTotal: number | null;
  readonly totalCost: number | null;
  readonly profit: number | null;
  /** Concurrency control: hash of record state at time of GET */
  _etag?: string;
}

export interface CreateOrderLineRequest {
  fkOrderHeaderId: number;
  fkProductId: number;
  quantity: number;
  unitPrice: number;
  discountPercent?: number | null;
  lineNumber: number;
}

export type UpdateOrderLineRequest = CreateOrderLineRequest;

export const orderLineSchema = z.object({
  fkOrderHeaderId: z.coerce.number(),
  fkProductId: z.coerce.number(),
  quantity: z.coerce.number(),
  unitPrice: z.coerce.number(),
  discountPercent: z.coerce.number().optional().nullable(),
  lineNumber: z.coerce.number(),
});

export type OrderLineFormData = z.infer<typeof orderLineSchema>;

