// OrderHeader.ts
// Generated by CodeCreator
import { z } from 'zod';

export interface OrderHeader {
  id: number;
  orderNumber: number;
  fkCustomerId: number;
  orderDate: string;
  readonly totalAmount: number | null;
  readonly vatAmount: number | null;
  readonly totalWithVat: number | null;
  enmPaymentMethod: number | null;
  enmPaymentStatus: number | null;
  paymentDate: string | null;
  invoiceNumber: string | null;
  enmDeliveryMethod: number | null;
  deliveryDate: string | null;
  enmDeliveryDay: number | null;
  enmOrderStatus: number | null;
  notes: string | null;
  notes2: string | null;
  readonly orderMonth: string | null;
  readonly quarter: string | null;
  /** Concurrency control: hash of record state at time of GET */
  _etag?: string;
}

export interface CreateOrderHeaderRequest {
  orderNumber: number;
  fkCustomerId: number;
  orderDate: string;
  enmPaymentMethod?: number | null;
  enmPaymentStatus?: number | null;
  paymentDate?: string | null;
  invoiceNumber?: string | null;
  enmDeliveryMethod?: number | null;
  deliveryDate?: string | null;
  enmDeliveryDay?: number | null;
  enmOrderStatus?: number | null;
  notes?: string | null;
  notes2?: string | null;
}

export type UpdateOrderHeaderRequest = CreateOrderHeaderRequest;

export const orderHeaderSchema = z.object({
  orderNumber: z.coerce.number(),
  fkCustomerId: z.coerce.number(),
  orderDate: z.string().min(1, 'Order Date is required'),
  enmPaymentMethod: z.coerce.number().optional().nullable(),
  enmPaymentStatus: z.coerce.number().optional().nullable(),
  paymentDate: z.string().optional().nullable(),
  invoiceNumber: z.string().max(50).optional().nullable(),
  enmDeliveryMethod: z.coerce.number().optional().nullable(),
  deliveryDate: z.string().optional().nullable(),
  enmDeliveryDay: z.coerce.number().optional().nullable(),
  enmOrderStatus: z.coerce.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  notes2: z.string().optional().nullable(),
});

export type OrderHeaderFormData = z.infer<typeof orderHeaderSchema>;

