// ProductPrice.ts
// Generated by CodeCreator
import { z } from 'zod';

export interface ProductPrice {
  id: number;
  fkProductId: number;
  enmCustomerType: number;
  sellingPrice: number;
  minQuantity: number | null;
  discountPercent: number | null;
  notes: string | null;
  /** Concurrency control: hash of record state at time of GET */
  _etag?: string;
}

export interface CreateProductPriceRequest {
  fkProductId: number;
  enmCustomerType: number;
  sellingPrice: number;
  minQuantity?: number | null;
  discountPercent?: number | null;
  notes?: string | null;
}

export type UpdateProductPriceRequest = CreateProductPriceRequest;

export const productPriceSchema = z.object({
  fkProductId: z.coerce.number(),
  enmCustomerType: z.coerce.number(),
  sellingPrice: z.coerce.number(),
  minQuantity: z.coerce.number().optional().nullable(),
  discountPercent: z.coerce.number().optional().nullable(),
  notes: z.string().optional().nullable(),
});

export type ProductPriceFormData = z.infer<typeof productPriceSchema>;

