// Product.ts
// Generated by CodeCreator
import { z } from 'zod';

export interface Product {
  id: number;
  productCode: string;
  productName: string;
  enmCategory: number | null;
  unitOfMeasure: string | null;
  notes: string | null;
  readonly isActive: boolean | null;
  readonly currentStock: number | null;
  baseCost: number | null;
  /** Concurrency control: hash of record state at time of GET */
  _etag?: string;
}

export interface CreateProductRequest {
  productCode: string;
  productName: string;
  enmCategory?: number | null;
  unitOfMeasure?: string | null;
  notes?: string | null;
  baseCost?: number | null;
}

export type UpdateProductRequest = CreateProductRequest;

export const productSchema = z.object({
  productCode: z.string().min(1, 'Product Code is required').max(50),
  productName: z.string().min(1, 'Product Name is required').max(255),
  enmCategory: z.coerce.number().optional().nullable(),
  unitOfMeasure: z.string().max(20).optional().nullable(),
  notes: z.string().optional().nullable(),
  baseCost: z.coerce.number().optional().nullable(),
});

export type ProductFormData = z.infer<typeof productSchema>;

