<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>TargCCOrders.DataController</RootNamespace>
	  <TargetFramework>net9.0</TargetFramework>
    <OptionStrict>On</OptionStrict>
    <AssemblyName>TargCCOrders.WSStdController</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
